import type { GlossaryTerm } from "./types";

export const glossary: GlossaryTerm[] = [
  { term: "LLM (Large Language Model)", def: "A model trained on vast text to predict and generate language. Claude is a family of LLMs." },
  { term: "API", def: "Application Programming Interface — the way your code talks to Claude over HTTP, mainly the /v1/messages endpoint." },
  { term: "Token", def: "The unit a model reads and bills in — a chunk of ~3–4 characters of English. Pricing and limits are in tokens, not characters.", related: ["Context window"] },
  { term: "Context window", def: "The maximum total tokens a model can consider at once: system prompt, history, tools, documents, and the reply all share this budget.", related: ["Token"] },
  { term: "System prompt", def: "A top-level instruction that sets Claude's role, rules, tone, and output format for the whole conversation." },
  { term: "Message roles", def: "user (human input), assistant (Claude's replies), and system (global instructions). The first message must be user." },
  { term: "stop_reason", def: "Why generation stopped: end_turn (done), max_tokens (cut off), tool_use (wants a tool), or refusal." },
  { term: "max_tokens", def: "A cap on the number of OUTPUT tokens. Too low truncates the reply." },
  { term: "Temperature", def: "A 0–1 sampling parameter trading focus (low) for creativity (high). Removed on the newest models in favor of prompting + effort." },
  { term: "Streaming", def: "Receiving the reply incrementally as Server-Sent Events instead of one blocking response — better UX and timeout safety." },
  { term: "Multimodal", def: "Handling more than text. Claude accepts images and PDFs alongside text in a single message." },
  { term: "Prompt engineering", def: "The craft of writing clear, specific, structured instructions that produce reliable output." },
  { term: "Few-shot prompting", def: "Including 1–5 example input→output pairs in the prompt to lock format and behavior. Zero-shot uses instructions only." },
  { term: "Chain of thought (CoT)", def: "Prompting the model to reason step-by-step before answering, improving accuracy on multi-step problems." },
  { term: "Prompt caching", def: "Reusing a stable prompt prefix across requests to cut cost (~90%) and latency. A strict prefix match — any change invalidates it.", related: ["Context window"] },
  { term: "Evaluation (eval)", def: "A test suite for an AI feature: a dataset of inputs, a runner, and a grader that scores outputs.", related: ["Model-graded eval"] },
  { term: "Code-graded eval", def: "Scoring outputs with deterministic code (exact match, valid JSON, keyword presence)." },
  { term: "Model-graded eval", def: "Using another model as a judge to score open-ended quality against a rubric (LLM-as-judge).", related: ["Evaluation (eval)"] },
  { term: "Tool use (function calling)", def: "Letting Claude call functions you define. It emits a structured request; your code runs it and returns the result.", related: ["Agent"] },
  { term: "tool_use / tool_result", def: "The response block where Claude requests a tool, and the user block where you return the result (matched by tool_use_id)." },
  { term: "Structured outputs", def: "Constraining the response to a JSON Schema (or strict tool arguments) so the format is guaranteed, not hoped for." },
  { term: "tool_choice", def: "Controls tool freedom: auto (default), any (must use a tool), a named tool (must use that one), or none." },
  { term: "Agent", def: "Tool use in a loop — the model decides actions, observes results, and repeats toward a goal it wasn't given step-by-step.", related: ["Agentic loop", "Workflow"] },
  { term: "Agentic loop", def: "observe → think → act → observe, repeating until the task is done (stop_reason=end_turn).", related: ["Agent"] },
  { term: "Workflow", def: "A pipeline where YOUR code controls the fixed steps, as opposed to an agent where the model chooses them.", related: ["Agent"] },
  { term: "MCP (Model Context Protocol)", def: "An open standard for connecting AI to tools, data resources, and prompts. Build a connector once; any MCP-aware client can use it." },
  { term: "Managed Agents", def: "An Anthropic-hosted surface that runs the agent loop and a tool-execution container for you. Create an Agent once; run Sessions." },
  { term: "RAG (Retrieval-Augmented Generation)", def: "Retrieving relevant data and injecting it into the prompt so the model answers from your facts, not its training.", related: ["Embedding", "Vector search"] },
  { term: "Embedding", def: "A vector representing a text's meaning; similar meanings produce nearby vectors, enabling semantic search.", related: ["Vector search", "RAG (Retrieval-Augmented Generation)"] },
  { term: "Vector search", def: "Finding the chunks whose embeddings are nearest to the query's embedding (e.g. cosine similarity).", related: ["Embedding"] },
  { term: "Chunking", def: "Splitting documents into retrievable pieces (often a few hundred tokens with overlap) for embedding and retrieval." },
  { term: "Grounding", def: "Instructing the model to answer only from provided context, admit gaps, and cite sources — the core of trustworthy RAG." },
  { term: "Citations", def: "Linking each claim in the answer back to the exact source text. Claude supports native document citations." },
  { term: "Context editing", def: "Automatically clearing stale tool results / thinking blocks from a long transcript (pruning).", related: ["Compaction"] },
  { term: "Compaction", def: "Summarizing earlier conversation history into a compact block to stay within the context window (summarizing).", related: ["Context editing"] },
  { term: "Memory tool", def: "A files directory Claude reads/writes to persist state across sessions — true cross-session memory." },
  { term: "Adaptive thinking", def: "Native reasoning where Claude decides how much to think per request, scaled by the effort setting." },
  { term: "Effort", def: "A dial (low / medium / high / xhigh / max) controlling reasoning depth and token spend on modern models." },
  { term: "Thinking block", def: "A response block containing Claude's internal reasoning, which you can display (summarized) or hide." },
  { term: "Server tools", def: "Tools Anthropic hosts and executes (web search, web fetch, code execution); results return inline with no execution loop for you." },
  { term: "Refusal", def: "When Claude declines a harmful request: a normal HTTP 200 with stop_reason='refusal'. Handle it as a branch, not an error." },
  { term: "Batch API", def: "Asynchronous bulk processing of requests at ~50% cost for non-latency-sensitive workloads." },
  { term: "Model ID", def: "The exact string selecting a model (e.g. claude-opus-4-8). Invented or mistyped IDs return a 404." },
];
