import type { Pattern } from "./types";

export const patterns: Pattern[] = [
  {
    name: "The request/response contract",
    tagline: "One stateless POST to /v1/messages — you resend the whole conversation every turn.",
    diagram: "request-response",
    when: "The shape underneath every other pattern here. Reach for it directly whenever a task is one input and one output: classify, summarise, extract, rewrite, answer.",
    watch: "The API keeps no memory of previous calls. If a follow-up 'forgets' what was said, you almost certainly forgot to append the assistant's turn to the history you sent back.",
    accent: "clay",
  },
  {
    name: "The three-part prompt",
    tagline: "Stable system instructions, structured user content, then the actual ask — in that order.",
    diagram: "prompt-anatomy",
    when: "Any prompt you expect to run more than once. Separating the role, the material, and the question is what makes a prompt editable later instead of a wall you're afraid to touch.",
    watch: "Burying the question at the top and the document below it costs you accuracy on long inputs. Put long context first and the instruction last — and it makes the prefix cacheable as a bonus.",
    accent: "clay",
  },
  {
    name: "Model tiering",
    tagline: "Haiku for the easy majority, Sonnet for the middle, Opus for the hard tail.",
    diagram: "model-tiers",
    when: "Any workload with volume. Most requests in a real product are easy — routing, tagging, short extraction — and never needed the frontier model you defaulted to.",
    watch: "Tier on evidence, not vibes. Build the eval first, then downgrade one step at a time and watch it. Downgrading blind is how a silent quality regression ships on a Friday.",
    accent: "sage",
  },
  {
    name: "Prompt caching",
    tagline: "Freeze the long prefix; pay ~10% to read it back instead of full price to resend it.",
    diagram: "caching",
    when: "Whenever the same large block — a system prompt, a document, a tool list — leads many requests. It is the single highest-leverage cost change available, and it needs no architectural rework.",
    watch: "Caching is a prefix match: one changed byte anywhere invalidates everything after it. A timestamp or request ID in the system prompt silently drops your hit rate to zero — check usage.cache_read_input_tokens rather than assuming.",
    accent: "ochre",
  },
  {
    name: "Streaming the response",
    tagline: "Emit tokens as they're produced instead of waiting for the final message.",
    diagram: "streaming",
    when: "Any user-facing surface, and any request with a large max_tokens — long non-streaming responses run into HTTP timeouts before they run into the model's limits.",
    watch: "Streaming changes your error handling, not just your UI: a failure can now arrive halfway through rendered text. Decide up front whether a partial answer is shown, retracted, or retried.",
    accent: "sage",
  },
  {
    name: "The tool-use loop",
    tagline: "Call, inspect stop_reason, execute, return results, repeat until end_turn.",
    diagram: "tool-loop",
    when: "The moment the model needs a fact it can't know or an action it can't take — live data, a database, a write to your system.",
    watch: "When the model asks for several tools at once, run them and return every tool_result in a single user message. Splitting them across messages quietly teaches the model to stop asking in parallel.",
    accent: "clay",
  },
  {
    name: "Workflow before agent",
    tagline: "If you can draw the steps, write the steps; save the loop for genuinely open-ended work.",
    diagram: "agent-vs-workflow",
    when: "At the start of every design. A fixed chain of calls you orchestrate is cheaper, faster, and far easier to debug than a model deciding its own path.",
    watch: "Agents earn their cost only when the task is hard to specify in advance and errors are recoverable. 'Agentic' is a property of the problem, not a compliment you pay your architecture.",
    accent: "slateblue",
  },
  {
    name: "The agentic loop",
    tagline: "Give the model a goal, a toolbox, and permission to keep going until it's done.",
    diagram: "agentic-loop",
    when: "Multi-step, poorly specified work where the path can't be enumerated up front — investigate a bug, research a question, migrate a file tree.",
    watch: "Bound it before you ship it: a step ceiling, a token or task budget, and a stop condition you actually check. An unbounded loop with a paid tool in it is a bill, not a feature.",
    accent: "slateblue",
  },
  {
    name: "Extended thinking",
    tagline: "Let the model reason before it answers, and pay for depth only where depth matters.",
    diagram: "thinking",
    when: "Multi-constraint reasoning, hard debugging, planning, maths — anywhere the first plausible answer is often the wrong one.",
    watch: "Thinking is billed whether or not you display it, and it is not a fix for a vague prompt. Tune depth with effort rather than reaching for a bigger model on every route.",
    accent: "ochre",
  },
  {
    name: "Retrieval-augmented generation",
    tagline: "Retrieve the relevant passages, ground the answer in them, cite what you used.",
    diagram: "rag-pipeline",
    when: "When answers must come from a corpus you control — too large for the window, changing too often to fine-tune on, or needing attribution.",
    watch: "Retrieval quality caps answer quality; no prompt recovers from the right passage never being fetched. Measure retrieval separately from generation or you'll debug the wrong half for a week.",
    accent: "sage",
  },
  {
    name: "MCP as the tool boundary",
    tagline: "Write the integration once as a server; every client that speaks MCP can use it.",
    diagram: "mcp",
    when: "When the same capability — your issue tracker, your warehouse, your internal docs — needs to reach more than one assistant or app.",
    watch: "A server is an API surface with a security boundary. Scope its tools narrowly and give each a description precise enough that the model picks it for the right reason, not just the familiar one.",
    accent: "slateblue",
  },
  {
    name: "The eval loop",
    tagline: "A fixed test set, a graded run, and a number you can move on purpose.",
    diagram: "eval-loop",
    when: "Before the second prompt change, not after the first incident. It is what turns 'this feels better' into a claim you can defend.",
    watch: "Build the set from real failures, not invented ones, and keep it small enough to run on every change. An eval suite nobody runs is documentation of an intention.",
    accent: "ochre",
  },
  {
    name: "Batch for the patient half",
    tagline: "Send non-urgent work asynchronously and pay half.",
    diagram: "ai-stack",
    when: "Backfills, nightly enrichment, bulk classification, eval sweeps — anything where a result in hours is as useful as a result in seconds.",
    watch: "Results come back in any order; key them by custom_id, never by position. And split the workload honestly — a request a user is waiting on does not belong here.",
    accent: "sage",
  },
  {
    name: "Context as a budget",
    tagline: "A large window is an allowance, not an invitation to spend it.",
    diagram: "context-management",
    when: "Long conversations and long-running agents, where history grows monotonically and quality quietly decays as the signal thins.",
    watch: "Decide deliberately between clearing old tool results, compacting history into a summary, and writing state to memory — they solve different problems, and reaching for the wrong one loses the detail you needed.",
    accent: "slateblue",
  },
];
