import type { GlossaryTerm } from "./types";

export const glossary: GlossaryTerm[] = [
  { term: "Availability Zone (AZ)", def: "One or more isolated data centers within a Region, with independent power, cooling, and networking. Spread workloads across AZs for resilience.", related: ["Region", "High availability"] },
  { term: "Auto Scaling Group", def: "AWS construct that keeps a fleet of VMs between a min and max count and scales on a policy (e.g. target CPU). Azure's equivalent is a VM Scale Set.", related: ["Autoscaling", "Load balancer"] },
  { term: "Autoscaling", def: "Automatically adding or removing compute capacity in response to demand, so you pay for what the moment needs and survive spikes.", related: ["Auto Scaling Group", "Elasticity"] },
  { term: "AMI", def: "Amazon Machine Image — a boot image (OS + preinstalled software) an EC2 instance starts from. Azure's equivalent is a VM Image.", related: ["EC2", "Virtual machine"] },
  { term: "Blob Storage", def: "Azure's object storage service for unstructured data in containers. AWS's equivalent is S3.", related: ["Object storage", "S3"] },
  { term: "Block storage", def: "A raw virtual disk attached to a single VM (AWS EBS, Azure Managed Disks), formatted with a filesystem — ideal for boot volumes and databases.", related: ["EBS", "Object storage"] },
  { term: "Bucket", def: "A container for objects in object storage (S3). Addressed by name; holds objects identified by keys. Azure calls it a container.", related: ["Object storage", "S3"] },
  { term: "CDN", def: "Content Delivery Network — caches content at global edge locations near users to cut latency and offload the origin (AWS CloudFront, Azure CDN/Front Door).", related: ["Edge location", "Latency"] },
  { term: "CIDR block", def: "A range of IP addresses in slash notation (e.g. 10.0.0.0/16). Defines a virtual network's or subnet's address space. Smaller slash number = bigger network.", related: ["VPC", "Subnet"] },
  { term: "Container", def: "A lightweight, portable package of an app plus its dependencies that shares the host OS kernel, starting in milliseconds and running identically anywhere.", related: ["Kubernetes", "Serverless"] },
  { term: "Durability", def: "The probability that stored data is not lost. Object storage advertises ~eleven nines via cross-AZ replication. Distinct from availability.", related: ["Availability", "Object storage"] },
  { term: "EBS", def: "Elastic Block Store — AWS block storage; a durable disk volume attached to an EC2 instance. Azure's equivalent is Managed Disks.", related: ["Block storage", "EC2"] },
  { term: "EC2", def: "Elastic Compute Cloud — AWS virtual machines, billed by the second. Azure's equivalent is Virtual Machines.", related: ["Virtual machine", "AMI"] },
  { term: "Edge location", def: "A small point-of-presence (PoP) outside the main Regions used by CDNs and DNS to serve users with low latency.", related: ["CDN", "Region"] },
  { term: "Egress", def: "Data transfer out of the cloud to the internet, which is billed (inbound is usually free). Cross-region traffic also costs — a common bill surprise.", related: ["Data transfer", "Region"] },
  { term: "Elasticity", def: "The ability to scale resources up and down automatically with demand, paying only for what's used.", related: ["Autoscaling", "Cloud computing"] },
  { term: "File storage", def: "A shared filesystem over NFS/SMB that many VMs can mount at once (AWS EFS, Azure Files).", related: ["Block storage", "Object storage"] },
  { term: "High availability", def: "Designing so a component or zone failure doesn't cause downtime — typically via redundancy across multiple Availability Zones.", related: ["Availability Zone", "Load balancer"] },
  { term: "IaaS", def: "Infrastructure as a Service — renting raw compute, storage, and networking (e.g. VMs); you manage the OS and up.", related: ["PaaS", "SaaS"] },
  { term: "IAM", def: "Identity and Access Management — the service defining who (users/roles) can do what to which resources. Azure's equivalent is Entra ID + RBAC.", related: ["Shared responsibility model", "Least privilege"] },
  { term: "Internet Gateway", def: "A VPC component that lets resources in a public subnet send and receive traffic to/from the internet.", related: ["NAT gateway", "Public subnet"] },
  { term: "Kubernetes", def: "An open-source container orchestrator that schedules, scales, and heals containers across a cluster. Managed as EKS (AWS) or AKS (Azure).", related: ["Container", "ECS"] },
  { term: "Lambda", def: "AWS serverless functions — run code in response to events, scaling from zero and billing per invocation. Azure's equivalent is Azure Functions.", related: ["Serverless", "Cold start"] },
  { term: "Cold start", def: "The added latency when a serverless function scales from zero and the platform must initialize a fresh execution environment.", related: ["Lambda", "Serverless"] },
  { term: "Least privilege", def: "Granting each identity only the permissions it needs and no more — a core security principle enforced through IAM policies.", related: ["IAM", "Shared responsibility model"] },
  { term: "Load balancer", def: "A service that distributes incoming traffic across healthy instances and routes around failures via health checks (AWS ELB/ALB/NLB, Azure Load Balancer/App Gateway).", related: ["Autoscaling", "High availability"] },
  { term: "Managed Disks", def: "Azure block storage volumes attached to VMs. AWS's equivalent is EBS.", related: ["Block storage", "EBS"] },
  { term: "NACL", def: "Network ACL — a stateless, subnet-level firewall supporting allow and deny rules; a coarse layer complementing security groups.", related: ["Security group", "Subnet"] },
  { term: "NAT gateway", def: "Lets resources in a private subnet reach the internet outbound (updates, APIs) while staying unreachable inbound.", related: ["Private subnet", "Internet Gateway"] },
  { term: "Object storage", def: "Storage that keeps files as objects in a flat namespace (buckets), reached over HTTP; near-infinite scale, high durability, low cost (S3, Blob Storage).", related: ["S3", "Bucket"] },
  { term: "PaaS", def: "Platform as a Service — deploy code and the platform runs it with no servers or OS to manage (AWS Elastic Beanstalk, Azure App Service).", related: ["IaaS", "Serverless"] },
  { term: "Private subnet", def: "A subnet with no direct internet route; hosts app servers and databases, reaching out only via a NAT gateway.", related: ["Public subnet", "NAT gateway"] },
  { term: "Public subnet", def: "A subnet whose route table sends internet-bound traffic to an Internet Gateway; hosts internet-facing resources like load balancers.", related: ["Private subnet", "Internet Gateway"] },
  { term: "Region", def: "A distinct geographic area (e.g. us-east-1, East US) containing multiple Availability Zones. Chosen for latency, compliance, and cost.", related: ["Availability Zone", "Edge location"] },
  { term: "Reserved Instance", def: "A pricing model giving a large discount (up to ~72%) for committing to 1–3 years of usage. Azure calls these Reservations; Savings Plans are a flexible variant.", related: ["Spot instance", "On-demand"] },
  { term: "On-demand", def: "Paying full, flexible per-second/hour rates for compute with no commitment — the baseline pricing model.", related: ["Reserved Instance", "Spot instance"] },
  { term: "Route 53", def: "AWS managed DNS with routing policies (latency, geo, weighted, failover) and health checks. Azure's equivalent is Azure DNS + Traffic Manager.", related: ["DNS", "CDN"] },
  { term: "DNS", def: "Domain Name System — translates human names into IP addresses. Managed DNS can also steer traffic with routing policies.", related: ["Route 53", "CDN"] },
  { term: "S3", def: "Simple Storage Service — AWS object storage; buckets of objects over HTTP with ~eleven nines of durability. Azure's equivalent is Blob Storage.", related: ["Object storage", "Blob Storage"] },
  { term: "SaaS", def: "Software as a Service — finished software used over the web with the vendor running everything (Microsoft 365, Salesforce).", related: ["PaaS", "IaaS"] },
  { term: "Security group", def: "A stateful, instance-level virtual firewall with allow-only rules — the primary everyday network control. Azure calls it a Network Security Group (NSG).", related: ["NACL", "WAF"] },
  { term: "Serverless", def: "Running code without managing servers; the platform provisions, scales from zero, and bills per use (Lambda, Azure Functions, Fargate).", related: ["Lambda", "Container"] },
  { term: "Shared responsibility model", def: "The split where the provider secures the cloud (hardware, facilities, service internals) and you secure what's in it (data, IAM, config).", related: ["IAM", "Least privilege"] },
  { term: "Spot instance", def: "Deeply discounted (up to ~90%) spare capacity that can be reclaimed with little notice — for fault-tolerant, interruptible workloads. Azure calls these Spot VMs.", related: ["Reserved Instance", "On-demand"] },
  { term: "Storage tier", def: "A storage class trading store cost against retrieval speed/cost (hot/standard, cool/infrequent, archive/glacier). Lifecycle rules move data between them.", related: ["Object storage", "Durability"] },
  { term: "Subnet", def: "A subdivision of a virtual network's CIDR range, living in one Availability Zone; used to segment tiers and place resources across AZs.", related: ["VPC", "CIDR block"] },
  { term: "VM Scale Set", def: "Azure's construct for a fleet of identical VMs that scales automatically. AWS's equivalent is an Auto Scaling Group.", related: ["Auto Scaling Group", "Autoscaling"] },
  { term: "Virtual machine", def: "A software-defined server running on the provider's hardware, launched in minutes and billed by the second (EC2, Azure VMs).", related: ["EC2", "Container"] },
  { term: "VPC", def: "Virtual Private Cloud — your isolated private network on AWS. Azure's equivalent is a VNet.", related: ["VNet", "Subnet"] },
  { term: "VNet", def: "Virtual Network — your isolated private network on Azure. AWS's equivalent is a VPC.", related: ["VPC", "Subnet"] },
  { term: "WAF", def: "Web Application Firewall — inspects HTTP (Layer 7) traffic to block attacks like SQL injection and XSS and enforce rate limits.", related: ["Security group", "CDN"] },
  { term: "Well-Architected Framework", def: "A structured set of pillars (operational excellence, security, reliability, performance, cost, sustainability) to review cloud designs against. Azure has an equivalent WAF.", related: ["High availability", "Shared responsibility model"] },
  { term: "Availability", def: "The probability you can access a resource right now (e.g. 99.9%). Lower than durability, and varies by service and design.", related: ["Durability", "High availability"] },
  { term: "Data transfer", def: "Movement of data between the internet, regions, and zones. Outbound (egress) and cross-region transfer are billed — often an overlooked cost.", related: ["Egress", "Region"] },
  { term: "ECS", def: "Elastic Container Service — AWS's simpler container orchestrator (vs Kubernetes/EKS). Runs containers, optionally serverless via Fargate.", related: ["Kubernetes", "Container"] },
  { term: "Cloud computing", def: "On-demand delivery of compute, storage, and services over the internet with pay-as-you-go pricing, replacing owned hardware.", related: ["Elasticity", "IaaS"] },
];
