import type { Module } from "./types";

export const cicd: Module = {
  id: "cicd",
  title: "CI/CD & GitHub Actions",
  blurb: "Automating the path from commit to production: pipeline concepts, hands-on GitHub Actions, testing and quality gates, and safe deployment strategies.",
  accent: "rose",
  lessons: [
    {
      slug: "ci-cd-concepts",
      title: "CI/CD, concretely",
      summary:
        "The anatomy of a pipeline — triggers, jobs, steps, and runners — and the principles that make continuous integration and delivery actually work.",
      minutes: 9,
      blocks: [
        { type: "p", text: "You met the delivery pipeline in the foundations module. Now we go hands-on with **CI/CD** — the automation that turns every commit into a tested artifact and, ideally, a running deployment. First, the shared vocabulary every CI system uses." },
        { type: "diagram", name: "pipeline-stages", caption: "A push triggers a pipeline of jobs; each job runs steps on a runner, and gates stop bad changes progressing." },
        { type: "h2", text: "Anatomy of a pipeline" },
        { type: "list", items: [
          "**Trigger (event)** — what starts the pipeline: a push, a pull request, a tag, a schedule, or a manual run.",
          "**Pipeline / workflow** — the whole automated process defined as code (YAML) in the repo.",
          "**Job** — a unit of the pipeline that runs on one machine; jobs can run in parallel or depend on each other.",
          "**Step** — a single command or action within a job (checkout, install, test, build).",
          "**Runner / agent** — the machine that executes a job (cloud-hosted or self-hosted).",
          "**Artifact** — a file produced by a job (a container image, a binary, a test report) passed on or published.",
        ]},
        { type: "callout", kind: "key", text: "Pipelines are defined as code and live in the repo alongside the app. That means your build/test/deploy process is versioned, reviewed, and reproducible — the same discipline you apply to application code." },
        { type: "h2", text: "The principles that make CI work" },
        { type: "list", ordered: true, items: [
          "**Integrate frequently.** Merge small changes to main many times a day — big infrequent merges defeat the point.",
          "**Every commit triggers a build + test.** Automatic, no exceptions.",
          "**Keep the build fast.** A slow pipeline (>10 min) kills the feedback loop; parallelize and cache.",
          "**Fix a broken build immediately.** A red main branch blocks everyone — it's the top priority.",
          "**Build once, promote the same artifact.** Build the image once and move that exact artifact through staging → prod; never rebuild per environment.",
        ]},
        { type: "callout", kind: "warn", text: "'Build once, deploy everywhere' is critical. If you rebuild the artifact for each environment, you're testing something different from what you ship. Build one immutable image, then promote that identical artifact through every stage." },
        { type: "h2", text: "The landscape" },
        { type: "compare", caption: "Common CI/CD platforms.", columns: ["Tool", "Style", "Notes"], rows: [
          { label: "GitHub Actions", cells: ["YAML in repo, event-driven", "Tightly integrated with GitHub; huge marketplace"] },
          { label: "GitLab CI", cells: ["YAML in repo", "Bundled with GitLab; strong all-in-one"] },
          { label: "Jenkins", cells: ["Groovy pipelines, self-hosted", "Very flexible, older, more to maintain"] },
          { label: "Argo CD / Flux", cells: ["GitOps CD (pull-based)", "Deploy side; covered in the GitOps module"] },
        ]},
        { type: "callout", kind: "note", text: "There's a split: **CI tools** (GitHub Actions, Jenkins) push changes out, while **GitOps CD tools** (Argo CD, Flux) pull desired state from Git into the cluster. Many teams use both — Actions to build and test, Argo CD to deploy. We use GitHub Actions here and cover GitOps later." },
      ],
      takeaways: [
        "A pipeline has triggers (events), jobs (on runners), steps (commands), and produces artifacts — all defined as versioned code in the repo.",
        "CI principles: integrate frequently, build+test every commit, keep it fast, fix red builds first.",
        "Build the artifact once and promote that identical image through environments — never rebuild per stage.",
        "CI tools push changes; GitOps CD tools pull desired state — many teams combine GitHub Actions with Argo CD.",
      ],
      flashcards: [
        { front: "Job vs step vs runner", back: "A job is a unit of the pipeline running on one machine; a step is a single command within a job; a runner is the machine that executes the job." },
        { front: "Why 'build once, deploy everywhere'?", back: "Rebuilding per environment means you ship something you never tested. Build one immutable artifact and promote that exact image through staging to production." },
        { front: "What are three principles of good CI?", back: "Integrate small changes frequently; build and test on every commit automatically; keep the build fast and fix a broken main branch immediately." },
      ],
      quiz: [
        { q: "Why should you build an artifact once and promote it?", options: ["To save disk space", "So you deploy exactly what you tested, not a rebuild", "Because rebuilding is impossible", "To avoid using a registry"], answer: 1, explain: "Rebuilding per environment risks shipping something different from what passed tests; promoting one immutable artifact guarantees parity." },
        { q: "In CI/CD vocabulary, what runs the steps of a job?", options: ["A trigger", "An artifact", "A runner", "A commit"], answer: 2, explain: "A runner (or agent) is the machine that executes a job's steps." },
      ],
    },
    {
      slug: "github-actions",
      title: "Hands-on GitHub Actions",
      summary:
        "Build a real CI workflow: triggers, jobs, steps, marketplace actions, secrets, and matrix builds — the YAML you'll write most.",
      minutes: 11,
      blocks: [
        { type: "p", text: "**GitHub Actions** is GitHub's built-in CI/CD. Workflows are YAML files in `.github/workflows/` that run in response to repository events. Because it's event-driven and has a huge marketplace of reusable **actions**, it's the fastest way to automate a repo." },
        { type: "diagram", name: "gha-workflow", caption: "An event triggers a workflow; jobs run on runners, each job a sequence of steps that use actions or run commands." },
        { type: "h2", text: "The building blocks" },
        { type: "list", items: [
          "**Workflow** — a YAML file in `.github/workflows/`; has a name, triggers (`on`), and jobs.",
          "**Event (`on`)** — what triggers it: `push`, `pull_request`, `workflow_dispatch` (manual), `schedule` (cron).",
          "**Job** — runs on a `runs-on` runner (e.g. `ubuntu-latest`); jobs are parallel unless linked with `needs`.",
          "**Step** — either `run:` a shell command or `uses:` a prebuilt action from the marketplace.",
          "**Action** — a reusable unit (e.g. `actions/checkout`, `docker/build-push-action`).",
        ]},
        { type: "h2", text: "A complete CI workflow" },
        { type: "code", lang: "yaml", caption: ".github/workflows/ci.yml", code: "name: CI\non:\n  push: { branches: [main] }\n  pull_request:\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with: { node-version: 20, cache: npm }\n      - run: npm ci\n      - run: npm test\n\n  build-image:\n    needs: test              # only if tests pass\n    runs-on: ubuntu-latest\n    permissions: { contents: read, packages: write }\n    steps:\n      - uses: actions/checkout@v4\n      - uses: docker/login-action@v3\n        with:\n          registry: ghcr.io\n          username: ${{ github.actor }}\n          password: ${{ secrets.GITHUB_TOKEN }}\n      - uses: docker/build-push-action@v6\n        with:\n          push: true\n          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}" },
        { type: "callout", kind: "key", text: "Read that flow: on every push/PR the `test` job runs; only if it passes (`needs: test`) does `build-image` build and push a container tagged with the commit SHA. That's a complete CI pipeline — test gate, then an immutable, traceable artifact — in ~25 lines." },
        { type: "h2", text: "Secrets, variables & permissions" },
        { type: "list", items: [
          "**Secrets** — `${{ secrets.NAME }}` injects encrypted values (tokens, keys) set in repo settings; never hardcode them.",
          "**`GITHUB_TOKEN`** — an automatic, short-lived token scoped to the repo for the workflow run.",
          "**Least privilege** — set `permissions:` to the minimum each job needs.",
          "**Environments** — add required reviewers and protection rules to gate deploys to prod.",
        ]},
        { type: "h2", text: "Matrix builds & caching" },
        { type: "p", text: "A **matrix** runs the same job across combinations (OS × language version) in parallel. Caching dependencies (`cache: npm` above, or `actions/cache`) keeps pipelines fast." },
        { type: "code", lang: "yaml", caption: "Testing across versions in parallel", code: "strategy:\n  matrix:\n    node: [18, 20, 22]\nruns-on: ubuntu-latest\nsteps:\n  - uses: actions/checkout@v4\n  - uses: actions/setup-node@v4\n    with: { node-version: ${{ matrix.node }} }\n  - run: npm ci && npm test" },
        { type: "callout", kind: "warn", text: "Pin marketplace actions to a version (`actions/checkout@v4`) or, for untrusted third-party actions, to a full commit SHA. A `@main` reference means someone else's change runs in your pipeline with your secrets — a real supply-chain risk." },
      ],
      takeaways: [
        "GitHub Actions workflows are YAML in .github/workflows/, triggered by events (push, pull_request, schedule, manual).",
        "Jobs run on runners and hold steps that either run commands or use marketplace actions; `needs` chains jobs into gates.",
        "Inject secrets with ${{ secrets.NAME }}, use the automatic GITHUB_TOKEN, and set least-privilege permissions.",
        "Matrix builds parallelize across versions; cache dependencies for speed; pin actions to a version or SHA for supply-chain safety.",
      ],
      flashcards: [
        { front: "Where do GitHub Actions workflows live and what triggers them?", back: "YAML files in .github/workflows/, triggered by repository events via `on:` — push, pull_request, schedule (cron), or workflow_dispatch (manual)." },
        { front: "How do you make one job run only after another passes?", back: "Add `needs: <job-name>` to the dependent job — it runs only if the named job succeeds, forming a gate." },
        { front: "Why pin action versions or SHAs?", back: "Referencing `@main` runs someone else's latest code in your pipeline with access to your secrets — a supply-chain risk. Pin to a released version or a full commit SHA." },
      ],
      quiz: [
        { q: "How do you ensure a build job runs only after tests pass?", options: ["Put them in the same step", "Add `needs: test` to the build job", "Run them in a matrix", "Use two workflows"], answer: 1, explain: "`needs: test` makes the build job depend on the test job succeeding first — a quality gate." },
        { q: "What's the safest way to reference a third-party action?", options: ["@main", "@latest", "A pinned version tag or full commit SHA", "No version at all"], answer: 2, explain: "Pinning to a version or commit SHA prevents an upstream change from silently running in your pipeline with your secrets." },
      ],
    },
    {
      slug: "testing-and-quality-gates",
      title: "Testing & quality gates",
      summary:
        "What runs inside the pipeline to keep bad changes out — the test pyramid, plus the linting, coverage, and security scans that form your quality gates.",
      minutes: 9,
      blocks: [
        { type: "p", text: "A pipeline is only as valuable as the checks inside it. **Quality gates** are automated checks that must pass before a change can progress — they're how CI actually protects `main` and production." },
        { type: "h2", text: "The test pyramid" },
        { type: "p", text: "Not all tests are equal. The **test pyramid** guides the mix: many fast, cheap tests at the bottom; few slow, expensive ones at the top." },
        { type: "compare", caption: "The test pyramid, bottom to top.", columns: ["Layer", "Tests", "Speed / count"], rows: [
          { label: "Unit", cells: ["A single function/class in isolation", "Milliseconds — have many"] },
          { label: "Integration", cells: ["Components together (app + DB)", "Seconds — have some"] },
          { label: "End-to-end", cells: ["The whole system through the UI/API", "Minutes — have few"] },
        ]},
        { type: "callout", kind: "warn", text: "Beware the 'ice-cream cone' anti-pattern: mostly slow E2E tests and few unit tests. It's slow, flaky, and hard to debug. Push tests down the pyramid — fast unit tests catch most bugs cheapest." },
        { type: "h2", text: "The gates in a real pipeline" },
        { type: "list", items: [
          "**Linting & formatting** — catch style and simple errors instantly (ESLint, Ruff, gofmt).",
          "**Type checks** — catch whole classes of bugs before runtime (tsc, mypy).",
          "**Unit + integration tests** — the core correctness checks.",
          "**Code coverage threshold** — fail the build if coverage drops below a bar (used as a guardrail, not a target to game).",
          "**Security scanning** — SAST for code (CodeQL), dependency/SCA scans (Dependabot), image scans (Trivy), and secret scanning.",
          "**Build verification** — the artifact actually builds and the container image is produced.",
        ]},
        { type: "diagram", name: "pipeline-stages", caption: "Each gate must pass before the change progresses; a failure stops the line and reports back fast." },
        { type: "callout", kind: "key", text: "'Shift left' means moving checks as early as possible — lint and unit tests on every commit, security scans in the PR — so problems are caught when they're cheapest to fix, not in production. The earlier the gate, the cheaper the fix." },
        { type: "h2", text: "Branch protection ties it together" },
        { type: "p", text: "Gates only matter if they're enforced. **Branch protection rules** on `main` require the CI checks to pass and the PR to be reviewed before merge — making it structurally impossible to merge code that fails the pipeline. This is what keeps the main branch always releasable." },
        { type: "callout", kind: "tip", text: "Make the pipeline required, not advisory. If a green check is optional, under deadline pressure someone will skip it. Required status checks + review turn your quality gates into guarantees." },
      ],
      takeaways: [
        "Quality gates are automated checks that must pass before a change progresses — how CI protects main and prod.",
        "The test pyramid: many fast unit tests, some integration tests, few slow E2E tests — avoid the E2E-heavy ice-cream cone.",
        "Typical gates: lint, type check, unit/integration tests, coverage threshold, security scans (SAST/SCA/image/secrets), build.",
        "'Shift left' catches issues early and cheaply; branch protection makes passing checks + review mandatory to merge.",
      ],
      flashcards: [
        { front: "What is the test pyramid?", back: "A guide to test mix: many fast unit tests at the base, fewer integration tests in the middle, and few slow end-to-end tests at the top." },
        { front: "What does 'shift left' mean?", back: "Moving checks (lint, tests, security scans) as early in the pipeline as possible so defects are caught when they're cheapest to fix, not in production." },
        { front: "How do quality gates become guarantees rather than suggestions?", back: "Branch-protection rules make CI checks and code review required before merging to main — you structurally can't merge failing code." },
      ],
      quiz: [
        { q: "Which test type should you have the MOST of?", options: ["End-to-end", "Manual", "Unit", "Load"], answer: 2, explain: "The test pyramid favors many fast, cheap unit tests at the base and few slow E2E tests at the top." },
        { q: "What makes a quality gate actually enforced?", options: ["A team agreement", "Branch protection requiring the check to pass before merge", "A comment in the README", "Running it nightly"], answer: 1, explain: "Required status checks via branch protection make it impossible to merge code that fails the pipeline." },
      ],
    },
    {
      slug: "deployment-strategies",
      title: "Deployment strategies",
      summary:
        "How to release a new version without breaking users — rolling, blue-green, and canary deployments, plus feature flags and instant rollback.",
      minutes: 10,
      blocks: [
        { type: "p", text: "Getting a tested artifact built is half the job; **releasing it safely** is the other half. The goal is zero-downtime deploys where a bad version affects as few users as possible and can be reversed instantly." },
        { type: "diagram", name: "deployment-strategies", caption: "Rolling replaces gradually; blue-green switches all at once; canary shifts a slice of traffic first." },
        { type: "h2", text: "The main strategies" },
        { type: "compare", caption: "Trade cost and complexity for safety.", columns: ["Strategy", "How it works", "Trade-off"], rows: [
          { label: "Rolling update", cells: ["Replace old pods with new ones incrementally", "No extra cost; both versions live briefly"] },
          { label: "Blue-green", cells: ["Stand up new (green) alongside old (blue), switch traffic at once", "Instant rollback; needs 2× capacity"] },
          { label: "Canary", cells: ["Send a small % of traffic to the new version, watch, then ramp", "Safest; needs traffic-shifting + good metrics"] },
          { label: "Recreate", cells: ["Stop all old, start all new", "Simple but causes downtime"] },
        ]},
        { type: "h2", text: "How to choose" },
        { type: "list", items: [
          "**Rolling** is the sensible default (and Kubernetes' built-in behavior) — free and zero-downtime for stateless apps.",
          "**Blue-green** when you need an instant, clean switch and rollback, and can afford double capacity briefly.",
          "**Canary** for high-risk changes on high-traffic services — you limit the blast radius to a few percent of users and promote only if metrics stay healthy.",
        ]},
        { type: "callout", kind: "key", text: "Canary is the gold standard for risk reduction: release to 5% of traffic, watch error rate and latency, and automatically roll back if they degrade — or promote to 100% if they don't. A bad deploy hits 5% of users for two minutes instead of everyone." },
        { type: "h2", text: "Feature flags & rollback" },
        { type: "p", text: "**Feature flags** decouple *deploy* from *release*: ship code dark (flag off), then turn a feature on for a cohort at runtime — no redeploy to enable or disable. Combined with the strategies above, they give fine-grained control and an instant kill switch." },
        { type: "callout", kind: "key", text: "The single most important operational property is fast, reliable rollback. Immutable, versioned artifacts make this trivial — redeploy the previous known-good image (or `kubectl rollout undo`). If you can roll back in seconds, every deploy is low-stakes." },
        { type: "callout", kind: "note", text: "Progressive delivery — automated canary and blue-green driven by metrics — is often run by GitOps tools like Argo Rollouts, which the GitOps & Argo CD module builds on." },
      ],
      takeaways: [
        "Release safely for zero downtime and minimal blast radius: rolling (default), blue-green (instant switch, 2× capacity), canary (traffic slice first).",
        "Rolling is Kubernetes' free default; blue-green gives clean instant rollback; canary limits a bad deploy to a few percent of users.",
        "Feature flags decouple deploy from release — ship dark, enable at runtime, and kill instantly without a redeploy.",
        "Fast, reliable rollback (redeploy the previous immutable image) is the most important operational property — it makes every deploy low-stakes.",
      ],
      flashcards: [
        { front: "Blue-green vs canary deployment", back: "Blue-green stands up a full new version and switches all traffic at once (instant rollback, needs 2× capacity). Canary shifts a small % of traffic to the new version first, watches metrics, then ramps up." },
        { front: "What do feature flags decouple?", back: "Deploy from release — you can ship code with a feature turned off (dark), then enable it for a cohort at runtime and kill it instantly, all without redeploying." },
        { front: "Why is fast rollback so important?", back: "It makes every deploy low-stakes: if a release misbehaves you revert to the previous known-good immutable image in seconds (e.g. `kubectl rollout undo`), limiting user impact." },
      ],
      quiz: [
        { q: "Which strategy exposes a new version to only a small % of users first?", options: ["Recreate", "Rolling", "Canary", "Blue-green"], answer: 2, explain: "Canary routes a small slice of traffic to the new version, watches metrics, and ramps up only if it stays healthy." },
        { q: "What do feature flags let you do?", options: ["Rebuild images faster", "Turn features on/off at runtime without redeploying", "Skip testing", "Replace Kubernetes"], answer: 1, explain: "Feature flags decouple deploy from release, enabling runtime toggling and an instant kill switch without a redeploy." },
      ],
    },
  ],
};
