import type { Module } from "./types";

export const kubernetes: Module = {
  id: "kubernetes",
  title: "Kubernetes",
  blurb: "The container orchestrator that runs production: its architecture, the core workload objects, networking with Services and Ingress, and config, secrets & scaling.",
  accent: "amber",
  lessons: [
    {
      slug: "kubernetes-architecture",
      title: "Why Kubernetes & how it's built",
      summary:
        "Kubernetes schedules, heals, and scales containers across a fleet of machines. Meet the control plane, the nodes, and the reconciliation loop that drives it all.",
      minutes: 10,
      blocks: [
        { type: "p", text: "Running one container is easy. Running hundreds across many machines — restarting the ones that crash, moving them off failed hosts, rolling out new versions without downtime, and scaling with load — is hard. **Kubernetes (K8s)** is the open-source **orchestrator** that does exactly that." },
        { type: "callout", kind: "key", text: "Kubernetes' core idea is declarative reconciliation: you describe the desired state ('run 3 replicas of this image'), and K8s continuously works to make reality match — restarting, rescheduling, and scaling on its own. You declare the what; it handles the how." },
        { type: "diagram", name: "k8s-architecture", caption: "A control plane makes decisions; worker nodes run the pods. The API server is the hub everything talks through." },
        { type: "h2", text: "The control plane" },
        { type: "p", text: "The **control plane** is the brain of the cluster. Its components:" },
        { type: "list", items: [
          "**API server** — the front door. Every command and component talks to it (via `kubectl` or the API). It's the only thing that writes to etcd.",
          "**etcd** — the cluster's database: a consistent key-value store holding all cluster state (the source of truth).",
          "**Scheduler** — decides which node each new pod should run on, based on resources and constraints.",
          "**Controller manager** — runs the reconciliation loops (e.g. the Deployment controller) that drive actual state toward desired state.",
        ]},
        { type: "h2", text: "The worker nodes" },
        { type: "p", text: "**Nodes** are the machines (VMs or bare metal) that actually run your containers. Each node runs:" },
        { type: "list", items: [
          "**kubelet** — the agent that talks to the API server and makes sure the pods it's assigned are running and healthy.",
          "**Container runtime** — containerd or CRI-O, which actually pulls images and runs containers.",
          "**kube-proxy** — programs networking rules so traffic reaches the right pods.",
        ]},
        { type: "h2", text: "The reconciliation loop" },
        { type: "p", text: "Everything in Kubernetes is a **controller** running the same loop: *observe* the current state, *compare* it to the desired state stored in etcd, and *act* to close the gap — forever. Delete a pod and the Deployment controller notices the shortfall and creates a replacement within seconds. This self-healing is why K8s is declarative, not imperative." },
        { type: "callout", kind: "note", text: "You rarely run Kubernetes by hand. Managed services — EKS (AWS), AKS (Azure), GKE (Google) — run the control plane for you, so you only manage worker nodes and workloads. Learning is easiest with a local cluster: kind, minikube, or k3s." },
        { type: "callout", kind: "tip", text: "You interact with the cluster almost entirely through `kubectl` talking to the API server: `kubectl get pods`, `kubectl apply -f app.yaml`, `kubectl logs`, `kubectl describe`. Learn those four and you can navigate any cluster." },
      ],
      takeaways: [
        "Kubernetes is a container orchestrator: it schedules, heals, scales, and rolls out containers across many machines.",
        "It's declarative — you specify desired state and controllers reconcile reality toward it continuously (self-healing).",
        "Control plane = API server (front door) + etcd (state) + scheduler (placement) + controller manager (loops).",
        "Worker nodes run kubelet, a container runtime, and kube-proxy; managed services (EKS/AKS/GKE) run the control plane for you.",
      ],
      flashcards: [
        { front: "What is Kubernetes' core idea?", back: "Declarative reconciliation: you declare desired state (e.g. 3 replicas), and controllers continuously observe, compare, and act to make actual state match — self-healing and self-scaling." },
        { front: "Name the control plane components", back: "API server (front door), etcd (state store), scheduler (assigns pods to nodes), and controller manager (runs reconciliation loops)." },
        { front: "What runs on a worker node?", back: "kubelet (node agent that ensures assigned pods run), a container runtime (containerd/CRI-O), and kube-proxy (networking rules)." },
      ],
      quiz: [
        { q: "What does 'declarative' mean in Kubernetes?", options: ["You script each step imperatively", "You declare desired state and controllers reconcile toward it", "You must restart pods manually", "It only works with YAML comments"], answer: 1, explain: "You declare the desired end state; Kubernetes' controllers continuously act to make reality match, without step-by-step instructions." },
        { q: "Which component is the single source of truth for cluster state?", options: ["kubelet", "etcd", "kube-proxy", "The scheduler"], answer: 1, explain: "etcd is the consistent key-value store holding all cluster state; only the API server writes to it." },
      ],
    },
    {
      slug: "pods-deployments-workloads",
      title: "Pods, ReplicaSets & Deployments",
      summary:
        "The workload objects you actually create — the pod as the atom of scheduling, and the Deployment that keeps replicas running and rolls out new versions.",
      minutes: 10,
      blocks: [
        { type: "p", text: "You don't run 'containers' directly in Kubernetes. You create higher-level **objects** and let controllers manage the containers for you. The ladder of workload objects starts with the pod." },
        { type: "diagram", name: "k8s-objects", caption: "A Deployment manages ReplicaSets, which manage Pods, which wrap containers." },
        { type: "h2", text: "Pods — the atom" },
        { type: "p", text: "A **Pod** is the smallest deployable unit: one or more containers that share a network address and storage, always scheduled together on one node. Usually a pod is a single app container (plus maybe a helper 'sidecar'). Pods are **ephemeral and cattle, not pets** — they're created and destroyed freely, each getting a fresh identity. You almost never create bare pods yourself." },
        { type: "callout", kind: "key", text: "Pods are disposable. Never depend on a specific pod staying alive or keeping its IP — it can be killed and replaced at any time. This is a feature: it's what makes self-healing and rolling updates possible." },
        { type: "h2", text: "ReplicaSets — keeping N alive" },
        { type: "p", text: "A **ReplicaSet** ensures a specified number of identical pod replicas are running. If one dies, it creates a replacement; if there are too many, it removes some. You rarely create these directly either — a Deployment manages them for you." },
        { type: "h2", text: "Deployments — the one you use" },
        { type: "p", text: "A **Deployment** is the object you'll create most. It manages ReplicaSets to give you **declarative updates**: change the image tag, and the Deployment performs a **rolling update** — gradually replacing old pods with new ones so there's no downtime — and can **roll back** instantly if the new version misbehaves." },
        { type: "code", lang: "yaml", caption: "A Deployment: 3 replicas of an app", code: "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: api\nspec:\n  replicas: 3\n  selector:\n    matchLabels: { app: api }\n  template:\n    metadata:\n      labels: { app: api }\n    spec:\n      containers:\n        - name: api\n          image: ghcr.io/acme/api:v1.4.0\n          ports: [{ containerPort: 8080 }]" },
        { type: "code", lang: "bash", caption: "Rolling out and rolling back", code: "kubectl apply -f deployment.yaml           # create/update\nkubectl set image deploy/api api=ghcr.io/acme/api:v1.5.0  # roll out\nkubectl rollout status deploy/api          # watch it\nkubectl rollout undo deploy/api            # instant rollback" },
        { type: "h2", text: "Other workload types" },
        { type: "compare", caption: "Pick the controller that matches the workload.", columns: ["Object", "Use for", "Key trait"], rows: [
          { label: "Deployment", cells: ["Stateless apps (web, APIs)", "Rolling updates, any pod interchangeable"] },
          { label: "StatefulSet", cells: ["Stateful apps (databases)", "Stable identity + storage per pod"] },
          { label: "DaemonSet", cells: ["One pod per node (agents, log collectors)", "Runs everywhere"] },
          { label: "Job / CronJob", cells: ["Run-to-completion / scheduled tasks", "Batch, not long-running"] },
        ]},
        { type: "callout", kind: "tip", text: "Labels and selectors are the glue of Kubernetes. A Deployment finds its pods, and a Service finds its endpoints, by matching labels (`app: api`) — not by name. Get labels right and everything connects." },
      ],
      takeaways: [
        "A Pod is the smallest unit — one or more co-scheduled containers sharing network and storage; treat pods as disposable cattle.",
        "A ReplicaSet keeps N identical pods running; you rarely create it directly.",
        "A Deployment is the object you use for stateless apps: declarative rolling updates and instant rollbacks.",
        "Use StatefulSets for stateful apps, DaemonSets for per-node agents, and Jobs/CronJobs for batch work. Labels/selectors connect it all.",
      ],
      flashcards: [
        { front: "What is a Pod?", back: "The smallest deployable unit in Kubernetes: one or more containers sharing a network identity and storage, always scheduled together. Ephemeral and disposable." },
        { front: "What does a Deployment give you over a bare pod?", back: "Declarative management of N replicas via ReplicaSets, with zero-downtime rolling updates and instant rollbacks when you change the image." },
        { front: "Deployment vs StatefulSet", back: "Deployment: stateless apps where pods are interchangeable. StatefulSet: stateful apps (databases) needing stable network identity and persistent per-pod storage." },
      ],
      quiz: [
        { q: "Which object should you use for a stateless web API?", options: ["StatefulSet", "DaemonSet", "Deployment", "CronJob"], answer: 2, explain: "Deployments manage interchangeable stateless replicas with rolling updates — ideal for web/API tiers." },
        { q: "You change a Deployment's image tag. What happens?", options: ["All pods restart at once", "A rolling update gradually replaces old pods with new ones", "Nothing until you restart the cluster", "The old pods keep running forever"], answer: 1, explain: "The Deployment performs a rolling update, replacing pods incrementally to avoid downtime — and can roll back if needed." },
      ],
    },
    {
      slug: "services-and-ingress",
      title: "Networking: Services & Ingress",
      summary:
        "Pods come and go with changing IPs, so how does traffic find them? Services give a stable address and load-balance; Ingress routes HTTP from the outside world.",
      minutes: 9,
      blocks: [
        { type: "p", text: "Pods are ephemeral and their IPs change constantly, so you can never point traffic at a pod directly. Kubernetes networking solves this with two objects: **Services** (stable internal addressing + load balancing) and **Ingress** (HTTP routing from outside)." },
        { type: "diagram", name: "k8s-networking", caption: "External traffic enters via Ingress → Service → healthy Pods; the Service is the stable front for a changing set of pods." },
        { type: "h2", text: "Services — a stable front door" },
        { type: "p", text: "A **Service** gives a set of pods (selected by label) a single **stable virtual IP and DNS name**, and load-balances traffic across the healthy ones. Pods behind it can scale, restart, and move — the Service address never changes. This decouples clients from the ever-changing pods." },
        { type: "compare", caption: "The Service types, from internal to external.", columns: ["Type", "Exposes to", "Use for"], rows: [
          { label: "ClusterIP", cells: ["Inside the cluster only (default)", "Internal service-to-service calls"] },
          { label: "NodePort", cells: ["A port on every node", "Basic external access, dev/testing"] },
          { label: "LoadBalancer", cells: ["A cloud load balancer with a public IP", "Exposing a service to the internet"] },
        ]},
        { type: "code", lang: "yaml", caption: "A ClusterIP Service fronting the api pods", code: "apiVersion: v1\nkind: Service\nmetadata:\n  name: api\nspec:\n  selector:\n    app: api          # matches the Deployment's pod labels\n  ports:\n    - port: 80        # the Service port\n      targetPort: 8080 # the container port\n  type: ClusterIP" },
        { type: "callout", kind: "key", text: "Services find their pods by label selector, not by name or IP. Any pod labeled `app: api` — however many, wherever scheduled — automatically becomes a healthy backend. That indirection is what makes scaling and self-healing transparent to clients." },
        { type: "h2", text: "Ingress — HTTP routing" },
        { type: "p", text: "Creating a cloud LoadBalancer per service is expensive. **Ingress** is a smarter layer 7 router: one entry point that routes HTTP(S) traffic to different Services based on **hostname and path** (`api.example.com` → api Service, `example.com/shop` → shop Service), and terminates **TLS**. It's implemented by an **ingress controller** (NGINX, Traefik) you run in the cluster." },
        { type: "code", lang: "yaml", caption: "An Ingress routing by host and path", code: "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: web\nspec:\n  rules:\n    - host: api.example.com\n      http:\n        paths:\n          - path: /\n            pathType: Prefix\n            backend:\n              service:\n                name: api\n                port: { number: 80 }" },
        { type: "callout", kind: "note", text: "The newer **Gateway API** is the evolving successor to Ingress, offering richer routing and cleaner separation of roles. Ingress remains the most widely deployed today, so learn it first." },
      ],
      takeaways: [
        "Pod IPs are ephemeral, so a Service gives a stable virtual IP + DNS name and load-balances across labeled pods.",
        "Service types: ClusterIP (internal, default), NodePort (a port per node), LoadBalancer (cloud LB with public IP).",
        "Services select pods by label — any matching pod automatically becomes a backend, making scaling transparent.",
        "Ingress is one L7 entry point routing HTTP(S) by host/path to Services and terminating TLS, run by an ingress controller.",
      ],
      flashcards: [
        { front: "Why can't you send traffic directly to a pod?", back: "Pods are ephemeral — they're created, destroyed, and rescheduled with changing IPs. A Service provides a stable address in front of them." },
        { front: "Name the three Service types", back: "ClusterIP (internal-only, default), NodePort (a static port on each node), and LoadBalancer (provisions a cloud load balancer with a public IP)." },
        { front: "What does Ingress do that a LoadBalancer Service doesn't?", back: "Ingress is one L7 entry point routing HTTP(S) to many Services by hostname/path and terminating TLS — instead of one cloud load balancer per service." },
      ],
      quiz: [
        { q: "How does a Service know which pods to send traffic to?", options: ["By pod name", "By a label selector", "By pod IP address", "By creation order"], answer: 1, explain: "A Service selects pods by label; any healthy pod matching the labels becomes a backend automatically." },
        { q: "You want host- and path-based HTTP routing with TLS for many services behind one entry point. Use…", options: ["A NodePort per service", "An Ingress", "A separate LoadBalancer per service", "ClusterIP only"], answer: 1, explain: "Ingress provides L7 host/path routing and TLS termination through a single entry point, avoiding a load balancer per service." },
      ],
    },
    {
      slug: "config-secrets-and-scaling",
      title: "Config, secrets, health & autoscaling",
      summary:
        "Keep configuration out of images with ConfigMaps and Secrets, let Kubernetes know when a pod is healthy with probes, and scale automatically with the HPA.",
      minutes: 10,
      blocks: [
        { type: "p", text: "The last piece is running workloads well in production: configuring them without rebuilding images, telling Kubernetes when they're healthy, and scaling them with demand." },
        { type: "h2", text: "ConfigMaps & Secrets" },
        { type: "p", text: "The same image should run in dev, staging, and prod — so configuration must live *outside* the image. **ConfigMaps** hold non-sensitive config (URLs, feature flags); **Secrets** hold sensitive values (passwords, API keys). Both are injected into pods as environment variables or mounted files." },
        { type: "code", lang: "yaml", caption: "Injecting config and a secret into a pod", code: "spec:\n  containers:\n    - name: api\n      image: ghcr.io/acme/api:v1.4.0\n      envFrom:\n        - configMapRef: { name: api-config }\n      env:\n        - name: DB_PASSWORD\n          valueFrom:\n            secretKeyRef: { name: api-secrets, key: db-password }" },
        { type: "callout", kind: "warn", text: "Kubernetes Secrets are only base64-encoded, NOT encrypted, by default — anyone with API access can read them. Enable encryption at rest, restrict access with RBAC, and for real security use an external manager (Vault, Sealed Secrets, or a cloud secrets store)." },
        { type: "h2", text: "Health probes" },
        { type: "p", text: "Kubernetes can't self-heal what it can't assess. **Probes** let it check pod health:" },
        { type: "list", items: [
          "**Liveness probe** — is the app alive? If it fails, Kubernetes restarts the container (recovers from deadlocks).",
          "**Readiness probe** — is the app ready for traffic? If it fails, the pod is removed from Service endpoints until it recovers (no requests to a warming-up or overloaded pod).",
          "**Startup probe** — for slow-starting apps, holds off the other probes until the app has booted.",
        ]},
        { type: "callout", kind: "key", text: "Liveness restarts; readiness routes. A failing liveness probe kills and restarts the container; a failing readiness probe just stops sending it traffic. Setting readiness correctly is what makes rolling updates truly zero-downtime." },
        { type: "h2", text: "Resource requests, limits & autoscaling" },
        { type: "p", text: "Each container declares **requests** (guaranteed resources the scheduler reserves) and **limits** (the ceiling it can't exceed). Requests drive scheduling; limits protect neighbors. With requests set, the **Horizontal Pod Autoscaler (HPA)** can add or remove pod replicas automatically based on CPU, memory, or custom metrics." },
        { type: "diagram", name: "k8s-scaling", caption: "The HPA watches metrics and adjusts the Deployment's replica count between a min and max." },
        { type: "code", lang: "yaml", caption: "An HPA: scale api between 3 and 20 pods at 70% CPU", code: "apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nmetadata:\n  name: api\nspec:\n  scaleTargetRef:\n    kind: Deployment\n    name: api\n  minReplicas: 3\n  maxReplicas: 20\n  metrics:\n    - type: Resource\n      resource:\n        name: cpu\n        target: { type: Utilization, averageUtilization: 70 }" },
        { type: "callout", kind: "note", text: "The HPA scales pods; the Cluster Autoscaler scales nodes to fit those pods. Together they let a cluster grow and shrink with demand — but the HPA only works if your containers have resource requests set." },
      ],
      takeaways: [
        "Keep config out of images: ConfigMaps for non-sensitive settings, Secrets for sensitive ones, injected as env vars or files.",
        "Secrets are only base64-encoded by default — enable encryption at rest, use RBAC, or an external secrets manager.",
        "Liveness probes restart unhealthy containers; readiness probes control whether a pod receives traffic (key to zero-downtime rollouts).",
        "Set resource requests/limits; the HPA then autoscales replicas on CPU/memory/custom metrics between a min and max.",
      ],
      flashcards: [
        { front: "ConfigMap vs Secret", back: "Both externalize configuration from the image. ConfigMaps hold non-sensitive data (URLs, flags); Secrets hold sensitive data (passwords, keys) — though Secrets are only base64-encoded by default, not encrypted." },
        { front: "Liveness vs readiness probe", back: "Liveness: is the app alive? Failure → restart the container. Readiness: is it ready for traffic? Failure → remove the pod from Service endpoints until healthy. 'Liveness restarts, readiness routes.'" },
        { front: "What does the Horizontal Pod Autoscaler do, and what does it require?", back: "It automatically adds/removes pod replicas based on CPU/memory/custom metrics between a min and max — but only works if containers declare resource requests." },
      ],
      quiz: [
        { q: "A pod is running but temporarily can't serve requests. Which probe should fail to stop traffic without killing it?", options: ["Liveness", "Readiness", "Startup", "None"], answer: 1, explain: "A failing readiness probe removes the pod from Service endpoints (no traffic) without restarting it; liveness would restart the container." },
        { q: "What must be set for the Horizontal Pod Autoscaler to work on CPU?", options: ["A LoadBalancer Service", "Container resource requests", "A StatefulSet", "TLS certificates"], answer: 1, explain: "The HPA computes utilization against the container's CPU request, so requests must be defined for it to scale." },
      ],
    },
  ],
};
