import type { Pattern } from "./types";

export const patterns: Pattern[] = [
  {
    name: "Immutable artifacts",
    tagline: "Build a versioned image once; deploy that exact artifact everywhere.",
    diagram: "image-layers",
    when: "Every containerized workload — the foundation for reproducible deploys and instant rollback.",
    watch: "Never mutate a running server or reuse the `latest` tag; pin an explicit version or digest so two hosts can't drift apart.",
    accent: "teal",
  },
  {
    name: "CI quality gates",
    tagline: "Lint, test, and scan on every change before it can merge.",
    diagram: "pipeline-stages",
    when: "Any repo with a shared main branch — required status checks + review keep main always releasable.",
    watch: "Keep the pipeline fast (<10 min) and gates required, not advisory; a slow or optional gate gets skipped under pressure.",
    accent: "iris",
  },
  {
    name: "Build once, promote",
    tagline: "One immutable image flows through staging to prod — never rebuilt per stage.",
    diagram: "cicd-pipeline",
    when: "Any multi-environment delivery pipeline where you need parity between what you tested and what you ship.",
    watch: "Configuration must be injected per environment (ConfigMaps/Secrets), not baked into the image.",
    accent: "rose",
  },
  {
    name: "Self-healing replicas",
    tagline: "Declare desired replica count; the controller keeps reality matching.",
    diagram: "k8s-objects",
    when: "Stateless services on Kubernetes — a Deployment restarts, reschedules, and rolls out pods automatically.",
    watch: "Set readiness probes correctly or rolling updates will send traffic to pods that aren't ready yet.",
    accent: "amber",
  },
  {
    name: "Service + Ingress edge",
    tagline: "One L7 entry point routes HTTP by host/path to stable Services.",
    diagram: "k8s-networking",
    when: "Exposing many services behind one address with TLS, instead of a cloud load balancer per service.",
    watch: "The ingress controller is a critical path — run it highly available and watch its resource limits.",
    accent: "teal",
  },
  {
    name: "Horizontal autoscaling",
    tagline: "Add and remove pods with demand between a min and max.",
    diagram: "k8s-scaling",
    when: "Stateless tiers with variable traffic — the HPA scales pods and the Cluster Autoscaler scales nodes.",
    watch: "The HPA needs resource requests set; tune min/max and scale-down stabilization to avoid thrashing.",
    accent: "amber",
  },
  {
    name: "Progressive delivery",
    tagline: "Shift a slice of traffic to the new version, watch metrics, then ramp or roll back.",
    diagram: "deployment-strategies",
    when: "High-traffic or high-risk services where a bad deploy must hit as few users as possible.",
    watch: "Requires reliable metrics and traffic shifting; pair with feature flags to separate deploy from release.",
    accent: "rose",
  },
  {
    name: "Shift-left security gates",
    tagline: "Run SAST, SCA, secret and image scans as required checks on every change.",
    diagram: "devsecops-pipeline",
    when: "Any pipeline — catch vulnerabilities in the PR where they're cheapest to fix, not in a pre-release audit.",
    watch: "Fail the build only on high-confidence, high-severity findings; a noisy gate gets muted or routed around.",
    accent: "iris",
  },
  {
    name: "Sign & verify artifacts",
    tagline: "Sign every image in CI and reject anything unsigned at deploy time.",
    diagram: "supply-chain-security",
    when: "Protecting the software supply chain — proving what runs is exactly what your pipeline built, untampered.",
    watch: "Pair signing with an SBOM and image scanning; keyless (OIDC) signing avoids managing long-lived keys.",
    accent: "teal",
  },
  {
    name: "Least privilege by default",
    tagline: "Per-workload ServiceAccounts and default-deny networking shrink the blast radius.",
    diagram: "rbac-model",
    when: "Every cluster — assume any pod can be compromised and limit what it can reach through the API and network.",
    watch: "Never bind cluster-admin 'to make it work'; grant the narrowest RBAC role and NetworkPolicy that functions.",
    accent: "rose",
  },
];
