import type { GlossaryTerm } from "./types";

export const glossary: GlossaryTerm[] = [
  // ── A ──
  { term: "ACM", def: "AWS Certificate Manager — issues free public TLS certificates that auto-renew, usable on CloudFront, ALB, and API Gateway. CloudFront certificates must be issued in us-east-1.", related: ["TLS", "CloudFront"] },
  { term: "ACU", def: "Aurora Capacity Unit — the scaling unit of Aurora Serverless v2, combining CPU, memory, and networking. Capacity adjusts in fine-grained ACU increments in seconds.", related: ["Aurora", "Serverless"] },
  { term: "Alias record", def: "A Route 53 record type pointing at an AWS resource (ALB, CloudFront, S3). Works at the zone apex where CNAMEs can't, follows changing IPs, and is free to query.", related: ["Route 53", "Zone apex"] },
  { term: "ALB", def: "Application Load Balancer — Layer 7 load balancing with routing by path, host, header, and query string, plus WAF, OIDC authentication, and Lambda targets.", related: ["NLB", "Target group"] },
  { term: "AMI", def: "Amazon Machine Image — the disk template an EC2 instance boots from (OS plus preinstalled software). Region-scoped, so parameterise AMI IDs in IaC.", related: ["EC2", "Golden image"] },
  { term: "ARN", def: "Amazon Resource Name — the globally unique identifier for an AWS resource: arn:partition:service:region:account-id:resource. S3 and IAM ARNs omit region/account.", related: ["IAM", "Resource policy"] },
  { term: "ASG", def: "Auto Scaling Group — maintains a target number of healthy EC2 instances across AZs, scaling on policy and replacing failures. Provides both elasticity and self-healing.", related: ["Launch template", "Target tracking"] },
  { term: "Athena", def: "Serverless SQL over data in S3, billed per byte scanned. Converting data to partitioned Parquet typically cuts cost and runtime by over 90%.", related: ["S3", "Parquet", "Glue"] },
  { term: "Aurora", def: "AWS's Postgres/MySQL-compatible database built on a distributed storage layer replicated six ways across three AZs — fast failover, up to 15 low-lag replicas, and Serverless v2.", related: ["RDS", "Multi-AZ"] },
  { term: "Availability", def: "The proportion of time a service is reachable and working (e.g. 99.99% = ~52 minutes of downtime a year). Distinct from durability.", related: ["Durability", "RTO"] },
  { term: "Availability Zone (AZ)", def: "One or more isolated data centers within a Region with independent power, cooling, and networking. Spanning at least two AZs is the highest-value resilience decision on AWS.", related: ["Region", "Multi-AZ"] },
  { term: "AZ ID", def: "The account-independent identifier for a physical Availability Zone (e.g. use1-az4). AZ letters are randomised per account, so AZ IDs are how you compare across accounts.", related: ["Availability Zone (AZ)"] },

  // ── B ──
  { term: "Backpressure", def: "Letting a queue or throttle absorb load so a fast producer doesn't overwhelm a slower consumer — the core reason to put SQS between services.", related: ["SQS", "Decoupling"] },
  { term: "Bastion host", def: "A hardened jump server used to reach instances in private subnets. Largely obsolete — Session Manager provides IAM-controlled, logged access with no inbound ports.", related: ["Session Manager", "Private subnet"] },
  { term: "Block Public Access (BPA)", def: "The account and bucket-level S3 master switch that overrides any bucket policy or ACL granting public access. Keep it on and serve public content via CloudFront + OAC.", related: ["S3", "OAC"] },
  { term: "Block storage", def: "A raw virtual disk (EBS) attached to one instance and formatted with a file system — for boot volumes and databases, as opposed to object storage.", related: ["EBS", "Object storage"] },
  { term: "Blast radius", def: "How much is affected when one thing fails or is compromised. AWS accounts are the strongest blast-radius boundary available.", related: ["AWS account", "Organizations"] },
  { term: "Blue/green deployment", def: "Standing up a complete new environment and switching traffic to it, giving instant rollback at the cost of briefly running double capacity.", related: ["Canary", "CodeDeploy"] },
  { term: "Bucket", def: "The top-level S3 container. Names are globally unique across all AWS accounts and the bucket lives in one region.", related: ["S3", "Object"] },

  // ── C ──
  { term: "Canary deployment", def: "Shifting a small percentage of traffic to a new version, watching metrics, then ramping. ALB weighted target groups provide this with no extra tooling.", related: ["Blue/green deployment", "Target group"] },
  { term: "CDN", def: "Content Delivery Network — caches content at edge locations near users to cut latency, reduce egress cost, and shield the origin. AWS's is CloudFront.", related: ["CloudFront", "Edge location"] },
  { term: "CDC", def: "Change Data Capture — streaming a database's ongoing changes to another system. DMS uses it to keep a migration target in sync until cutover.", related: ["DMS", "DynamoDB Streams"] },
  { term: "CDK", def: "AWS Cloud Development Kit — define infrastructure in TypeScript, Python, Java, or Go; it synthesises CloudFormation templates.", related: ["CloudFormation", "Terraform"] },
  { term: "Cell-based architecture", def: "Partitioning workloads into independent full-stack cells so a failure or bad deploy affects one cell rather than every customer.", related: ["Shuffle sharding", "Blast radius"] },
  { term: "Change set", def: "A CloudFormation preview of exactly what an update will create, modify, or replace. Always read it — some property changes replace a database rather than modifying it.", related: ["CloudFormation", "Drift"] },
  { term: "CIDR block", def: "An IP range in slash notation (10.0.0.0/16). A smaller number after the slash means a larger network. VPC CIDRs cannot be shrunk after creation.", related: ["VPC", "Subnet"] },
  { term: "CloudFormation", def: "AWS's native IaC service. Templates in YAML/JSON deploy as stacks with managed state, rollback, drift detection, and StackSets for multi-account rollout.", related: ["Stack", "StackSet", "CDK"] },
  { term: "CloudFront", def: "AWS's CDN — 600+ edge locations with TLS termination, caching, WAF integration, signed URLs, and edge functions.", related: ["CDN", "OAC", "Cache key"] },
  { term: "CloudTrail", def: "Records AWS API calls — who did what, when, from where. Management events are free for 90 days; data events (object-level) are opt-in and billed.", related: ["AWS Config", "Audit"] },
  { term: "CloudWatch", def: "AWS's telemetry service: metrics, logs, alarms, dashboards. EC2 memory and disk metrics require the CloudWatch agent.", related: ["EMF", "Logs Insights", "Alarm"] },
  { term: "Cold start", def: "The extra latency when Lambda must create and initialise a new execution environment — download code, start the runtime, run init. Warm invocations skip all three.", related: ["Lambda", "Provisioned concurrency"] },
  { term: "Cache key", def: "The combination of URL, headers, cookies, and query strings CloudFront uses to identify a cached object. Forwarding too much makes every request unique and destroys the hit rate.", related: ["CloudFront", "TTL"] },
  { term: "Circuit breaker", def: "Stopping calls to a repeatedly failing dependency so it can recover, instead of amplifying the failure with retries.", related: ["Retry storm", "Backpressure"] },
  { term: "Compute Optimizer", def: "Free AWS service that analyses CloudWatch history and recommends rightsizing for EC2, ASGs, EBS, Lambda, and ECS with projected savings.", related: ["Rightsizing", "Cost Explorer"] },
  { term: "Conformance pack", def: "A bundle of AWS Config rules mapped to a compliance framework (CIS, PCI, NIST), deployable across an organization.", related: ["AWS Config", "CIS Benchmark"] },
  { term: "Control Tower", def: "Automates a governed multi-account landing zone: Organizations, OUs, guardrails, centralised logging, IAM Identity Center, and an account factory.", related: ["Landing zone", "Organizations"] },
  { term: "Correlation ID", def: "An identifier threaded through every log line of a single request so Logs Insights can reconstruct its path across services.", related: ["Logs Insights", "X-Ray"] },
  { term: "Cost allocation tag", def: "A tag activated in the billing console so Cost Explorer and the CUR can group spend by it. Without these, spend can't be attributed to teams.", related: ["Cost Explorer", "CUR", "Tagging"] },
  { term: "Cost Explorer", def: "The free AWS tool for analysing spend by service, account, and tag over time, with rightsizing and Savings Plan recommendations.", related: ["AWS Budgets", "CUR"] },
  { term: "CUR", def: "Cost and Usage Report — the most granular billing export (one row per resource per hour) delivered to S3 and typically queried with Athena.", related: ["Cost Explorer", "FinOps"] },

  // ── D ──
  { term: "DAX", def: "DynamoDB Accelerator — a DynamoDB-native in-memory cache that takes reads from milliseconds to microseconds with no application changes.", related: ["DynamoDB", "ElastiCache"] },
  { term: "Data key", def: "A short-lived key KMS generates to encrypt your actual data locally. The KMS key then encrypts the data key — this is envelope encryption.", related: ["KMS", "Envelope encryption"] },
  { term: "Data event", def: "CloudTrail logging of object-level operations (S3 GetObject, Lambda Invoke, DynamoDB item access). Off by default, billed, and required to answer 'who read this file?'.", related: ["CloudTrail", "Management event"] },
  { term: "DataSync", def: "Managed service for bulk and ongoing transfer between on-prem NFS/SMB/HDFS (or other clouds) and AWS storage, with verification and scheduling.", related: ["Snowball", "Storage Gateway"] },
  { term: "Direct Connect (DX)", def: "A dedicated private circuit between your network and AWS — consistent latency and cheaper egress, but weeks to provision and not redundant by default.", related: ["Site-to-Site VPN", "Transit Gateway"] },
  { term: "DLQ", def: "Dead Letter Queue — where messages or events go after retries are exhausted, so failures are captured rather than silently discarded.", related: ["SQS", "Lambda"] },
  { term: "DMS", def: "Database Migration Service — full load plus CDC replication between databases, with the Schema Conversion Tool for engine changes.", related: ["CDC", "Migration"] },
  { term: "Drift", def: "Live infrastructure no longer matching the IaC that defines it, usually caused by manual console changes. Detected by terraform plan or CloudFormation drift detection.", related: ["CloudFormation", "Terraform"] },
  { term: "Durability", def: "The probability stored data still exists. S3 Standard is designed for eleven nines (99.999999999%) across at least three AZs. Not the same as backup.", related: ["Availability", "S3"] },
  { term: "DynamoDB", def: "Serverless key-value and document database with single-digit-millisecond latency at any scale. You design the table around known access patterns.", related: ["Partition key", "GSI", "DAX"] },
  { term: "DynamoDB Streams", def: "An ordered change log of every item modification, typically consumed by Lambda — the backbone of event-driven patterns and materialised views.", related: ["DynamoDB", "EventBridge"] },

  // ── E ──
  { term: "EBS", def: "Elastic Block Store — network-attached virtual disks scoped to one AZ. gp3 is the sensible default; io2 Block Express for guaranteed high IOPS.", related: ["Block storage", "Snapshot"] },
  { term: "EC2", def: "Elastic Compute Cloud — AWS virtual machines, billed per second, with full control of the OS and everything above it.", related: ["AMI", "ASG", "Instance profile"] },
  { term: "ECR", def: "Elastic Container Registry — managed private Docker registry with IAM auth, vulnerability scanning, lifecycle policies, replication, and a pull-through cache.", related: ["ECS", "Container"] },
  { term: "ECS", def: "Elastic Container Service — AWS's native container orchestrator using task definitions, tasks, services, and clusters. No control-plane fee.", related: ["Fargate", "EKS", "Task role"] },
  { term: "EFS", def: "Elastic File System — elastic multi-AZ NFS that thousands of instances, containers, and Lambda functions can mount concurrently.", related: ["FSx", "S3"] },
  { term: "Edge location", def: "One of 600+ small points of presence outside full Regions, used by CloudFront and Route 53 to serve users with low latency.", related: ["CDN", "Region"] },
  { term: "Egress", def: "Data leaving AWS toward the internet, which is billed per GB. Inbound is free; cross-AZ and cross-region transfer are also charged.", related: ["NAT gateway", "CloudFront"] },
  { term: "EKS", def: "Elastic Kubernetes Service — a managed upstream Kubernetes control plane (~$73/month per cluster) with node groups, Fargate profiles, or Karpenter for capacity.", related: ["IRSA", "Karpenter", "ECS"] },
  { term: "ElastiCache", def: "Managed Redis/Valkey or Memcached for caching, sessions, leaderboards, rate limiting, and pub/sub.", related: ["Cache-aside", "DAX"] },
  { term: "Elastic IP (EIP)", def: "A static public IPv4 address you own. Billed when not attached to a running instance, and IPv4 addresses now carry an hourly charge generally.", related: ["EC2", "NAT gateway"] },
  { term: "EMF", def: "Embedded Metric Format — emitting CloudWatch metrics inside structured log lines, avoiding per-datapoint PutMetricData cost while keeping full log context.", related: ["CloudWatch", "Powertools"] },
  { term: "ENI", def: "Elastic Network Interface — the virtual NIC that carries a private IP and the security groups. In awsvpc mode each ECS task gets its own.", related: ["Security group", "awsvpc"] },
  { term: "Envelope encryption", def: "Encrypting data with a locally generated data key, then encrypting that data key with a KMS key — fast bulk crypto with centrally controlled, audited keys.", related: ["KMS", "Data key"] },
  { term: "EventBridge", def: "Serverless event bus routing events by content to many targets, with AWS/SaaS integrations, schema registry, archive and replay, Scheduler, and Pipes.", related: ["SNS", "SQS", "Fan-out"] },
  { term: "Execution role", def: "In ECS, the role the agent uses to pull images from ECR, read secrets, and ship logs — distinct from the task role your application code uses.", related: ["Task role", "ECS"] },
  { term: "Expand/contract", def: "A two-phase schema migration: deploy a backwards-compatible change, then the code using it, then remove the old path later — so each deploy can roll back.", related: ["CI/CD", "RDS"] },

  // ── F ──
  { term: "Fan-out", def: "Publishing one message that reaches many independent consumers — typically SNS or EventBridge feeding multiple SQS queues or Lambdas.", related: ["SNS", "EventBridge"] },
  { term: "Fargate", def: "Serverless compute for ECS and EKS: you declare CPU and memory per task and AWS supplies the host. Roughly a 20–30% premium over EC2 with no node management.", related: ["ECS", "EKS"] },
  { term: "FinOps", def: "The practice of managing cloud spend collaboratively across engineering, finance, and product — informing, optimising, and operating on unit economics.", related: ["Cost Explorer", "Savings Plan"] },
  { term: "FIS", def: "AWS Fault Injection Service — deliberately injects failures (terminating instances, adding latency, simulating AZ loss) to test resilience and runbooks.", related: ["Game day", "Resilience"] },
  { term: "FSx", def: "Managed purpose-built file systems: Windows File Server (SMB/AD), Lustre (HPC/ML), NetApp ONTAP, and OpenZFS.", related: ["EFS", "File storage"] },

  // ── G ──
  { term: "Game day", def: "A planned exercise deliberately failing components in a controlled window to validate recovery, alarms, and runbooks.", related: ["FIS", "DR"] },
  { term: "Gateway endpoint", def: "A free VPC endpoint for S3 and DynamoDB implemented as a route table entry. Adding one removes NAT gateway data-processing charges for that traffic.", related: ["Interface endpoint", "NAT gateway"] },
  { term: "Global Accelerator", def: "Static anycast IPs that pull traffic onto the AWS backbone at the nearest edge and fail over between regional endpoints in seconds. Optimises connections, not content.", related: ["CloudFront", "Route 53"] },
  { term: "Glue", def: "Serverless ETL plus a data catalog of schemas, used to catalogue and transform data-lake data for Athena and Redshift.", related: ["Athena", "S3"] },
  { term: "Golden image", def: "A pre-baked, hardened AMI with agents and dependencies installed, so instances boot fast and identically. Built by EC2 Image Builder or Packer.", related: ["AMI", "Instance refresh"] },
  { term: "Graviton", def: "AWS's ARM-based processors, typically ~20% better price-performance than equivalent x86 instances. Usually a drop-in change for interpreted or multi-arch workloads.", related: ["EC2", "Rightsizing"] },
  { term: "GSI", def: "Global Secondary Index — a DynamoDB index with any attributes as its keys, addable at any time, eventually consistent, with its own capacity.", related: ["LSI", "DynamoDB"] },
  { term: "GuardDuty", def: "Threat detection analysing CloudTrail, VPC Flow Logs, DNS logs, EKS audit logs, and S3 data events for mining, C2 traffic, and credential misuse. No agents.", related: ["Security Hub", "Detective"] },
  { term: "Guardrail", def: "A preventive (SCP) or detective (Config rule) control applied broadly so teams can move quickly without creating risk.", related: ["SCP", "AWS Config"] },

  // ── H ──
  { term: "Health check", def: "A probe determining whether a target should receive traffic. ELB health checks test the application; EC2 status checks only test the instance.", related: ["Target group", "ASG"] },
  { term: "Hosted zone", def: "A Route 53 container of DNS records for a domain. Public zones answer the internet; private zones answer only inside associated VPCs.", related: ["Route 53", "Alias record"] },
  { term: "Hot partition", def: "A DynamoDB partition receiving disproportionate traffic because of a low-cardinality key, causing throttling while overall utilisation looks low.", related: ["Partition key", "Write sharding"] },

  // ── I ──
  { term: "IAM", def: "Identity and Access Management — the global, free service authorising every AWS API call via users, groups, roles, and policies.", related: ["Role", "Policy", "STS"] },
  { term: "IAM Identity Center", def: "Formerly AWS SSO — one login portal across every account, federated to your IdP, issuing short-lived credentials via permission sets.", related: ["Permission set", "Federation"] },
  { term: "Idempotency", def: "Handling the same request twice producing the same result. Mandatory on AWS because SQS, SNS, EventBridge, and Lambda all deliver at least once.", related: ["SQS", "Lambda"] },
  { term: "IGW", def: "Internet Gateway — one per VPC, free, enabling two-way internet traffic for resources with public IPs. A subnet is 'public' because it routes 0.0.0.0/0 here.", related: ["NAT gateway", "Public subnet"] },
  { term: "IMDS", def: "Instance Metadata Service — the link-local endpoint (169.254.169.254) where an instance reads its own identity and role credentials. Always enforce IMDSv2.", related: ["Instance profile", "SSRF"] },
  { term: "Instance profile", def: "The wrapper that attaches an IAM role to an EC2 instance, delivering temporary auto-rotating credentials via IMDS — so no keys are stored on disk.", related: ["IAM", "IMDS"] },
  { term: "Instance store", def: "NVMe SSD physically attached to the host: extremely fast, free, and permanently lost on stop, terminate, or host failure. Scratch space only.", related: ["EBS", "EC2"] },
  { term: "Intelligent-Tiering", def: "An S3 storage class that automatically moves objects between access tiers based on usage — the low-risk default for large buckets with unpredictable access.", related: ["S3", "Lifecycle rule"] },
  { term: "Interface endpoint", def: "A PrivateLink VPC endpoint — an ENI in your subnet giving private access to most AWS services, or to services others publish. Billed hourly plus per GB.", related: ["Gateway endpoint", "PrivateLink"] },
  { term: "IRSA", def: "IAM Roles for Service Accounts — mapping a Kubernetes ServiceAccount to an IAM role via OIDC so each EKS pod has its own AWS permissions.", related: ["EKS", "OIDC"] },

  // ── K ──
  { term: "Karpenter", def: "An AWS-built Kubernetes autoscaler that provisions right-sized nodes directly from pending pods (including Spot), generally beating the Cluster Autoscaler on cost and speed.", related: ["EKS", "Spot"] },
  { term: "Key policy", def: "The resource policy on a KMS key. It is authoritative — IAM permissions alone cannot grant key access, which is why 'S3 AccessDenied' is often a KMS problem.", related: ["KMS", "Resource policy"] },
  { term: "KMS", def: "Key Management Service — stores keys in HSMs, never releasing key material. Every use is logged in CloudTrail; supports rotation, grants, and multi-region keys.", related: ["Envelope encryption", "Key policy"] },

  // ── L ──
  { term: "Lambda", def: "Serverless functions billed per millisecond and GB of memory, with a 15-minute maximum. Memory scales CPU proportionally, so more memory is often faster and no more expensive.", related: ["Cold start", "Concurrency"] },
  { term: "Landing zone", def: "A pre-governed multi-account AWS environment — OUs, SCP guardrails, identity, networking, and centralised logging — that applications land in.", related: ["Control Tower", "Organizations"] },
  { term: "Launch template", def: "The versioned blueprint an ASG uses to create instances (AMI, type, security groups, IAM profile, user data). Replaces the older launch configurations.", related: ["ASG", "Instance refresh"] },
  { term: "Least privilege", def: "Granting only the permissions actually needed. Achieved iteratively via CloudTrail history and IAM Access Analyzer, not designed perfectly up front.", related: ["IAM", "Access Analyzer"] },
  { term: "Lifecycle rule", def: "An S3 policy that transitions objects between storage classes or expires them by age — the main lever on storage cost. Also aborts incomplete multipart uploads.", related: ["S3", "Intelligent-Tiering"] },
  { term: "Logs Insights", def: "CloudWatch's query language over log groups, priced per GB scanned. Structured JSON logs with a correlation ID make it precise instead of hopeful.", related: ["CloudWatch", "Correlation ID"] },
  { term: "LSI", def: "Local Secondary Index — a DynamoDB index sharing the partition key with a different sort key. Creation-time only, strongly consistent, and caps item collections at 10 GB.", related: ["GSI", "DynamoDB"] },

  // ── M ──
  { term: "Macie", def: "Discovers and classifies sensitive data (PII, credentials) in S3 buckets and reports whether it's exposed.", related: ["S3", "GuardDuty"] },
  { term: "Management event", def: "A CloudTrail record of a control-plane API call (create, modify, delete). Free for 90 days in Event History; create a trail for longer retention.", related: ["CloudTrail", "Data event"] },
  { term: "MGN", def: "AWS Application Migration Service — block-level replication of existing servers into AWS, enabling test cutovers before the real rehost.", related: ["Migration", "7 Rs"] },
  { term: "Multi-AZ", def: "An RDS/Aurora deployment with a synchronous standby in another AZ and automatic failover. For availability — not a backup and, in classic form, not readable.", related: ["Read replica", "Availability Zone (AZ)"] },
  { term: "Multipart upload", def: "Splitting one S3 upload into parallel parts — recommended above ~100 MB and required above 5 GB. Incomplete ones bill invisibly without a lifecycle rule.", related: ["S3", "Lifecycle rule"] },

  // ── N ──
  { term: "NACL", def: "Network Access Control List — a stateless, numbered, subnet-level filter supporting explicit deny. Return traffic needs its own outbound rule for ephemeral ports.", related: ["Security group", "Subnet"] },
  { term: "NAT gateway", def: "Gives private subnets outbound-only internet access. Zonal, and billed hourly plus per GB processed — one of the most common surprise costs on AWS.", related: ["IGW", "Gateway endpoint"] },
  { term: "NLB", def: "Network Load Balancer — Layer 4 (TCP/UDP) with static Elastic IPs, source-IP preservation, extreme throughput, and ultra-low latency.", related: ["ALB", "Target group"] },

  // ── O ──
  { term: "OAC", def: "Origin Access Control — the modern mechanism letting only CloudFront read a private S3 bucket, so public buckets are never needed for websites.", related: ["CloudFront", "Block Public Access (BPA)"] },
  { term: "Object", def: "A file plus metadata stored in S3, addressed by a key inside a bucket. Objects are replaced whole, not appended to.", related: ["S3", "Bucket"] },
  { term: "Object Lock", def: "S3 WORM retention making objects immutable for a period. Governance mode allows privileged override; compliance mode allows none — the anti-ransomware control.", related: ["S3", "Versioning"] },
  { term: "OIDC federation", def: "Trusting an external OpenID Connect issuer (GitHub Actions, an EKS cluster) so it can assume an AWS role with no stored credentials. Always pin the sub claim.", related: ["STS", "IRSA"] },
  { term: "OLTP / OLAP", def: "Online Transaction Processing (many small reads/writes — RDS, DynamoDB) versus Online Analytical Processing (large aggregations — Redshift, Athena).", related: ["RDS", "Redshift"] },
  { term: "Organizations", def: "AWS's multi-account service: a management account, OUs, Service Control Policies, and consolidated billing across every member account.", related: ["SCP", "Landing zone"] },
  { term: "OU", def: "Organizational Unit — a folder grouping AWS accounts so policies such as SCPs apply to a whole class of accounts at once.", related: ["Organizations", "SCP"] },

  // ── P ──
  { term: "Parameter Store", def: "Systems Manager's hierarchical store for configuration and SecureString secrets. Standard parameters are free — the budget alternative to Secrets Manager.", related: ["Secrets Manager", "Systems Manager"] },
  { term: "Parquet", def: "A compressed columnar file format. Converting lake data to partitioned Parquet typically cuts Athena cost and runtime by over 90%.", related: ["Athena", "S3"] },
  { term: "Partition key", def: "The DynamoDB attribute hashed to choose a physical partition. Its cardinality determines whether load spreads evenly or creates a hot partition.", related: ["Sort key", "Hot partition"] },
  { term: "PassRole", def: "The IAM permission to hand a role to an AWS service. A classic privilege-escalation path — always constrain it by role ARN and iam:PassedToService.", related: ["IAM", "Least privilege"] },
  { term: "Permission boundary", def: "A policy capping what an IAM user or role can do without granting anything. Lets developers create roles safely, since those roles can't exceed the boundary.", related: ["SCP", "IAM"] },
  { term: "Permission set", def: "An IAM Identity Center bundle of policies assigned to groups and provisioned as an IAM role in each assigned account.", related: ["IAM Identity Center", "Federation"] },
  { term: "Pilot light", def: "A DR strategy where data replicates continuously to another region but compute is switched off — recovery means scaling up, not rebuilding.", related: ["Warm standby", "RTO"] },
  { term: "PITR", def: "Point-In-Time Recovery — restoring RDS or DynamoDB to any second within the retention window (up to 35 days). Restores create a new instance/table.", related: ["Snapshot", "RPO"] },
  { term: "PrivateLink", def: "Private connectivity to AWS services or to services others publish behind an NLB, with no peering, route sharing, or CIDR coordination.", related: ["Interface endpoint", "VPC peering"] },
  { term: "Private subnet", def: "A subnet whose default route goes to a NAT gateway (or nowhere), so its resources aren't directly reachable from the internet.", related: ["Public subnet", "NAT gateway"] },
  { term: "Provisioned concurrency", def: "Pre-initialised Lambda execution environments that eliminate cold starts for latency-critical paths, billed even while idle.", related: ["Cold start", "Reserved concurrency"] },
  { term: "Public subnet", def: "A subnet whose route table sends 0.0.0.0/0 to an Internet Gateway. There is no 'public' checkbox — routing is what defines it.", related: ["IGW", "Private subnet"] },

  // ── R ──
  { term: "RDS", def: "Relational Database Service — managed Postgres, MySQL, MariaDB, Oracle, SQL Server, and Db2 with automated backups, patching, and Multi-AZ failover.", related: ["Aurora", "Multi-AZ", "RDS Proxy"] },
  { term: "RDS Proxy", def: "A managed connection pool in front of RDS/Aurora that multiplexes many short-lived clients (especially Lambda) and survives failovers transparently.", related: ["RDS", "Lambda"] },
  { term: "Read replica", def: "An asynchronous read-only copy of a database used to scale reads or for cross-region DR. Promoted manually — distinct from a Multi-AZ standby.", related: ["Multi-AZ", "Aurora"] },
  { term: "Redshift", def: "Columnar MPP data warehouse for analytical queries over huge datasets, with Serverless, Spectrum (query S3 directly), and zero-ETL integrations.", related: ["Athena", "OLTP / OLAP"] },
  { term: "Region", def: "A geographic area containing multiple Availability Zones. Regions are isolated by design — nothing crosses between them unless you configure it.", related: ["Availability Zone (AZ)", "Edge location"] },
  { term: "Reserved concurrency", def: "A Lambda setting that both guarantees and caps concurrent executions, and removes those slots from the shared account pool. Setting it to 0 disables the function.", related: ["Lambda", "Provisioned concurrency"] },
  { term: "Resource policy", def: "A policy attached to a resource (bucket, queue, KMS key, role trust policy) stating which principals may act on it. Cross-account access needs one on both sides.", related: ["IAM", "Key policy"] },
  { term: "Retry storm", def: "A self-inflicted outage where naive retries multiply load on a struggling dependency. Prevented by exponential backoff with jitter, attempt caps, and circuit breakers.", related: ["Circuit breaker", "Backpressure"] },
  { term: "Rightsizing", def: "Matching instance and volume sizes to real utilisation. Do this before buying Savings Plans, or you commit to waste for one to three years.", related: ["Compute Optimizer", "Savings Plan"] },
  { term: "Role", def: "An IAM identity with permissions but no long-lived credentials, assumed temporarily via STS. The default identity mechanism in modern AWS.", related: ["STS", "Trust policy"] },
  { term: "Route 53", def: "AWS's DNS and domain registrar, with alias records, health checks, and six routing policies including weighted, latency, failover, and geolocation.", related: ["Alias record", "Hosted zone"] },
  { term: "Route table", def: "The rules mapping destination CIDRs to targets (IGW, NAT, TGW, endpoint). Longest prefix wins, and the local VPC route always exists.", related: ["Subnet", "IGW"] },
  { term: "RPO", def: "Recovery Point Objective — how much data you can afford to lose, expressed in time. Drives backup and replication frequency.", related: ["RTO", "PITR"] },
  { term: "RTO", def: "Recovery Time Objective — how long you can be down. Drives DR strategy, standby capacity, and failover automation.", related: ["RPO", "Pilot light"] },

  // ── S ──
  { term: "S3", def: "Simple Storage Service — object storage with eleven nines of durability, strong read-after-write consistency, seven storage classes, and lifecycle automation.", related: ["Bucket", "Object", "Lifecycle rule"] },
  { term: "SAM", def: "Serverless Application Model — a CloudFormation extension with concise resource types for Lambda, API Gateway, and DynamoDB, plus a local testing CLI.", related: ["CloudFormation", "Lambda"] },
  { term: "Savings Plan", def: "A commitment to a dollar-per-hour of compute spend for one or three years for up to ~72% off. Compute Savings Plans flex across EC2, Fargate, and Lambda.", related: ["Reserved Instance", "Spot"] },
  { term: "SCP", def: "Service Control Policy — an Organizations guardrail capping the maximum permissions any principal in an account can have. Never grants; only limits.", related: ["Organizations", "Permission boundary"] },
  { term: "Secrets Manager", def: "Stores secrets encrypted with KMS, with automatic rotation (native for RDS), resource policies, and multi-region replication.", related: ["Parameter Store", "KMS"] },
  { term: "Security group", def: "A stateful, allow-only virtual firewall attached to an ENI. Can reference other security groups as sources, so rules survive autoscaling.", related: ["NACL", "ENI"] },
  { term: "Security Hub", def: "Aggregates findings from GuardDuty, Inspector, Macie, Config, and partners into one prioritised view, with automated scoring against CIS and AWS FSBP.", related: ["GuardDuty", "CIS Benchmark"] },
  { term: "Serverless", def: "A model where you never provision or patch servers and pay only while code runs. Lambda, Fargate, DynamoDB on-demand, S3, and API Gateway all qualify.", related: ["Lambda", "Fargate"] },
  { term: "Service quota", def: "A per-account, per-region cap on a resource or rate. Many are raisable via a request — check quotas before a launch or load test, not during.", related: ["Trusted Advisor"] },
  { term: "Session Manager", def: "Systems Manager's IAM-authorised, fully logged shell into an instance through the SSM agent — no SSH keys, bastions, or inbound ports.", related: ["Systems Manager", "Bastion host"] },
  { term: "Shared responsibility model", def: "AWS secures the cloud (facilities, hardware, service internals); you secure what's in it (data, IAM, network config, and OS patching on EC2).", related: ["IAM", "Compliance"] },
  { term: "Shield", def: "DDoS protection: Standard is automatic and free at the edge; Advanced adds a response team, cost protection, and deeper mitigations for a subscription fee.", related: ["WAF", "CloudFront"] },
  { term: "Shuffle sharding", def: "Assigning each customer a random subset of resources so any single failure affects only a small, mostly non-overlapping group.", related: ["Cell-based architecture"] },
  { term: "Site-to-Site VPN", def: "IPsec tunnels between your network and AWS over the internet — live in under an hour, with variable latency. Often the backup path for Direct Connect.", related: ["Direct Connect (DX)", "Transit Gateway"] },
  { term: "Snapshot", def: "An incremental point-in-time backup of an EBS volume stored in S3 by AWS. Region-scoped and copyable; needs a lifecycle policy or it accumulates cost.", related: ["EBS", "AWS Backup"] },
  { term: "Snowball", def: "A physical device shipped to you for transferring large data volumes — usually faster than the network above roughly 50–100 TB on an ordinary link.", related: ["DataSync", "Migration"] },
  { term: "SNS", def: "Simple Notification Service — a push topic delivering each message to all subscribers (SQS, Lambda, HTTP, email, SMS), with attribute-based filter policies.", related: ["SQS", "EventBridge", "Fan-out"] },
  { term: "Sort key", def: "The optional second part of a DynamoDB primary key. Items sharing a partition key are stored together and ordered by sort key, enabling range queries.", related: ["Partition key", "DynamoDB"] },
  { term: "Spot", def: "Spare EC2 capacity at up to ~90% off, reclaimed with a two-minute notice. Ideal for batch, CI, and stateless fleets when pools are diversified.", related: ["Savings Plan", "AWS Batch"] },
  { term: "SQS", def: "Simple Queue Service — a pull-based queue that buffers work, retries failures, and moves poison messages to a DLQ. Standard is at-least-once; FIFO adds ordering.", related: ["DLQ", "Visibility timeout"] },
  { term: "Stack", def: "A deployed instance of a CloudFormation template. Deleting the stack deletes its resources unless a deletion policy retains them.", related: ["CloudFormation", "StackSet"] },
  { term: "StackSet", def: "CloudFormation deploying one stack across many accounts and regions from the management account — the standard way to roll out org-wide baselines.", related: ["Stack", "Organizations"] },
  { term: "Step Functions", def: "A managed state machine service orchestrating steps with declarative retries, catches, parallelism, and visible execution history. Standard and Express workflows.", related: ["Lambda", "Saga"] },
  { term: "Storage class", def: "The S3 tier an object sits in — Standard, Intelligent-Tiering, Standard-IA, One Zone-IA, and three Glacier tiers — trading storage price against retrieval cost and speed.", related: ["S3", "Lifecycle rule"] },
  { term: "STS", def: "Security Token Service — issues temporary credentials (keys starting ASIA) via AssumeRole, AssumeRoleWithWebIdentity, or SAML.", related: ["Role", "OIDC federation"] },
  { term: "Subnet", def: "A CIDR slice of a VPC bound to exactly one Availability Zone. AWS reserves 5 IPs in each, so a /28 gives 11 usable addresses.", related: ["VPC", "Route table"] },
  { term: "Systems Manager (SSM)", def: "A toolbox for fleet operations: Session Manager, Run Command, Patch Manager, Parameter Store, Automation runbooks, Inventory, and AppConfig.", related: ["Session Manager", "Parameter Store"] },

  // ── T ──
  { term: "Tagging", def: "Key-value labels on resources. Essential for cost attribution, access control (ABAC), automation targeting, and ownership — and painful to add retroactively.", related: ["Cost allocation tag", "ABAC"] },
  { term: "Target group", def: "A set of load-balancer backends (instances, IPs, Lambdas) plus their health-check configuration. Shifting traffic between target groups is how canaries work.", related: ["ALB", "Health check"] },
  { term: "Target tracking", def: "The default ASG scaling policy: hold a metric at a target value (CPU 50%, or requests per target). Simpler and better behaved than step scaling.", related: ["ASG", "Autoscaling"] },
  { term: "Task definition", def: "The versioned ECS blueprint specifying images, CPU/memory, environment, secrets, IAM roles, logging, and health checks.", related: ["ECS", "Task role"] },
  { term: "Task role", def: "The IAM role an ECS container's application code uses to call AWS APIs — distinct from the execution role used by the agent.", related: ["Execution role", "ECS"] },
  { term: "Terraform", def: "HashiCorp's multi-cloud IaC tool using HCL, with a state file you must store remotely, encrypt, and lock. The most requested tool in cloud engineering roles.", related: ["CloudFormation", "Drift"] },
  { term: "Transit Gateway (TGW)", def: "A regional router that VPCs, VPNs, and Direct Connect attach to, providing transitive routing plus per-attachment route tables for segmentation.", related: ["VPC peering", "Direct Connect (DX)"] },
  { term: "Trust policy", def: "The resource policy on an IAM role defining which principals may assume it. Can require an ExternalId, MFA, or a pinned OIDC sub claim.", related: ["Role", "STS"] },
  { term: "Trusted Advisor", def: "Checks an account across cost, security, fault tolerance, performance, and service limits. The full check set requires Business support or above.", related: ["Service quota", "Cost Explorer"] },
  { term: "TTL", def: "Time To Live — how long a DNS answer or cache entry stays valid, or (in DynamoDB) an attribute triggering free automatic item deletion.", related: ["Route 53", "DynamoDB"] },

  // ── U–W ──
  { term: "User data", def: "A script that runs on an EC2 instance's first boot for bootstrapping. Its output lands in /var/log/cloud-init-output.log.", related: ["EC2", "Launch template"] },
  { term: "Versioning", def: "An S3 setting keeping every version of an object, so deletes create a delete marker rather than destroying data. Pair with a lifecycle rule for noncurrent versions.", related: ["S3", "Object Lock"] },
  { term: "Visibility timeout", def: "How long an SQS message stays hidden after being received. Set it below your processing time and messages get processed twice — the classic SQS bug.", related: ["SQS", "Idempotency"] },
  { term: "VPC", def: "Virtual Private Cloud — your isolated network in a region, with your own CIDR, subnets, routing, and firewalls. Almost every AWS resource lives in one.", related: ["Subnet", "Route table"] },
  { term: "VPC Flow Logs", def: "Records of accepted and rejected traffic per ENI. A REJECT means a security group or NACL dropped the packet; no entry at all usually means routing never delivered it.", related: ["Security group", "NACL"] },
  { term: "VPC peering", def: "A private one-to-one link between two VPCs. Non-transitive and impossible with overlapping CIDRs — beyond a handful of VPCs, use Transit Gateway.", related: ["Transit Gateway (TGW)", "PrivateLink"] },
  { term: "WAF", def: "Web Application Firewall — L7 filtering on CloudFront, ALB, and API Gateway with managed rule groups and rate-based rules. Deploy in count mode first.", related: ["Shield", "CloudFront"] },
  { term: "Warm standby", def: "A DR strategy running a scaled-down but live copy of production in another region, scaled up and cut over in minutes.", related: ["Pilot light", "RTO"] },
  { term: "Well-Architected Framework", def: "AWS's six-pillar review framework: Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, and Sustainability.", related: ["Guardrail", "FinOps"] },
  { term: "Write sharding", def: "Adding a random or calculated suffix to a DynamoDB partition key to spread writes across partitions and avoid a hot partition.", related: ["Hot partition", "Partition key"] },

  // ── extras ──
  { term: "ABAC", def: "Attribute-Based Access Control — granting access by matching principal tags to resource tags, so one policy covers every team instead of one policy per team.", related: ["IAM", "Tagging"] },
  { term: "Access Analyzer", def: "IAM feature reporting resources reachable from outside your account or organization, unused permissions, policy validation, and CloudTrail-based policy generation.", related: ["IAM", "Least privilege"] },
  { term: "AWS account", def: "An isolated container with its own resources, IAM, quotas, and bill — the strongest blast-radius boundary AWS offers.", related: ["Organizations", "Blast radius"] },
  { term: "AWS Backup", def: "Centralised backup policy across EBS, EFS, RDS, DynamoDB, FSx, EC2, and S3, applied by tag, with vault lock, cross-account copy, and restore testing.", related: ["Snapshot", "RPO"] },
  { term: "AWS Batch", def: "Managed batch computing — queues jobs and provisions compute environments (usually Spot) to run containerised work at scale.", related: ["Spot", "ECS"] },
  { term: "AWS Budgets", def: "Alerts when spend, usage, or Savings Plan coverage crosses a threshold, including forecast-based alerts.", related: ["Cost Explorer", "FinOps"] },
  { term: "AWS Config", def: "Records resource configuration state over time, evaluates it against rules, and can auto-remediate. CloudTrail records actions; Config records state.", related: ["CloudTrail", "Conformance pack"] },
  { term: "Cache-aside", def: "The standard caching pattern: check the cache, and on a miss read the database and store the result with a TTL.", related: ["ElastiCache", "TTL"] },
  { term: "CIS Benchmark", def: "The CIS AWS Foundations Benchmark — concrete account-hardening controls (root MFA, CloudTrail on, no open SSH, encryption) available as a Security Hub standard.", related: ["Security Hub", "Compliance"] },
  { term: "Detective", def: "Builds investigation graphs from CloudTrail, Flow Logs, and GuardDuty findings to answer 'what else did this principal do?'.", related: ["GuardDuty", "Security Hub"] },
  { term: "Inspector", def: "Continuously scans EC2, ECR images, and Lambda functions for software vulnerabilities and network reachability.", related: ["ECR", "Security Hub"] },
  { term: "Saga", def: "A distributed-transaction pattern using compensating actions (refund the payment if shipping fails) instead of rollback — commonly implemented in Step Functions.", related: ["Step Functions", "Idempotency"] },
  { term: "SSRF", def: "Server-Side Request Forgery — tricking a server into making requests on an attacker's behalf, historically used to steal role credentials from IMDSv1.", related: ["IMDS", "Security group"] },
  { term: "7 Rs", def: "The migration dispositions: Retire, Retain, Rehost, Relocate, Replatform, Repurchase, Refactor. Most estates are mostly the first five.", related: ["Migration", "MGN"] },
];
