import type { Module } from "./types";

export const architecture: Module = {
  id: "architecture",
  title: "Architecture, resilience & migration",
  blurb:
    "The reference architectures you'll be asked to draw, RTO/RPO and the four DR strategies, multi-region reality, and how enterprises actually move to AWS.",
  accent: "iris",
  lessons: [
    {
      slug: "reference-architectures",
      title: "The reference architectures you'll be asked to draw",
      summary:
        "The three-tier web app, the event-driven pipeline, and the decoupled worker pattern — plus the design principles underneath all of them.",
      minutes: 11,
      blocks: [
        { type: "p", text: "Most AWS system-design conversations converge on a handful of shapes. Knowing them cold — including the trade-offs and failure modes — is what makes a whiteboard exercise straightforward instead of stressful." },
        { type: "h2", text: "1. The three-tier web application" },
        { type: "diagram", name: "three-tier-reference", caption: "Public edge, private compute, private data — replicated across two AZs." },
        { type: "list", items: [
          "**Route 53** alias → **CloudFront** (with WAF and ACM TLS) → **ALB** in public subnets.",
          "**Application tier** — ECS/Fargate tasks or an EC2 Auto Scaling Group in **private** subnets across two or three AZs.",
          "**Data tier** — RDS/Aurora Multi-AZ in isolated subnets, plus ElastiCache for sessions and hot reads.",
          "**S3** for static assets and uploads, reached via a gateway endpoint; **Secrets Manager** for credentials.",
          "**CloudWatch + X-Ray** for telemetry, **CloudTrail + Config** for audit.",
        ]},
        { type: "callout", kind: "key", text: "When asked to design 'a scalable web application on AWS', this is the answer, and the marks are in the details: **why two AZs, why the app tier is private, why sessions aren't on the instance, what happens when an AZ fails, and what it costs.**" },
        { type: "h2", text: "2. The event-driven pipeline" },
        { type: "diagram", name: "event-driven-fanout", caption: "A producer publishes once; independent consumers react without knowing about each other." },
        { type: "p", text: "**S3 or an application publishes an event → EventBridge (or SNS) → multiple SQS queues → Lambda or Fargate consumers → DynamoDB/S3 results.** Each consumer has its own retry policy, DLQ, and scaling profile. Adding a new consumer is a new rule, not a change to the producer — which is the entire point." },
        { type: "h2", text: "3. Queue-based decoupling for slow work" },
        { type: "diagram", name: "queue-decoupling", caption: "The API accepts fast; workers process at their own pace." },
        { type: "p", text: "An API returns `202 Accepted` with a job ID, puts a message on **SQS**, and a worker fleet (Lambda, Fargate, or an ASG scaled on `ApproximateAgeOfOldestMessage`) processes it. The client polls or receives a webhook. This turns a fragile synchronous chain into a resilient one and is the standard answer for anything slow: video encoding, report generation, third-party API calls." },
        { type: "h2", text: "The principles underneath" },
        { type: "compare", caption: "What actually makes these designs work.", columns: ["Principle", "Why it matters"], rows: [
          { label: "Statelessness", cells: ["Any instance can die at any moment — sessions and files must live in shared services"] },
          { label: "Loose coupling", cells: ["A queue or event bus turns a dependency's outage into a delay instead of an outage"] },
          { label: "Idempotency", cells: ["Retries are guaranteed, so processing twice must be safe"] },
          { label: "Graceful degradation", cells: ["Serve stale cache or a reduced feature set rather than a 500"] },
          { label: "Backpressure", cells: ["Queues and throttling protect a slow downstream from a fast upstream"] },
          { label: "Timeouts and retries with backoff and jitter", cells: ["Naive retries turn a blip into a self-inflicted DDoS"] },
          { label: "Circuit breakers", cells: ["Stop calling a failing dependency so it can recover"] },
        ]},
        { type: "callout", kind: "warn", text: "**The retry storm is the most common self-inflicted outage.** A downstream slows, every client retries three times, load triples, it fails completely, and retries continue. Always use exponential backoff **with jitter**, cap total attempts, and add a circuit breaker. AWS SDKs do adaptive retries by default — don't wrap your own naive loop around them." },
        { type: "h2", text: "How to answer a design question" },
        { type: "steps", items: [
          { title: "Clarify requirements first", text: "Traffic volume and shape, latency target, consistency needs, RTO/RPO, compliance, and budget. Designing before asking is the most common interview mistake." },
          { title: "Start simple and correct", text: "Draw the smallest thing that meets the requirements. Multi-region active-active as an opening move signals inexperience, not seniority." },
          { title: "Add resilience", text: "Multi-AZ, health checks, retries, and what happens when each component fails." },
          { title: "Add scale where the numbers demand it", text: "Caching, read replicas, autoscaling, async processing — justified by the traffic figures you asked for." },
          { title: "Name the trade-offs and the cost", text: "\"This is roughly $X/month; we could halve it by Y at the cost of Z.\" That sentence is what distinguishes a senior answer." },
          { title: "Say how you'd operate it", text: "Deployment, rollback, dashboards, alarms, and the runbook. Designs that can't be operated aren't designs." },
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Three-tier** = presentation, application, and data layers separated. **Loose coupling** = components that can change or fail independently. **Backpressure** = signalling upstream to slow down, usually via a queue. **Exponential backoff with jitter** = waiting progressively longer plus a random offset so retries don't synchronise. **Circuit breaker** = stopping calls to a failing dependency after repeated failures. **Graceful degradation** = losing features rather than the whole service. **202 Accepted** = the HTTP response meaning 'received, processing asynchronously'." },
      ],
      takeaways: [
        "The three-tier web app — Route 53, CloudFront, ALB, private compute, Multi-AZ data — is the default answer to most design prompts.",
        "Event-driven fan-out lets consumers be added without touching the producer.",
        "Queue-based decoupling handles slow work: accept fast, process at the worker's pace.",
        "Statelessness, loose coupling, idempotency, backpressure, and backoff-with-jitter make these designs actually work.",
        "Answer design questions by clarifying requirements, starting simple, then adding resilience, scale, cost, and operations.",
      ],
      flashcards: [
        { front: "What's in a standard AWS three-tier architecture?", back: "Route 53 → CloudFront (+WAF/ACM) → ALB in public subnets → app tier (ECS/ASG) in private subnets across ≥2 AZs → RDS Multi-AZ + ElastiCache in isolated subnets, with S3 for assets." },
        { front: "Why add jitter to exponential backoff?", back: "Without it, all clients retry at the same intervals and hit the recovering service in synchronised waves — the retry storm that keeps an outage going." },
        { front: "What does a queue give you architecturally?", back: "Decoupling, backpressure to absorb spikes, retries with a DLQ, and independent scaling of producer and consumer." },
        { front: "First thing to do in a system design question?", back: "Clarify requirements — traffic, latency, consistency, RTO/RPO, compliance, budget. Designing before asking is the classic mistake." },
      ],
      quiz: [
        { q: "Why does the application tier sit in private subnets?", options: ["It's cheaper", "So it isn't directly reachable from the internet — only through the load balancer", "Private subnets are faster", "It's required by AWS"], answer: 1, explain: "Only the ALB should be internet-facing. Private placement means an attacker must go through the load balancer and its WAF rules." },
        { q: "A downstream service slows and the whole system collapses under retries. What's missing?", options: ["More instances", "Exponential backoff with jitter and a circuit breaker", "A bigger database", "More AZs"], answer: 1, explain: "Naive retries multiply load on an already struggling dependency. Backoff with jitter plus a circuit breaker lets it recover." },
        { q: "Which pattern best fits a 10-minute video transcoding request from a web API?", options: ["Synchronous call and wait", "202 Accepted, SQS, worker fleet, poll or webhook", "Increase the API Gateway timeout", "Run it in the browser"], answer: 1, explain: "Accept the job immediately, queue it, process asynchronously, and notify — no HTTP path should stay open for ten minutes." },
      ],
    },
    {
      slug: "resilience-and-dr",
      title: "Resilience, RTO/RPO & disaster recovery",
      summary:
        "What availability targets really demand, the four DR strategies and their costs, multi-region honestly assessed, and testing that proves any of it works.",
      minutes: 11,
      blocks: [
        { type: "p", text: "Resilience is not a feature you enable; it's a set of decisions about what you're willing to lose and how quickly you must recover. Those decisions have names: **RTO** and **RPO**." },
        { type: "h2", text: "The two numbers" },
        { type: "list", items: [
          "**RTO (Recovery Time Objective)** — how long you can be down. Drives architecture: standby capacity, automation, failover mechanism.",
          "**RPO (Recovery Point Objective)** — how much data you can afford to lose, measured in time. Drives backup and replication frequency.",
          "Both are **business decisions**, not technical ones. Your job is to price the options and let the business choose — an RTO of 5 minutes and an RTO of 8 hours are different budgets, not different levels of professionalism.",
        ]},
        { type: "compare", caption: "What availability targets actually cost you in downtime.", columns: ["Target", "Downtime per year", "Roughly what it demands"], rows: [
          { label: "99% (two nines)", cells: ["3.65 days", "Single AZ, manual recovery"] },
          { label: "99.9% (three nines)", cells: ["8.8 hours", "Multi-AZ, automated failover, good monitoring"] },
          { label: "99.99% (four nines)", cells: ["52 minutes", "Multi-AZ everywhere, no single points of failure, tested automation, fast deploys"] },
          { label: "99.999% (five nines)", cells: ["5.3 minutes", "Multi-region, cell-based architecture, extreme operational maturity"] },
        ]},
        { type: "callout", kind: "key", text: "**Every nine costs roughly an order of magnitude more.** Four nines means 52 minutes of downtime *per year*, including deployments, AWS incidents, and human error — that's a serious engineering programme, not a checkbox. Most businesses genuinely need three nines and will be happier spending the difference elsewhere." },
        { type: "h2", text: "The four DR strategies" },
        { type: "diagram", name: "dr-strategies", caption: "Faster recovery costs more — pick the cheapest option that meets the business RTO/RPO." },
        { type: "compare", caption: "The standard ladder.", columns: ["Strategy", "RTO / RPO", "What runs in the DR region", "Relative cost"], rows: [
          { label: "Backup & restore", cells: ["Hours / hours", "Nothing — backups replicated", "$"] },
          { label: "Pilot light", cells: ["Tens of minutes / minutes", "Data replicating, core services off", "$$"] },
          { label: "Warm standby", cells: ["Minutes / seconds", "A scaled-down but running copy", "$$$"] },
          { label: "Multi-site active/active", cells: ["Near zero / near zero", "Full capacity serving traffic", "$$$$"] },
        ]},
        { type: "list", items: [
          "**Backup & restore** — cross-region snapshot copies and S3 replication, with IaC to rebuild. Cheap, slow, and perfectly adequate for many internal systems.",
          "**Pilot light** — the database is replicating continuously (Aurora Global Database, DynamoDB Global Tables) but compute is off. Recovery is scaling up, not rebuilding.",
          "**Warm standby** — a smaller version of production is always running and can be scaled up and cut over quickly. Also lets you test regularly, because it's genuinely alive.",
          "**Active/active** — traffic served from multiple regions via Route 53 or Global Accelerator. Highest cost, hardest correctness problems (data conflicts), and it removes failover as an event.",
        ]},
        { type: "h2", text: "Multi-region, honestly" },
        { type: "callout", kind: "warn", text: "Multi-region is not a bigger multi-AZ. It brings **data consistency problems** (replication lag, write conflicts), **doubled operational surface** (deploys, IAM, monitoring, quotas in both regions), **cross-region data transfer costs**, and **failover logic that must be tested or it won't work**. Multi-AZ handles the failures that actually happen most often. Go multi-region for regulation, genuine global latency, or a business-critical RTO — not for reassurance." },
        { type: "p", text: "The services that make it feasible: **Aurora Global Database** (sub-second replication, ~1 minute failover), **DynamoDB Global Tables** (active-active with last-writer-wins), **S3 Cross-Region Replication**, **Route 53 failover/latency routing with health checks**, and **Global Accelerator** for instant IP-level failover." },
        { type: "h2", text: "Designing for failure inside one region" },
        { type: "steps", items: [
          { title: "Eliminate single points of failure", text: "Two AZs minimum for every tier, including NAT gateways. Ask of each component: what if this instance, this AZ, or this dependency disappears?" },
          { title: "Make health checks honest", text: "They must fail when the app is genuinely unable to serve — a check that only proves the process is alive is worse than none." },
          { title: "Degrade gracefully", text: "Cached responses, feature flags to shed non-essential work, and read-only mode instead of a total outage." },
          { title: "Bound everything", text: "Timeouts, retries with backoff and jitter, connection pool limits, and circuit breakers — unbounded anything turns a slowdown into a collapse." },
          { title: "Practise recovery", text: "Game days with AWS Fault Injection Service: kill instances, fail an AZ, add latency, expire credentials. Fix what breaks." },
          { title: "Test restores on a schedule", text: "Measure the real recovery time and record it as your actual RTO — it's usually longer than the plan says." },
        ]},
        { type: "callout", kind: "key", text: "**A DR plan that has never been executed is a hypothesis.** The single most valuable resilience activity in most organisations is a quarterly restore-and-failover exercise, because it converts assumptions into a measured number — and the first attempt always finds something." },
        { type: "h2", text: "Cell-based architecture, briefly" },
        { type: "p", text: "At the highest availability tiers, AWS itself uses **cell-based architecture**: partition customers into independent cells, each a complete stack, so a failure or bad deploy affects one cell rather than everyone. Combined with **shuffle sharding** (assigning each customer a random subset of resources), it makes total outages structurally unlikely. It's worth knowing as the answer to 'how would you go beyond multi-AZ without multi-region?'" },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**RTO** = how long recovery may take. **RPO** = how much data you may lose. **Pilot light** = data replicating with compute switched off. **Warm standby** = a scaled-down live copy. **Active/active** = multiple regions serving traffic simultaneously. **Failover** = switching to the standby. **Failback** = returning to the primary afterwards, which is often harder. **Cell-based architecture** = independent full-stack partitions limiting blast radius. **Shuffle sharding** = giving each customer a random subset of resources so failures overlap minimally. **Game day** = a deliberate failure exercise." },
      ],
      takeaways: [
        "RTO and RPO are business decisions; your job is to price the options.",
        "Each additional nine of availability costs roughly an order of magnitude — most businesses need three.",
        "The DR ladder is backup-restore, pilot light, warm standby, active/active, in rising cost and falling RTO.",
        "Multi-region adds consistency problems, doubled ops, and transfer costs — use it for real requirements, not comfort.",
        "Within a region: no single points of failure, honest health checks, graceful degradation, bounded retries, and tested recovery.",
      ],
      flashcards: [
        { front: "RTO vs RPO", back: "RTO is how long you can be down (drives architecture and automation); RPO is how much data you can lose (drives backup and replication frequency)." },
        { front: "What is the pilot light strategy?", back: "Data replicates continuously to the DR region while compute stays switched off — recovery means scaling up rather than rebuilding, giving tens-of-minutes RTO at modest cost." },
        { front: "How much downtime does 99.99% allow per year?", back: "About 52 minutes — including deploys, AWS incidents, and human error, which is why it requires serious engineering rather than a setting." },
        { front: "What is shuffle sharding?", back: "Assigning each customer a random subset of resources so that any single failure affects only a small, mostly non-overlapping group of customers." },
      ],
      quiz: [
        { q: "The business accepts 4 hours of downtime and 15 minutes of data loss. Cheapest suitable strategy?", options: ["Multi-site active/active", "Warm standby", "Pilot light", "Backup and restore with hourly snapshots"], answer: 2, explain: "Pilot light meets a tens-of-minutes RTO with minutes of RPO at far lower cost than warm standby. Backup-restore alone typically can't guarantee a 15-minute RPO." },
        { q: "What most often makes a DR plan fail when it's finally needed?", options: ["Insufficient bandwidth", "It was never tested end to end", "The wrong instance type", "Missing tags"], answer: 1, explain: "Untested plans hide missing IAM permissions, stale AMIs, undocumented steps, and wrong DNS TTLs. Only an exercise reveals them." },
        { q: "Which is a genuine reason to go multi-region?", options: ["It feels safer", "Regulatory requirements, global latency, or a business-critical RTO multi-AZ can't meet", "To use more services", "Because the team knows Route 53"], answer: 1, explain: "Multi-region doubles operational surface and introduces data consistency problems, so it needs a requirement multi-AZ genuinely cannot satisfy." },
      ],
    },
    {
      slug: "migration-and-landing-zones",
      title: "Migration to AWS & the landing zone",
      summary:
        "The 7 Rs, how a real migration programme is sequenced, and the multi-account landing zone every serious AWS estate is built on.",
      minutes: 10,
      blocks: [
        { type: "p", text: "A great deal of cloud engineering work is not greenfield — it's moving what already exists. Migration has a well-established vocabulary and sequence, and knowing it marks you as someone who has been near a real programme." },
        { type: "h2", text: "The 7 Rs" },
        { type: "diagram", name: "migration-7rs", caption: "Seven dispositions per application, from switching it off to rebuilding it." },
        { type: "compare", caption: "What each one means in practice.", columns: ["Strategy", "What you do", "When it's right"], rows: [
          { label: "Retire", cells: ["Turn it off", "Nobody uses it — typically 10–20% of an estate, and the cheapest win available"] },
          { label: "Retain", cells: ["Leave it where it is, for now", "Recently invested in, or blocked by licensing/latency/regulation"] },
          { label: "Rehost", cells: ["Lift and shift to EC2 (AWS Application Migration Service)", "Speed matters most, or a data-center exit deadline is fixed"] },
          { label: "Relocate", cells: ["Move VMware workloads wholesale", "Large VMware estates moving without re-platforming"] },
          { label: "Replatform", cells: ["Lift and tinker — self-managed DB → RDS, VM → container", "A modest change removes a large amount of toil"] },
          { label: "Repurchase", cells: ["Replace with SaaS", "Commodity software: email, CRM, HR, ticketing"] },
          { label: "Refactor", cells: ["Re-architect cloud-native", "The application is strategic and its current form blocks the business"] },
        ]},
        { type: "callout", kind: "key", text: "Real portfolios end up **mostly retire, rehost, and replatform**, with refactor reserved for the few applications that genuinely earn it. Proposing to refactor everything is how migration programmes run years late — the value is usually in leaving the data center, not in rewriting a decade of code." },
        { type: "h2", text: "How a migration is sequenced" },
        { type: "steps", items: [
          { title: "Assess", text: "Discovery (AWS Application Discovery Service, or a partner tool) to inventory servers, dependencies, and utilisation. Build a business case with real TCO, not list prices." },
          { title: "Mobilise", text: "Build the landing zone, define guardrails, set up networking and identity, train the team, and migrate two or three low-risk applications to learn." },
          { title: "Wave planning", text: "Group applications into waves by dependency, not by team convenience. Applications that talk to each other move together, or you pay for cross-premises latency and traffic." },
          { title: "Migrate and validate", text: "Replicate, cut over in a maintenance window, validate functionality and performance, and keep a rollback path until confidence is earned." },
          { title: "Optimise", text: "Rightsize once you have real utilisation data, apply Savings Plans, replatform the obvious candidates, and shut down the old environment — the savings only materialise when you actually decommission." },
        ]},
        { type: "callout", kind: "warn", text: "The most expensive migration mistake is **finishing the migration but never decommissioning the source**. Paying for both environments indefinitely erases the business case. Put decommissioning dates in the plan and hold them." },
        { type: "h2", text: "The landing zone" },
        { type: "diagram", name: "multi-account-org", caption: "The multi-account structure everything else gets built inside." },
        { type: "p", text: "A **landing zone** is the pre-governed AWS environment applications land in: accounts, identity, networking, logging, and guardrails already in place so teams don't each invent them. **AWS Control Tower** builds one; large enterprises sometimes build their own with Terraform for finer control." },
        { type: "list", items: [
          "**Account structure** — Security OU (log archive, audit), Infrastructure OU (networking, shared services), Workloads OU (prod/staging/dev per application), Sandbox OU.",
          "**Identity** — IAM Identity Center federated to the corporate IdP, with permission sets per job function.",
          "**Network** — a Transit Gateway hub, centralised egress and DNS, non-overlapping CIDRs from a managed IPAM.",
          "**Logging** — organization CloudTrail and Config into a locked log-archive account.",
          "**Guardrails** — SCPs for region restrictions, root protection, and preventing security-service tampering, plus Config conformance packs.",
          "**Account vending** — a factory (Control Tower Account Factory or Terraform) so a new account arrives fully baselined in minutes, not weeks.",
        ]},
        { type: "callout", kind: "tip", text: "The landing zone is the highest-leverage work in an AWS estate. Every guardrail you put in it applies to every account created afterwards — and every one you skip becomes a hundred individual remediation tickets two years later." },
        { type: "h2", text: "Migrating data" },
        { type: "list", items: [
          "**Databases** — DMS with CDC for minimal downtime; the Schema Conversion Tool for engine changes.",
          "**File shares** — DataSync for bulk and incremental transfer; Storage Gateway for hybrid access during transition.",
          "**Very large volumes** — Snowball devices when the arithmetic beats the network (roughly above 50–100 TB on an ordinary link).",
          "**Applications** — AWS Application Migration Service (MGN) block-level replicates servers into AWS, enabling test cutovers before the real one.",
          "**Always rehearse the cutover** at least once against a copy. The first attempt always finds something.",
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Disposition** = the chosen R for a given application. **Wave** = a batch of applications migrated together. **Landing zone** = the pre-governed multi-account AWS environment. **Account vending** = automated creation of baselined accounts. **IPAM** = IP Address Manager, which prevents overlapping CIDR allocations. **Cutover** = the moment traffic moves to the new environment. **TCO** (Total Cost of Ownership) = the full cost including people, licences, and facilities — the honest basis for a business case. **MGN** = AWS Application Migration Service." },
        { type: "h2", text: "What a strong migration answer sounds like" },
        { type: "quote", text: "We'd start with discovery and a real TCO business case, build a Control Tower landing zone with SCP guardrails and Transit Gateway networking, then migrate in dependency-based waves — retiring what's unused, rehosting the bulk with MGN, replatforming databases onto RDS where it's cheap to do so, and refactoring only the two or three applications that justify it. Optimisation and decommissioning are in the plan from day one, not bolted on afterwards.", cite: "The shape of an answer that lands" },
      ],
      takeaways: [
        "The 7 Rs are retire, retain, rehost, relocate, replatform, repurchase, refactor — most estates are mostly the first five.",
        "Migrations run assess → mobilise → wave planning → migrate and validate → optimise, with decommissioning planned from the start.",
        "A landing zone provides accounts, identity, networking, logging, and guardrails before applications arrive.",
        "Account vending makes every future account baselined by default — the highest-leverage governance work available.",
        "Move data with DMS/CDC, DataSync, Snowball, or MGN, and always rehearse the cutover.",
      ],
      flashcards: [
        { front: "Name the 7 Rs of migration", back: "Retire, Retain, Rehost, Relocate, Replatform, Repurchase, Refactor." },
        { front: "Why plan migration waves by dependency?", back: "Applications that talk to each other should move together — splitting them across waves creates cross-premises latency, data transfer costs, and fragile hybrid links." },
        { front: "What is a landing zone?", back: "A pre-governed multi-account AWS environment — OUs, SCP guardrails, IAM Identity Center, centralised networking and logging — that applications land in, typically built with Control Tower." },
        { front: "What erases a migration business case?", back: "Never decommissioning the source environment, so you pay for both indefinitely." },
      ],
      quiz: [
        { q: "An estate has 400 applications and a data-center exit in 12 months. What dominates the plan?", options: ["Refactor everything to serverless", "Retire the unused, rehost the bulk, replatform selectively", "Retain everything", "Repurchase all of it as SaaS"], answer: 1, explain: "With a hard deadline, speed wins: retire what nobody uses, lift and shift the majority, and replatform only where it's cheap. Refactoring 400 applications in a year isn't achievable." },
        { q: "What's the first technical deliverable of a migration programme?", options: ["The first application", "A landing zone with guardrails, identity, networking, and logging", "A Savings Plan", "A CloudFront distribution"], answer: 1, explain: "Applications need somewhere governed to land. Building the landing zone first means every subsequent account inherits the guardrails automatically." },
        { q: "Which tool block-level replicates existing servers into AWS for a rehost?", options: ["DataSync", "AWS Application Migration Service (MGN)", "DMS", "Snowball"], answer: 1, explain: "MGN continuously replicates source servers so you can run test cutovers and then perform the real one with minimal downtime." },
      ],
    },
  ],
};
