import type { Module } from "./types";

export const role: Module = {
  id: "role",
  title: "The AWS Cloud Engineer role",
  blurb:
    "What the job actually involves day to day, the skill matrix beyond AWS, the certification roadmap, portfolio projects, and how AWS interviews really run.",
  accent: "amber",
  lessons: [
    {
      slug: "the-day-job",
      title: "What an AWS Cloud Engineer actually does",
      summary:
        "The real weekly shape of the role, the skills outside AWS that matter as much as AWS, and how the job differs from adjacent titles.",
      minutes: 9,
      blocks: [
        { type: "p", text: "Job adverts list services. The actual work is narrower and more repetitive than the adverts suggest — and knowing its real shape helps you prepare for the right things." },
        { type: "h2", text: "A representative week" },
        { type: "compare", caption: "Roughly how the time goes.", columns: ["Activity", "Share", "What it looks like"], rows: [
          { label: "Infrastructure as Code", cells: ["~30%", "Writing and reviewing Terraform/CDK, module design, plan reviews, state wrangling"] },
          { label: "Operations & incidents", cells: ["~20%", "Alarms, on-call, capacity, patching, upgrades, 'why is this slow'"] },
          { label: "CI/CD & automation", cells: ["~15%", "Pipelines, deployment safety, build tooling, scripts that remove toil"] },
          { label: "Enabling other teams", cells: ["~15%", "Reviews, access requests, answering 'how should we do X', documentation"] },
          { label: "Security & compliance", cells: ["~10%", "IAM policies, findings, audit evidence, guardrails"] },
          { label: "Cost", cells: ["~10%", "Reports, rightsizing, commitment planning, awkward questions about last month"] },
        ]},
        { type: "callout", kind: "key", text: "Notice what's small: greenfield architecture. Most of the job is **operating, automating, and improving what already exists** — and being the person other engineers ask before they build something. Optimising your preparation purely for architecture whiteboarding misses where the work is." },
        { type: "h2", text: "The skills that aren't AWS" },
        { type: "list", items: [
          "**Linux** — processes, systemd, networking tools, file systems, permissions, log locations. Half of debugging an EC2 problem is Linux, not AWS.",
          "**Networking fundamentals** — TCP/IP, subnetting, DNS, TLS, HTTP, routing. VPC is just these concepts with AWS names, and people who know the fundamentals learn VPC in an afternoon.",
          "**Python and Bash** — automation, Lambda functions, glue scripts, parsing output. You don't need to be a software engineer; you do need to write clear, testable scripts.",
          "**Git and code review** — infrastructure lives in pull requests, so branching, review etiquette, and clean commits are daily skills.",
          "**Terraform** — the most requested single tool in cloud engineering job postings.",
          "**Containers and Kubernetes** — at least ECS fluency; EKS fluency for many roles.",
          "**Databases** — enough SQL and operational knowledge to reason about slow queries, connections, and replication.",
          "**Communication** — writing a design doc, explaining a trade-off to a non-engineer, and running an incident calmly. This is what separates senior from mid.",
        ]},
        { type: "callout", kind: "warn", text: "The most common gap in candidates who know AWS well: **Linux and networking fundamentals**. Someone who can recite instance families but can't read `ss -tlnp`, explain a subnet mask, or diagnose a TLS handshake failure will struggle in the parts of the job that hurt." },
        { type: "h2", text: "Adjacent titles" },
        { type: "compare", caption: "Overlapping roles, different centres of gravity.", columns: ["Title", "Centre of gravity"], rows: [
          { label: "Cloud Engineer", cells: ["Building and running AWS infrastructure; IaC, networking, cost, security"] },
          { label: "DevOps Engineer", cells: ["Delivery pipelines and developer experience; heavy CI/CD and tooling"] },
          { label: "SRE", cells: ["Reliability as an engineering discipline; SLOs, error budgets, deep systems debugging"] },
          { label: "Cloud Architect", cells: ["Design, standards, and governance across many teams; less hands-on"] },
          { label: "Platform Engineer", cells: ["Building the internal platform other teams self-serve from"] },
          { label: "Security Engineer (cloud)", cells: ["IAM, detection, compliance, and incident response"] },
        ]},
        { type: "p", text: "In smaller companies these are one person. In large ones they're separate teams, and the boundaries are a frequent source of friction — worth asking about in an interview, because \"who owns production?\" tells you more about a job than the title does." },
        { type: "h2", text: "How to be good at it" },
        { type: "steps", items: [
          { title: "Automate the thing you did twice", text: "The compounding habit of the role. Manual work you repeat is a script you haven't written yet." },
          { title: "Leave things better than you found them", text: "Fix the noisy alarm, delete the orphaned volume, document the undocumented step. Small maintenance compounds into a system people trust." },
          { title: "Write things down", text: "Design docs, runbooks, and decision records (ADRs). Your future self is the most frequent reader, and it makes you scalable." },
          { title: "Understand the cost of what you build", text: "Being the engineer who knows the monthly figure gives your opinions weight in every meeting." },
          { title: "Be findable and kind", text: "Much of the role is unblocking others; being the person people are happy to ask is a genuine career asset." },
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Toil** = manual, repetitive operational work that scales with usage and produces no lasting value — the thing automation exists to remove. **On-call** = being responsible for responding to alerts outside working hours. **SLO** (Service Level Objective) = the reliability target you hold yourself to. **Error budget** = how much unreliability the SLO permits, spent deliberately on change. **ADR** (Architecture Decision Record) = a short document capturing a decision and its reasoning. **Platform team** = a team whose product is the internal developer platform." },
      ],
      takeaways: [
        "The job is mostly IaC, operations, CI/CD, and enabling other teams — greenfield architecture is a small slice.",
        "Linux, networking fundamentals, Python/Bash, Git, and Terraform matter as much as AWS service knowledge.",
        "Cloud Engineer, DevOps, SRE, Architect, and Platform roles overlap; the boundaries differ by company size.",
        "Automating repeated work, writing things down, and knowing costs are the habits that compound.",
        "Communication — design docs, trade-off explanations, calm incident handling — is what marks seniority.",
      ],
      flashcards: [
        { front: "What's the largest single time investment in a cloud engineer's week?", back: "Infrastructure as Code — writing and reviewing Terraform/CDK — followed by operations and incidents." },
        { front: "Most common skills gap in AWS-fluent candidates", back: "Linux and networking fundamentals. VPC concepts are ordinary networking with AWS names, and EC2 debugging is mostly Linux." },
        { front: "What is toil?", back: "Manual, repetitive operational work that scales with usage and creates no lasting value — the target of automation." },
        { front: "Cloud Engineer vs SRE", back: "Cloud Engineer centres on building and running the infrastructure; SRE centres on reliability as an engineering discipline with SLOs, error budgets, and deep debugging." },
      ],
      quiz: [
        { q: "Which activity typically consumes the most cloud-engineer time?", options: ["Greenfield architecture design", "Infrastructure as Code and reviews", "Writing documentation only", "Attending conferences"], answer: 1, explain: "Most infrastructure change flows through IaC and pull requests, making it the dominant activity in a typical week." },
        { q: "A candidate knows AWS services thoroughly but can't diagnose why a service isn't listening on a port. What's missing?", options: ["More certifications", "Linux and networking fundamentals", "Terraform", "Kubernetes"], answer: 1, explain: "Debugging real systems requires fundamentals underneath the AWS abstractions — the most common gap in otherwise strong candidates." },
        { q: "What best signals seniority in this role?", options: ["Knowing more service names", "Explaining trade-offs clearly and running incidents calmly", "Having the most certifications", "Writing the most code"], answer: 1, explain: "Judgement and communication distinguish senior engineers; service recall is table stakes and easily looked up." },
      ],
    },
    {
      slug: "certifications-and-study",
      title: "Certifications & a study plan that works",
      summary:
        "Which AWS certifications are worth your time, in what order, how much they actually help — and a realistic 12-week plan.",
      minutes: 9,
      blocks: [
        { type: "p", text: "Certifications are a useful forcing function and a weak proxy for ability. They open doors — particularly at consultancies and partners, where AWS partner tiers depend on certified headcount — and they never substitute for having built something." },
        { type: "h2", text: "The roadmap" },
        { type: "compare", caption: "The certifications, in a sensible order.", columns: ["Certification", "Level", "Worth it when"], rows: [
          { label: "Cloud Practitioner (CLF)", cells: ["Foundational", "You're brand new or non-technical; skippable if you'll sit SAA soon"] },
          { label: "Solutions Architect Associate (SAA)", cells: ["Associate", "**The one to get.** Broad coverage, the most recognised, the best value per hour"] },
          { label: "SysOps Administrator Associate (SOA)", cells: ["Associate", "Operations-focused roles; historically the hardest associate"] },
          { label: "Developer Associate (DVA)", cells: ["Associate", "You write application code on AWS (Lambda, SDKs, CI/CD)"] },
          { label: "Solutions Architect Professional (SAP)", cells: ["Professional", "Genuinely difficult; strong signal for senior and architect roles"] },
          { label: "DevOps Engineer Professional (DOP)", cells: ["Professional", "Pipelines, automation, and reliability at depth"] },
          { label: "Specialty (Security, Networking, ML, Data)", cells: ["Specialty", "You already work in that domain and want depth recognised"] },
        ]},
        { type: "callout", kind: "key", text: "**If you take exactly one, take the Solutions Architect Associate.** It covers the services this course teaches, it's the most widely recognised line on a CV, and preparing for it forces breadth you'd otherwise skip. Add SAP later only if you're targeting senior/architect roles or a partner requires it." },
        { type: "h2", text: "What exams actually test" },
        { type: "list", items: [
          "**Service selection under constraints** — 'cheapest option that meets these requirements', 'least operational overhead', 'highest availability'. Read for the constraint; it decides the answer.",
          "**Eliminating wrong answers.** Two options are usually clearly wrong; the discipline is choosing between the last two on the stated constraint.",
          "**Default best practices** — Multi-AZ, least privilege, encryption on, managed over self-managed, decoupled over synchronous.",
          "**They do not test** whether you can debug a real VPC at 2am. That's the job; this is the exam.",
        ]},
        { type: "h2", text: "A realistic 12-week plan" },
        { type: "steps", items: [
          { title: "Weeks 1–2 — Foundations & IAM", text: "Global infrastructure, accounts, pricing, IAM in depth. Create an account, secure root with MFA, set a $10 budget, build users and roles by hand." },
          { title: "Weeks 3–4 — Networking", text: "Build a VPC from scratch without a wizard: subnets, route tables, IGW, NAT, security groups, NACLs. Then rebuild it in Terraform. This is the highest-value fortnight in the plan." },
          { title: "Weeks 5–6 — Compute & storage", text: "EC2, AMIs, ASG behind an ALB; S3 with lifecycle, versioning, and a static site behind CloudFront. Break things deliberately and watch the ASG replace them." },
          { title: "Weeks 7–8 — Databases & serverless", text: "RDS Multi-AZ, DynamoDB modelling, then Lambda + API Gateway + DynamoDB deployed with SAM or CDK." },
          { title: "Weeks 9–10 — Containers, IaC & CI/CD", text: "Containerise an app, push to ECR, run on ECS Fargate, and deploy it from GitHub Actions using OIDC — no stored credentials." },
          { title: "Week 11 — Observability, security & cost", text: "Dashboards, alarms, structured logs, GuardDuty, Security Hub, Cost Explorer. Review your own account against the CIS benchmark." },
          { title: "Week 12 — Consolidate", text: "Practice exams until consistently above 80%, review every wrong answer to the underlying concept, and write up your projects." },
        ]},
        { type: "callout", kind: "tip", text: "**Budget alerts before anything else.** Set a $10 budget and a billing alarm on day one of week one. Every learner who has been surprised by a bill had skipped this, and it takes four minutes." },
        { type: "h2", text: "Study resources worth the time" },
        { type: "list", items: [
          "**AWS Skill Builder** — free digital training including the official exam-readiness courses.",
          "**AWS documentation and FAQs** — dry, authoritative, and the source most exam questions are derived from.",
          "**The Well-Architected Framework whitepaper** — short, and it directly shapes how exam scenarios are framed.",
          "**Practice exams** — the highest-yield preparation once you have the material; use them diagnostically, not as a memory test.",
          "**AWS Free Tier** — nothing beats building. Reading about NAT gateways teaches less than seeing one on your bill.",
          "**re:Invent talks** (especially the deep-dive and 'under the hood' sessions) — free, and better than most paid courses.",
        ]},
        { type: "callout", kind: "warn", text: "Avoid the certification treadmill. Three certifications and no projects reads worse than one certification and a repository containing a Terraform-built, CI/CD-deployed application. Interviewers probe for the thing you actually built." },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Associate / Professional / Specialty** = AWS's certification tiers by depth. **Exam readiness course** = AWS's official session on question style and scoring. **Scenario question** = a paragraph of context ending in 'which solution meets these requirements most cost-effectively'. **Recertification** = certifications expire after three years. **Partner tier** = AWS's ranking of consultancies, partly based on certified staff — why employers pay for exams." },
      ],
      takeaways: [
        "Solutions Architect Associate is the single highest-value certification; add professionals only for senior/architect targets.",
        "Exams test constrained service selection and default best practices, not real-world debugging.",
        "A 12-week plan works: foundations/IAM → networking → compute/storage → data/serverless → containers/IaC/CI-CD → observability → consolidation.",
        "Set a budget alert on day one and build in the Free Tier — reading is no substitute.",
        "Projects beat extra certifications; interviewers probe what you actually built.",
      ],
      flashcards: [
        { front: "Which single AWS certification gives the best return?", back: "Solutions Architect Associate — broad, widely recognised, and its syllabus matches everyday cloud engineering work." },
        { front: "How do AWS exam questions usually work?", back: "A scenario ending in a constraint — cheapest, least operational overhead, most highly available. Two options are clearly wrong; the constraint picks between the last two." },
        { front: "What's the highest-value fortnight of self-study?", back: "Building a VPC from scratch by hand and then rebuilding it in Terraform — networking underpins almost every real AWS problem." },
        { front: "Certifications vs projects", back: "Certifications open doors; projects get offers. One cert plus a Terraform-built, CI/CD-deployed application beats three certs and nothing built." },
      ],
      quiz: [
        { q: "You can only take one AWS exam. Which?", options: ["Cloud Practitioner", "Solutions Architect Associate", "A specialty exam", "DevOps Professional"], answer: 1, explain: "SAA offers the broadest, most recognised coverage and maps closely to daily cloud engineering work." },
        { q: "An exam question ends with 'most cost-effectively'. What does that tell you?", options: ["Pick the most managed service", "The constraint decides between otherwise valid options", "Pick the newest service", "All options are equal"], answer: 1, explain: "Several answers usually work technically; the stated constraint — cost, operational overhead, availability — is what selects the intended one." },
        { q: "What should you set up on day one of learning AWS?", options: ["A Savings Plan", "A budget alert and billing alarm", "An EKS cluster", "A multi-region deployment"], answer: 1, explain: "A $10 budget with alerts takes minutes and prevents the surprise-bill experience that derails many self-learners." },
      ],
    },
    {
      slug: "interviews-and-portfolio",
      title: "Interviews, portfolio projects & troubleshooting drills",
      summary:
        "How AWS-role interviews are structured, projects that actually impress, the troubleshooting scenarios you'll be given, and how AWS's own Leadership Principles work.",
      minutes: 11,
      blocks: [
        { type: "p", text: "Cloud engineering interviews follow a recognisable pattern. Preparing for the pattern — rather than trying to memorise 200 services — is what converts knowledge into offers." },
        { type: "h2", text: "The five rounds" },
        { type: "compare", caption: "What each round is really testing.", columns: ["Round", "Looks like", "Actually assessing"], rows: [
          { label: "Screening", cells: ["Rapid service questions, résumé walkthrough", "Baseline fluency and whether your CV is truthful"] },
          { label: "System design", cells: ["'Design a scalable web app / event pipeline on AWS'", "Requirement gathering, trade-offs, resilience, cost awareness"] },
          { label: "Troubleshooting", cells: ["'The site is slow / this can't connect — what do you do?'", "Systematic method under uncertainty; the strongest signal in the loop"] },
          { label: "Hands-on / coding", cells: ["Write Terraform, a Python script, or a CLI task", "Whether you actually work this way daily"] },
          { label: "Behavioural", cells: ["'Tell me about a time…'", "Ownership, judgement, and how you behave when things go wrong"] },
        ]},
        { type: "callout", kind: "key", text: "**The troubleshooting round separates candidates more than any other.** Interviewers aren't looking for the answer — they're watching whether you narrow the problem systematically, state assumptions, ask for evidence, and say what you'd check next rather than guessing." },
        { type: "h2", text: "A troubleshooting method that works" },
        { type: "steps", items: [
          { title: "Establish the symptom precisely", text: "All users or some? All requests or a percentage? Since when? What's the actual error and status code?" },
          { title: "Ask what changed", text: "Deployments, IaC applies, config changes, traffic shifts, AWS Health notices. Most incidents follow a change." },
          { title: "Narrow the layer", text: "DNS → edge/CDN → load balancer → application → database → downstream. Bisect rather than guessing." },
          { title: "Name the evidence you'd look at", text: "ALB target 5XX and response time, application logs by correlation ID, X-Ray service map, RDS Performance Insights, Flow Logs. Be specific — that specificity is the signal." },
          { title: "Form and test one hypothesis at a time", text: "Changing three things at once means learning nothing when it recovers." },
          { title: "Say how you'd mitigate before you fully understand", text: "Roll back, scale out, fail over, shed load. Recovery first, root cause second." },
        ]},
        { type: "h2", text: "Scenarios you should be able to walk through" },
        { type: "list", items: [
          "**'EC2 in a private subnet can't reach the internet.'** → route table default route, NAT gateway present and in a *public* subnet, NACLs both directions, security group egress, DNS resolution.",
          "**'S3 access denied despite full S3 permissions.'** → Block Public Access, bucket policy explicit deny, SCP, VPC endpoint policy, and — most likely — the **KMS key policy**.",
          "**'The site got slow after a deploy.'** → what changed, ALB p99 and 5XX, target health, application logs, database Performance Insights, connection pool saturation, then roll back.",
          "**'The bill doubled last month.'** → Cost Explorer grouped by service and then by tag, check `EC2-Other` for NAT and data transfer, look for a new region or forgotten load test, Anomaly Detection findings.",
          "**'Lambda is timing out intermittently.'** → duration p99 against the timeout, downstream latency in X-Ray, cold starts, concurrency throttling, VPC ENI or DNS resolution, database connection exhaustion.",
          "**'One AZ went down — what happens to our system?'** → walk each tier: ALB, ASG/ECS spread, RDS failover, NAT per AZ, and anything single-AZ you'd discover the hard way.",
        ]},
        { type: "h2", text: "Portfolio projects that actually land" },
        { type: "compare", caption: "Ranked by what they demonstrate.", columns: ["Project", "Shows"], rows: [
          { label: "Three-tier app, fully in Terraform, deployed by GitHub Actions with OIDC", cells: ["The whole job in one repository — IaC, networking, CI/CD, no stored credentials"] },
          { label: "Serverless API: API Gateway + Lambda + DynamoDB with SAM/CDK", cells: ["Event-driven design, IaC, and cost awareness"] },
          { label: "Containerised service on ECS Fargate with blue/green deploys", cells: ["Container fluency and deployment safety"] },
          { label: "A multi-account landing zone with SCP guardrails", cells: ["Governance thinking — rare and impressive in a junior candidate"] },
          { label: "A cost-optimisation write-up of your own account", cells: ["Business awareness and measurable results"] },
        ]},
        { type: "callout", kind: "tip", text: "**A README is half the project.** Include an architecture diagram, the decisions you made and rejected, the monthly cost, and what you'd do differently at 100× scale. Interviewers skim code and read READMEs — and 'what would you change at scale?' is often the first question they ask about it." },
        { type: "h2", text: "The behavioural round (and Amazon's version)" },
        { type: "p", text: "Use **STAR**: Situation, Task, Action, Result — with the Action being most of the answer and the Result quantified. Prepare six stories covering: an incident you handled, a mistake you made, a disagreement you resolved, something you automated, something you learned fast, and something you delivered under pressure. Each can be reframed for many questions." },
        { type: "p", text: "If you interview **at AWS itself**, the loop is explicitly structured around the **Leadership Principles**, and each interviewer probes specific ones. The ones that come up most for engineering roles: **Customer Obsession, Ownership, Invent and Simplify, Dive Deep, Bias for Action, Deliver Results, Earn Trust,** and **Are Right, A Lot**. Answers must be **your** actions ('I', not 'we'), with **data** in the result, and interviewers will drill several layers deeper — 'Dive Deep' means they will ask about the specific query, the specific metric, and the specific number." },
        { type: "callout", kind: "warn", text: "The most common behavioural failure is a story with no measurable outcome and no personal contribution. 'We improved reliability' says nothing. '**I** added ELB health checks and reduced failed-request rate from 2.1% to 0.04% over three weeks' is an answer." },
        { type: "h2", text: "Questions worth asking them" },
        { type: "list", items: [
          "How is infrastructure managed — what proportion is in IaC versus click-ops?",
          "How does on-call work, and what's a typical week's alert volume?",
          "Who owns production — the team that writes it, or a separate ops group?",
          "What's the deployment frequency, and how long does a rollback take?",
          "What's the biggest piece of technical debt you'd want this role to help with?",
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**STAR** = Situation, Task, Action, Result — the structure for behavioural answers. **Leadership Principles (LPs)** = Amazon's 16 stated principles that structure their entire interview loop. **Bar raiser** = an Amazon interviewer from outside the team with veto power over the hire. **Click-ops** = building infrastructure by hand in the console rather than in code. **Loop** = the full set of interview rounds. **Signal** = the evidence an interviewer is trying to gather about a specific competency." },
        { type: "quote", text: "Interviewers hire the person who is easiest to imagine doing the job on Monday. Show your method, not your memory.", cite: "The short version of everything above" },
      ],
      takeaways: [
        "Interviews have five rounds: screening, system design, troubleshooting, hands-on, and behavioural.",
        "Troubleshooting is the strongest differentiator — show a systematic method and name the specific evidence you'd examine.",
        "Rehearse the six standard scenarios: private-subnet egress, S3 AccessDenied, post-deploy slowness, bill doubling, Lambda timeouts, AZ failure.",
        "The best portfolio project is a full three-tier app in Terraform deployed by CI/CD with OIDC — and its README matters as much as the code.",
        "Behavioural answers need STAR, first-person actions, and quantified results; AWS's own loop probes Leadership Principles in depth.",
      ],
      flashcards: [
        { front: "Which interview round differentiates candidates most?", back: "Troubleshooting — because it reveals method under uncertainty rather than memorised facts." },
        { front: "S3 AccessDenied with full S3 permissions — checklist?", back: "Block Public Access, bucket policy explicit deny, SCP, VPC endpoint policy, and most commonly the KMS key policy missing kms:Decrypt." },
        { front: "What makes a portfolio project impressive?", back: "End-to-end realism — Terraform-defined, CI/CD-deployed with OIDC, multi-AZ — plus a README with an architecture diagram, decisions, cost, and what you'd change at scale." },
        { front: "Why do behavioural answers fail?", back: "No measurable result and no personal contribution. Say what *you* did and quantify the outcome." },
      ],
      quiz: [
        { q: "In a troubleshooting round, what should you do first?", options: ["Propose a fix immediately", "Establish the precise symptom and ask what changed", "List every AWS service involved", "Suggest a rebuild"], answer: 1, explain: "Narrowing the symptom and identifying recent changes resolves a large share of real incidents and demonstrates method rather than guessing." },
        { q: "Which project best demonstrates readiness for a cloud engineer role?", options: ["A console-built EC2 instance", "A three-tier app in Terraform deployed by GitHub Actions via OIDC", "A list of certifications", "A blog post about AWS"], answer: 1, explain: "It exercises IaC, networking, multi-AZ design, CI/CD, and credential-free authentication — the actual daily work, evidenced." },
        { q: "What's missing from 'we improved reliability last year'?", options: ["Nothing", "Your specific actions and a quantified result", "More technical terms", "A longer story"], answer: 1, explain: "Interviewers need your individual contribution and a measurable outcome — the STAR Action and Result are where the signal lives." },
      ],
    },
  ],
};
