import type { Pattern } from "./types";

export const patterns: Pattern[] = [
  {
    name: "Three-tier web application",
    tagline: "Route 53 → CloudFront → ALB → private app tier → Multi-AZ data.",
    diagram: "three-tier-reference",
    when: "The default shape for most AWS applications, and the answer to nearly every 'design a scalable web app' prompt.",
    watch: "The app tier must be stateless — sessions in ElastiCache, uploads in S3 — or autoscaling and deploys silently lose data.",
    accent: "iris",
  },
  {
    name: "Multi-AZ high availability",
    tagline: "Span at least two Availability Zones so one failing doesn't take you down.",
    diagram: "availability-multi-az",
    when: "Every production workload. It's the highest-value resilience decision on AWS and usually close to free.",
    watch: "Deploy a NAT gateway per AZ too — a single shared NAT reintroduces the single point of failure you just removed.",
    accent: "teal",
  },
  {
    name: "Autoscaling web tier",
    tagline: "A load balancer over a fleet that grows, shrinks, and replaces its own failures.",
    diagram: "autoscaling",
    when: "Stateless web and app tiers with variable traffic — you get elasticity and self-healing from the same construct.",
    watch: "Enable ELB health checks as well as EC2 status checks, or a hung application keeps serving errors forever.",
    accent: "amber",
  },
  {
    name: "Public/private subnet tiering",
    tagline: "Expose only the load balancer; hide compute and data in private subnets.",
    diagram: "vpc-anatomy",
    when: "Every VPC. Minimising what's directly reachable from the internet is the cheapest security control available.",
    watch: "NAT gateways bill hourly and per GB — add free gateway endpoints for S3 and DynamoDB before the bill arrives.",
    accent: "rose",
  },
  {
    name: "Event-driven fan-out",
    tagline: "Publish once; independent consumers react without the producer knowing they exist.",
    diagram: "event-driven-fanout",
    when: "Several teams or services need to react to the same business event, and more will be added later.",
    watch: "Put an SQS queue in front of each consumer so one slow subscriber can't lose messages — and make every consumer idempotent.",
    accent: "iris",
  },
  {
    name: "Queue-based decoupling",
    tagline: "Accept fast, return 202, and let workers process at their own pace.",
    diagram: "queue-decoupling",
    when: "Slow work behind a fast API — video encoding, report generation, third-party calls — or any spike that would overwhelm a downstream service.",
    watch: "Set the visibility timeout well above processing time, or messages reappear mid-flight and you get duplicate side effects.",
    accent: "teal",
  },
  {
    name: "Serverless API",
    tagline: "API Gateway → Lambda → DynamoDB, scaling to zero when idle.",
    diagram: "serverless-event",
    when: "Spiky or low-volume APIs, internal tools, and event glue — no servers, no idle cost, deployed with SAM or CDK.",
    watch: "API Gateway's integration timeout is 29 seconds, and very high sustained throughput is usually cheaper on containers.",
    accent: "amber",
  },
  {
    name: "Edge caching with CloudFront",
    tagline: "Serve from 600+ edge locations; only cache misses reach the origin.",
    diagram: "cdn",
    when: "Global audiences, static-heavy sites, and any origin you want shielded from spikes — it also cuts egress cost.",
    watch: "Cache-key design is everything: forwarding all headers and cookies makes every request unique and the hit rate collapses.",
    accent: "iris",
  },
  {
    name: "Private S3 behind CloudFront (OAC)",
    tagline: "A private bucket with only CloudFront allowed to read it.",
    diagram: "s3-request-flow",
    when: "Any public website or asset delivery from S3 — it replaces public buckets entirely and adds TLS, caching, and WAF.",
    watch: "The ACM certificate must be issued in us-east-1, and single-page apps need 403/404 mapped back to /index.html.",
    accent: "rose",
  },
  {
    name: "Hub-and-spoke with Transit Gateway",
    tagline: "One regional router replaces a mesh of peering connections.",
    diagram: "network-topology",
    when: "More than a handful of VPCs, plus on-prem connectivity, with prod/non-prod segmentation via per-attachment route tables.",
    watch: "The hub becomes a critical dependency — and none of it works if CIDRs overlap, so plan addressing before you build.",
    accent: "teal",
  },
  {
    name: "Hybrid connectivity",
    tagline: "Direct Connect for the primary path, Site-to-Site VPN as the encrypted backup.",
    diagram: "hybrid-connectivity",
    when: "A data center that must reach AWS privately with consistent latency, typically during a migration or for a permanent hybrid estate.",
    watch: "Direct Connect is not redundant by default and takes weeks to provision — design the second path from the start.",
    accent: "iris",
  },
  {
    name: "Caching layer",
    tagline: "Cache-aside in ElastiCache in front of the database.",
    diagram: "caching-layer",
    when: "Read-heavy workloads with repeated queries, session storage, leaderboards, and rate limiting.",
    watch: "Always set a TTL as the staleness backstop, and plan for thundering herd when a hot key expires or the cache restarts cold.",
    accent: "amber",
  },
  {
    name: "Blue/green & canary deployment",
    tagline: "Shift traffic gradually, watch the alarms, roll back instantly.",
    diagram: "deployment-strategies",
    when: "Any user-facing service where a bad release must not become an outage — ALB weighted target groups give canaries free.",
    watch: "Rollback automation is only as good as the health check; one that returns 200 regardless of dependencies promotes broken releases.",
    accent: "rose",
  },
  {
    name: "CI/CD with OIDC",
    tagline: "Build once, promote the artifact, authenticate with no stored credentials.",
    diagram: "cicd-pipeline",
    when: "Every repository. It's the only sanctioned path to production and removes long-lived AWS keys from your CI system.",
    watch: "Pin the OIDC trust policy to the org, repo, and branch — an unpinned `sub` claim lets any repository assume your role.",
    accent: "iris",
  },
  {
    name: "Multi-account landing zone",
    tagline: "OUs, SCP guardrails, centralised logging, and an account factory.",
    diagram: "multi-account-org",
    when: "Any organisation beyond a couple of engineers — every guardrail here applies automatically to every future account.",
    watch: "Keep the management account free of workloads, and remember SCPs cap permissions but never grant them.",
    accent: "teal",
  },
  {
    name: "Disaster recovery ladder",
    tagline: "Backup-restore, pilot light, warm standby, or active/active.",
    diagram: "dr-strategies",
    when: "Whenever the business states an RTO and RPO — pick the cheapest rung that meets them, not the most impressive one.",
    watch: "A plan you've never executed is a hypothesis. Schedule a real failover and restore test, and record the measured time as your true RTO.",
    accent: "rose",
  },
  {
    name: "Well-Architected review",
    tagline: "Pressure-test any design against six pillars before it ships.",
    diagram: "well-architected",
    when: "Before launch and after any major change in traffic, region, or compliance obligation.",
    watch: "The pillars conflict deliberately — a good review names the trade-off rather than claiming to maximise everything.",
    accent: "amber",
  },
  {
    name: "Migration by the 7 Rs",
    tagline: "Retire, retain, rehost, relocate, replatform, repurchase, refactor.",
    diagram: "migration-7rs",
    when: "Moving an existing estate to AWS — assign a disposition per application and plan waves by dependency.",
    watch: "Put decommissioning dates in the plan. Paying for both environments indefinitely erases the entire business case.",
    accent: "iris",
  },
];
