import type { GlossaryTerm } from "./types";

export const glossary: GlossaryTerm[] = [
  { term: "Agent", def: "An LLM that uses tools in a loop to pursue a goal, deciding its own next steps rather than following a fixed script.", related: ["Agent loop", "Workflow"] },
  { term: "Agent loop", def: "The core cycle of an agent: perceive → reason → act → observe, repeating until the goal is met or a limit is hit.", related: ["Agent", "ReAct"] },
  { term: "Workflow", def: "An LLM system whose steps are controlled by your code along predefined paths — as opposed to an agent, where the model chooses the path.", related: ["Agent"] },
  { term: "Harness", def: "The code surrounding the model that assembles each request, runs the loop, executes tools, and enforces limits/guardrails.", related: ["Agent loop", "Guardrails"] },
  { term: "Context engineering", def: "Curating what enters the context window each turn — the right instructions, tools, and facts in, stale data out. The dominant lever on agent quality.", related: ["Context window", "Memory (agent)"] },
  { term: "Context window", def: "The maximum tokens a model can consider at once; system prompt, history, tools, retrieved data, and the reply all share this budget.", related: ["Token", "Context engineering"] },
  { term: "Token", def: "The unit a model reads and bills in — roughly 3–4 characters of English. Cost and limits are measured in tokens.", related: ["Context window"] },
  { term: "Tool use (function calling)", def: "Letting a model call functions you define. It emits a structured request; your code runs it and returns the result.", related: ["Agent", "Tool description"] },
  { term: "Tool description", def: "The natural-language docs for a tool — the primary signal the model uses to decide whether and how to call it.", related: ["Tool use (function calling)"] },
  { term: "Chain of thought (CoT)", def: "Prompting a model to generate intermediate reasoning before its answer, improving multi-step accuracy.", related: ["ReAct", "Reflection"] },
  { term: "ReAct", def: "Reason + Act: interleaving Thought, Action (tool call), and Observation in a loop — the default single-agent pattern.", related: ["Agent loop", "Chain of thought (CoT)"] },
  { term: "Plan-and-execute", def: "Separating planning (decompose the goal into subtasks) from execution (carry them out), with optional replanning.", related: ["Decomposition", "ReAct"] },
  { term: "Reflection", def: "A generate → critique → revise loop where an agent improves its own output against criteria or external checks.", related: ["LLM-as-judge"] },
  { term: "Decomposition", def: "Breaking a complex goal into smaller, focused subtasks (sequential, parallel, or recursive).", related: ["Routing", "Plan-and-execute"] },
  { term: "Routing", def: "Classifying an input and dispatching it to the best-suited, right-sized handler.", related: ["Decomposition"] },
  { term: "Memory (agent)", def: "Engineered state for a stateless model: short-term (the context window) plus long-term stores retrieved on demand.", related: ["Episodic memory", "Semantic memory", "Procedural memory", "Context engineering"] },
  { term: "Episodic memory", def: "Long-term memory of past events/interactions an agent can recall later.", related: ["Memory (agent)"] },
  { term: "Semantic memory", def: "Long-term memory of facts and knowledge (e.g. user preferences).", related: ["Memory (agent)"] },
  { term: "Procedural memory", def: "Long-term memory of how to do things — skills, learned routines, saved tool sequences.", related: ["Memory (agent)"] },
  { term: "Compaction", def: "Summarizing earlier conversation/history to keep a long run within the context window.", related: ["Context window", "Memory (agent)"] },
  { term: "RAG", def: "Retrieval-Augmented Generation: fetch relevant chunks from a knowledge base and inject them into the prompt so the model answers from real facts.", related: ["Embedding", "Agentic RAG", "Vector database"] },
  { term: "Agentic RAG", def: "Exposing retrieval as a tool the agent calls when it decides it needs facts — issuing multiple refined queries instead of one blind retrieval.", related: ["RAG", "Tool use (function calling)"] },
  { term: "Embedding", def: "A vector capturing the meaning of text so similar meanings land near each other, enabling semantic search.", related: ["RAG", "Vector database"] },
  { term: "Vector database", def: "A store optimized for similarity search over embeddings — the index behind retrieval.", related: ["Embedding", "RAG"] },
  { term: "MCP (Model Context Protocol)", def: "An open standard for connecting agents to tools, data resources, and prompts. Build a connector once; any MCP-aware client can use it.", related: ["Tool use (function calling)"] },
  { term: "Multi-agent system", def: "Several focused agents, each with its own role/tools/context, coordinated toward a shared goal.", related: ["Supervisor pattern", "Handoff", "Shared state (blackboard)"] },
  { term: "Supervisor pattern", def: "Orchestrator-workers: a lead agent decomposes a goal, delegates subtasks to workers, and synthesizes their results. The controllable default.", related: ["Multi-agent system", "Hierarchical agents"] },
  { term: "Hierarchical agents", def: "Nested supervisors (supervisors of supervisors) forming an org chart for large systems.", related: ["Supervisor pattern"] },
  { term: "Network (peer-to-peer)", def: "A topology where any agent can hand off to any other — flexible but harder to control.", related: ["Multi-agent system", "Handoff"] },
  { term: "Handoff", def: "Transferring control (and curated context) from one agent to another, often implemented as a callable tool.", related: ["Multi-agent system", "Delegation"] },
  { term: "Delegation", def: "An agent calling another as a subtask, getting a result, and keeping control — versus a handoff, which transfers control fully.", related: ["Handoff"] },
  { term: "Shared state (blackboard)", def: "Coordinating agents through a common store they read and write, rather than messaging each peer directly.", related: ["Multi-agent system"] },
  { term: "CrewAI", def: "A role-based multi-agent framework: assemble a Crew of Agents that complete Tasks under a Process (sequential or hierarchical).", related: ["Crew", "Process (CrewAI)", "Flow (CrewAI)"] },
  { term: "Crew", def: "In CrewAI, the team — a set of agents and tasks executed under a chosen process.", related: ["CrewAI", "Process (CrewAI)"] },
  { term: "Process (CrewAI)", def: "A crew's execution strategy: sequential (a pipeline) or hierarchical (a manager agent plans and delegates).", related: ["Crew", "Supervisor pattern"] },
  { term: "Flow (CrewAI)", def: "Event-driven, code-controlled orchestration in CrewAI (@start/@listen/@router + state) that can invoke autonomous Crews.", related: ["CrewAI", "Workflow"] },
  { term: "LangGraph", def: "A framework modeling agent systems as a graph of nodes and edges over a shared state, with cycles, checkpointing, and human-in-the-loop.", related: ["State graph", "Human-in-the-loop (HITL)"] },
  { term: "State graph", def: "LangGraph's model: nodes transform shared state, edges (some conditional) route execution, and cycles enable the agent loop.", related: ["LangGraph"] },
  { term: "AutoGen", def: "Microsoft's framework where multi-agent collaboration happens through conversation between agents (and optionally a human).", related: ["Multi-agent system"] },
  { term: "OpenAI Agents SDK", def: "A minimal agent framework built on agents + handoffs, plus guardrails, sessions, and tracing. Successor to Swarm.", related: ["Handoff", "Guardrails"] },
  { term: "Evaluation (agent)", def: "Measuring agent quality with a dataset, a runner, and graders — at the outcome, trajectory, and component levels.", related: ["LLM-as-judge", "Trajectory"] },
  { term: "Trajectory", def: "The sequence of steps an agent took (tools, decisions) — evaluated to judge how, not just whether, it solved a task.", related: ["Evaluation (agent)", "Observability"] },
  { term: "LLM-as-judge", def: "Using a model to score open-ended output against a rubric — flexible but needing its own validation against human labels.", related: ["Evaluation (agent)", "Reflection"] },
  { term: "Observability", def: "Recording what an agent actually did — prompts, tool calls, decisions, tokens, latency — as traces of nested spans.", related: ["Trajectory", "Evaluation (agent)"] },
  { term: "Guardrails", def: "Enforced limits around an agent: input screening, tool/action constraints, output validation, and resource caps.", related: ["Harness", "Human-in-the-loop (HITL)"] },
  { term: "Human-in-the-loop (HITL)", def: "Pausing the agent for a human to approve, edit, or reject — reserved for irreversible, high-stakes, or low-confidence actions.", related: ["Guardrails"] },
  { term: "Prompt injection", def: "Malicious text posing as instructions (often hidden in fetched content) to make an agent misuse its tools or leak data.", related: ["Lethal trifecta", "Guardrails"] },
  { term: "Lethal trifecta", def: "The dangerous combination of private-data access + untrusted content + external action that lets an injection exfiltrate or destroy.", related: ["Prompt injection"] },
  { term: "Least privilege", def: "Giving each agent the minimum tools, data scope, and permissions it needs — limiting the blast radius of any failure or injection.", related: ["Guardrails", "Prompt injection"] },
  { term: "Prompt caching", def: "Reusing a stable prompt prefix across requests to cut input cost (often ~90%) and latency.", related: ["Context window", "Token"] },
  { term: "Stateless", def: "A model remembers nothing between calls; the app must resend context each time. The reason memory must be engineered.", related: ["Memory (agent)", "Context window"] },
  { term: "Agentic stack", def: "The layers around a production agent: models, model access, tools/MCP, memory, orchestration, observability & evals, guardrails & HITL." },
  { term: "Agent harness", def: "A thin runtime around the loop — tools, permissions, context management — increasingly favored over heavyweight orchestration frameworks.", related: ["Agentic stack"] },
  { term: "Coding agent", def: "An agent (Claude Code, Cursor agents) that runs the loop on a repo: explores, edits, runs tests, iterates. The category's biggest success so far.", related: ["Agent loop"] },
  { term: "Spec-driven development", def: "Humans write precise behavior specs and review diffs; coding agents implement. The craft moves upstream from typing to defining and verifying.", related: ["Coding agent"] },
  { term: "A2A (Agent2Agent)", def: "An open protocol for agent↔agent interoperability: Agent Cards for discovery, tasks and artifacts for delegation across vendors and frameworks.", related: ["MCP (Model Context Protocol)", "Agent Card"] },
  { term: "Agent Card", def: "A2A's discovery document — JSON describing an agent's skills, endpoint, and auth, so other agents can find and address it.", related: ["A2A (Agent2Agent)"] },
  { term: "Voice agent", def: "An agent operating over speech under a ~1-second conversational latency budget — via a cascaded STT→LLM→TTS pipeline or a speech-to-speech model.", related: ["Speech-to-speech model", "Barge-in"] },
  { term: "Speech-to-speech model", def: "An audio-native model that listens and speaks directly over a streaming connection — human-level latency and prosody, no transcription hop.", related: ["Voice agent"] },
  { term: "Barge-in", def: "A user interrupting the agent mid-speech; the agent must stop instantly, discard queued audio, and treat the interruption as new input.", related: ["Voice agent"] },
  { term: "Turn detection", def: "Deciding when the user has finished speaking. Semantic end-of-turn detection beats fixed silence timers — too eager interrupts, too patient adds dead air.", related: ["Voice agent"] },
  { term: "Ambient agent", def: "An agent triggered by events, schedules, and state changes rather than chat — running in the background and judging what deserves action or attention.", related: ["Proactive agent"] },
  { term: "Proactive agent", def: "An agent that initiates: notifying, drafting, or acting before being asked. Graded on precision — every notification spends a trust budget.", related: ["Ambient agent", "Human-in-the-loop (HITL)"] },
  { term: "Agentic web", def: "Infrastructure treating agents as first-class web clients: MCP endpoints over scraping, A2A delegation, and agentic-commerce payment mandates.", related: ["MCP (Model Context Protocol)", "A2A (Agent2Agent)", "Agentic commerce"] },
  { term: "Agentic commerce", def: "Protocols letting agents transact with scoped, verifiable payment mandates instead of stored cards — delegated spending authority with caps and audit trails.", related: ["Agentic web"] },
  { term: "Agent washing", def: "Rebranding chatbots, RPA scripts, and fixed automations as 'agents'. Test: does the model choose next steps at runtime, or does code?", related: ["Workflow"] },
  { term: "Agent swarm", def: "Many agents attacking one goal in parallel with dynamic spawning and shared artifacts — powerful for parallelizable work, cost- and error-multiplying elsewhere.", related: ["Multi-agent system"] },
  { term: "Vertical agent", def: "An agent purpose-built for one domain (legal, medical, recruiting) with domain tools, data, and evals baked in — the commercially winning shape.", related: ["Agent washing"] },
  { term: "Service-as-software", def: "Selling completed outcomes (resolved tickets, booked meetings) priced per result instead of seats — which makes agent reliability evals the unit economics.", related: ["Vertical agent", "Evaluation (agent)"] },
  { term: "Digital worker", def: "An agent framed as headcount — a name, a role, an inbox. Useful adoption framing; architecturally still tools + loop + guardrails.", related: ["Agent washing"] },
];
