import type { Pattern } from "./types";

export const patterns: Pattern[] = [
  {
    name: "ReAct",
    tagline: "Reason → Act → Observe, in a loop.",
    diagram: "react-loop",
    when: "The default single-agent pattern: any task needing tools plus deliberation between steps.",
    watch: "Doom loops on failing actions and ignored observations — cap iterations and make tool errors loud.",
    accent: "teal",
  },
  {
    name: "Plan-and-Execute",
    tagline: "Decide the plan first, then carry it out.",
    diagram: "plan-execute",
    when: "Long, complex tasks where step-by-step reasoning drifts or repeats work.",
    watch: "Rigid plans break on surprises — always allow replanning; skip it for short tasks.",
    accent: "iris",
  },
  {
    name: "Reflection",
    tagline: "Generate → critique → revise.",
    diagram: "reflection",
    when: "Quality-critical output — code, writing, analysis — where a second look pays off.",
    watch: "Self-grading is lenient and returns diminish; ground critiques in tests/rubrics and cap rounds.",
    accent: "rose",
  },
  {
    name: "Routing",
    tagline: "Classify the input, dispatch to a specialist.",
    diagram: "react-loop",
    when: "Mixed workloads where different inputs need different handlers or model sizes.",
    watch: "A wrong classification sends work down the wrong path — evaluate the router itself.",
    accent: "amber",
  },
  {
    name: "Supervisor (Orchestrator-Workers)",
    tagline: "A lead delegates subtasks and synthesizes results.",
    diagram: "supervisor",
    when: "A goal that decomposes into delegable subtasks — the controllable multi-agent default.",
    watch: "The supervisor is a bottleneck and single point of failure; give it a capable model.",
    accent: "rose",
  },
  {
    name: "Hierarchical",
    tagline: "Supervisors of supervisors — an org chart.",
    diagram: "hierarchical",
    when: "Large systems where one supervisor's span of control is overloaded.",
    watch: "Each layer adds latency and cost; keep the tree as shallow as the task allows.",
    accent: "iris",
  },
  {
    name: "Network (Peer-to-Peer)",
    tagline: "Any agent can hand off to any other.",
    diagram: "network",
    when: "Open-ended collaboration that can't be neatly hierarchical.",
    watch: "Conversations sprawl and are hard to bound; add ownership rules and handoff caps.",
    accent: "teal",
  },
  {
    name: "Handoff",
    tagline: "Transfer control to a better-suited agent.",
    diagram: "handoff",
    when: "Triage and specialist routing within a multi-agent system.",
    watch: "Context dies at the seam and agents ping-pong — pass a curated briefing, cap handoffs.",
    accent: "amber",
  },
  {
    name: "Shared State (Blackboard)",
    tagline: "Agents coordinate through a common store.",
    diagram: "blackboard",
    when: "Larger or parallel systems needing decoupling and central inspection.",
    watch: "Concurrency hazards: stale reads, conflicting writes — use field ownership and append-only logs.",
    accent: "iris",
  },
  {
    name: "Agentic RAG",
    tagline: "Retrieval as a tool the agent calls on demand.",
    diagram: "rag-agent",
    when: "Knowledge-grounded tasks where the agent should decide when and what to retrieve.",
    watch: "Answer quality is capped by retrieval quality — invest in chunking, hybrid search, re-ranking.",
    accent: "amber",
  },
  {
    name: "Reflexion / Evaluator-Optimizer",
    tagline: "A separate evaluator scores and steers a generator.",
    diagram: "eval-agent",
    when: "Tasks with checkable criteria where an explicit judge can guide iteration.",
    watch: "Validate the evaluator against humans; a biased judge optimizes the wrong thing.",
    accent: "teal",
  },
  {
    name: "Human-in-the-Loop",
    tagline: "Pause for approval on the actions that matter.",
    diagram: "human-in-loop",
    when: "Irreversible, high-stakes, low-confidence, or ambiguous actions.",
    watch: "Too many gates kill the speed benefit — match oversight to stakes and reversibility.",
    accent: "rose",
  },
];
