import type { Module } from "./types";

export const foundations: Module = {
  id: "foundations",
  title: "Foundations",
  blurb:
    "What an AI Engineer actually does, how a language model really works under the hood, the 2026 model landscape, and the reference stack every GenAI product is assembled from.",
  accent: "iris",
  lessons: [
    {
      slug: "what-is-an-ai-engineer",
      title: "What is an AI Engineer?",
      summary:
        "A role that barely existed five years ago and is now on every hiring plan — what it is, how it differs from ML engineering and data science, and what you're actually paid to decide.",
      minutes: 9,
      blocks: [
        { type: "p", text: "An **AI Engineer** builds products on top of models somebody else trained. You are not gathering a dataset and running gradient descent; you are taking a general-purpose model — an API call away, or a set of open weights on your own GPUs — and turning it into a system that is *reliable enough to put in front of users*." },
        { type: "callout", kind: "key", text: "The one-line definition: **an AI Engineer turns a probabilistic model into a dependable product.** Everything in this course — prompting, retrieval, tools, evals, guardrails, inference tuning — exists to close the gap between *it worked in the playground* and *it works for 10,000 users at 3 a.m.*" },
        { type: "h2", text: "Why the role appeared" },
        { type: "p", text: "Until about 2022, using machine learning in a product meant training a model: collect labelled data, pick an architecture, train, evaluate, deploy, retrain as it drifts. That work needs an **ML Engineer**, and it takes months. Then pretrained language models became good enough to solve a large class of those problems *with no training at all* — you describe the task in words." },
        { type: "p", text: "That collapsed the time-to-first-working-version from months to an afternoon, and it moved the hard part. The hard part is no longer *can a model do this?* It is **can this model do it consistently, cheaply, safely, and fast enough — and how would we know?** Answering that is the AI Engineer's job, and it is much closer to software and systems engineering than to statistics." },
        { type: "diagram", name: "role-spectrum", caption: "The AI Engineer sits between ML engineering and product software — model as a dependency, not a deliverable." },
        { type: "h2", text: "How the neighbouring roles differ" },
        { type: "compare", caption: "Overlapping, but with genuinely different centres of gravity.", columns: ["Role", "Owns", "Typical artefact", "Core skill"], rows: [
          { label: "Data Scientist", cells: ["Questions and evidence", "An analysis, a metric, an experiment readout", "Statistics and causal reasoning"] },
          { label: "ML Engineer", cells: ["Trained models and their pipelines", "A training pipeline and a served model", "Modelling, feature engineering, MLOps"] },
          { label: "AI Engineer", cells: ["Products built on existing models", "A retrieval/agent system with an eval suite", "Systems design, evaluation, prompt & context engineering"] },
          { label: "Research Engineer", cells: ["The models themselves", "A pretrained or post-trained checkpoint", "Deep learning, distributed training, CUDA"] },
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**LLM** (Large Language Model) = a model trained to predict the next token of text, which turns out to be enough to summarise, translate, code, and reason. **Foundation model** = a large model pretrained on broad data, then adapted to many tasks. **Inference** = running a trained model to get an answer (as opposed to *training* it). **Frontier model** = the most capable models available at a given moment. **Open-weight** = a model whose parameters you can download and run yourself. **GenAI** = generative AI, the umbrella term for models that produce text, images, audio, or video." },
        { type: "h2", text: "What you're actually paid to decide" },
        { type: "p", text: "Almost every day of the job comes down to a handful of recurring trade-offs. Interviewers probe these directly, because they separate people who have shipped from people who have demoed." },
        { type: "list", items: [
          "**Which model, for which request?** Frontier quality costs 10–50× the cheap tier. Most systems route: a small model for classification and extraction, a big one for the hard 5%.",
          "**Prompt, retrieve, or fine-tune?** In that order, almost always. Fine-tuning is the answer to *behaviour and format*, retrieval is the answer to *knowledge*, and people reach for the wrong one constantly.",
          "**How much context, and which context?** Long context windows made it *possible* to stuff everything in; cost, latency, and attention dilution make it a bad idea. Choosing what goes in the window is now its own discipline.",
          "**How do we know it works?** Without an eval suite you are guessing. The single most reliable signal of a strong AI Engineer is that they built the evaluation before they tuned the prompt.",
          "**What happens when it's wrong?** Not *if*. Fallbacks, confidence thresholds, human review, guardrails, and a way to notice failures in production.",
          "**What does it cost per request, and does that survive 100× traffic?** Token maths on a whiteboard is a routine interview task.",
        ]},
        { type: "diagram", name: "ai-engineer-stack", caption: "The four layers of a GenAI product. You rent the model; you own the two layers where quality is decided." },
        { type: "h2", text: "The skills that actually get you hired in 2026" },
        { type: "compare", caption: "What job descriptions ask for, translated.", columns: ["What the JD says", "What it means in practice"], rows: [
          { label: "\"Experience with RAG\"", cells: ["You can chunk, embed, retrieve, rerank — and diagnose why retrieval returned the wrong passage"] },
          { label: "\"Agentic workflows\"", cells: ["You can design a tool-calling loop with termination conditions, retries, and a human-in-the-loop escape hatch"] },
          { label: "\"Prompt / context engineering\"", cells: ["You treat the context window as a budget and can explain what you put in it and why"] },
          { label: "\"Evaluation frameworks\"", cells: ["You have built a golden dataset and an LLM-as-judge rubric, and you know their failure modes"] },
          { label: "\"LLMOps / production experience\"", cells: ["Tracing, cost dashboards, prompt versioning, canary releases, rate-limit and fallback handling"] },
          { label: "\"Familiar with MCP\"", cells: ["You know how tools and data are exposed to a model through a standard protocol, and how to secure that"] },
        ]},
        { type: "callout", kind: "warn", text: "The most common way candidates fail an AI Engineer loop is not weak Python. It's answering *\"how would you know if this is good?\"* with a shrug. Have a real answer — dataset, metric, threshold, regression suite — for every system you describe." },
        { type: "h2", text: "The mindset shift from ordinary software" },
        { type: "p", text: "Traditional software is deterministic: the same input yields the same output, and a bug is reproducible. A language model is a **probabilistic component**. The same prompt can produce different text; correctness is a distribution, not a boolean; and \"fixing\" a failure often means shifting a rate from 8% to 2% rather than eliminating it." },
        { type: "list", items: [
          "You **test statistically**, over a dataset, not with a single assertion.",
          "You **design for being wrong**: validation, retries, constrained outputs, and human review at the right threshold.",
          "You **version prompts like code**, because a prompt edit is a deploy with no type checker behind it.",
          "You **measure before and after**, because intuition about prompt changes is famously unreliable.",
        ]},
        { type: "quote", text: "The model is the easy part. The system around the model is the product.", cite: "The sentence this entire course is an expansion of" },
      ],
      takeaways: [
        "An AI Engineer builds products on models they didn't train — the work is systems engineering, not modelling.",
        "The role exists because pretrained models moved the hard problem from 'can it work?' to 'is it reliable, cheap, safe, and fast enough?'",
        "Daily decisions: which model tier, prompt vs retrieve vs fine-tune, what goes in the context window, how it's evaluated, and what happens when it's wrong.",
        "Hiring signals in 2026: RAG, agents/tool use, context engineering, evals, LLMOps, and MCP.",
        "Models are probabilistic components, so you test over datasets, design for failure, and version prompts like code.",
      ],
      flashcards: [
        { front: "AI Engineer vs ML Engineer", back: "An ML Engineer trains and serves models (data → pipeline → checkpoint). An AI Engineer builds systems on top of existing models (prompting, retrieval, tools, evals, serving), treating the model as a dependency." },
        { front: "The default order for improving an LLM feature", back: "Prompt → retrieve → fine-tune → (rarely) pretrain. Move down a rung only when the rung above provably can't get there — each step costs far more effort and lock-in." },
        { front: "Why can't you unit-test an LLM feature the usual way?", back: "Output is probabilistic, so correctness is a rate over a dataset, not a single assertion. You need a golden set, a metric, a threshold, and a regression run in CI." },
        { front: "What's the strongest signal of a senior AI Engineer in an interview?", back: "They build the evaluation before tuning the prompt, and can state the dataset, the metric, the threshold, and the failure modes of their own eval." },
      ],
      quiz: [
        { q: "A support bot gives outdated answers about your product's pricing. What's the right first move?", options: ["Fine-tune the model on your docs", "Add retrieval over the current pricing docs", "Increase the temperature", "Switch to a larger model"], answer: 1, explain: "Missing or stale *knowledge* is a retrieval problem. Fine-tuning bakes information in at training time and goes stale immediately — it changes behaviour and format, not facts." },
        { q: "Which best describes the core difficulty of AI engineering?", options: ["Designing neural network architectures", "Making a probabilistic component reliable inside a deterministic product", "Labelling large datasets", "Optimising CUDA kernels"], answer: 1, explain: "The model is rented. The engineering is everything that makes its variable output dependable: context, constraints, evaluation, fallbacks, and observability." },
        { q: "Your prompt change 'feels better' in the playground. What should happen before it ships?", options: ["Ship it — playground testing is the eval", "Run it against a golden dataset and compare scores", "Ask a teammate to eyeball ten outputs", "Raise the temperature to check robustness"], answer: 1, explain: "Prompt intuition is unreliable and changes often trade one failure mode for another. A versioned golden set with a scored comparison is the only way to know if you improved anything." },
      ],
    },
    {
      slug: "how-llms-actually-work",
      title: "How an LLM actually works",
      summary:
        "Tokens, the context window, attention, and sampling — the mechanical picture you need so that latency, cost, and hallucination stop being mysteries.",
      minutes: 12,
      blocks: [
        { type: "p", text: "You do not need to be able to derive backpropagation to be an excellent AI Engineer. You *do* need a mechanical picture of what happens between your prompt going in and text coming out, because almost every practical problem — cost, latency, truncation, hallucination, non-determinism — is explained by that mechanism." },
        { type: "h2", text: "Everything is tokens" },
        { type: "p", text: "A model does not see characters or words. Text is first split by a **tokenizer** into **tokens** — subword fragments — and each token is mapped to an integer ID. As a rule of thumb, **1 token ≈ 4 characters ≈ ¾ of an English word**, so 1,000 tokens is roughly 750 words. Common words are one token; rare words, code identifiers, emoji, and non-English scripts fragment into many." },
        { type: "callout", kind: "key", text: "Tokens are the currency of everything. **Price** is per token. **Context limits** are in tokens. **Latency** scales with tokens. When you estimate cost or debug truncation, you are always counting tokens — never words." },
        { type: "code", lang: "python", caption: "Counting tokens before you send anything expensive", code: `# Anthropic — ask the API to count exactly, no guessing
import anthropic

client = anthropic.Anthropic()
count = client.messages.count_tokens(
    model="claude-sonnet-4-5",
    system="You are a precise financial analyst.",
    messages=[{"role": "user", "content": long_document}],
)
print(count.input_tokens)

# Rough offline estimate when you just need an order of magnitude
approx_tokens = len(text) / 4` },
        { type: "callout", kind: "warn", text: "Tokenizers are model-family specific — a count from one vendor's tokenizer does not transfer to another's, and non-English text can cost 2–3× more tokens for the same meaning. If you serve a multilingual product, measure cost per language, not per request." },
        { type: "diagram", name: "llm-io", caption: "A single model call: prefill reads the whole prompt at once, then decode emits one token at a time." },
        { type: "h2", text: "Prefill and decode — where your latency lives" },
        { type: "p", text: "Generation happens in two phases with completely different performance characteristics, and confusing them is the single most common source of bad latency reasoning." },
        { type: "compare", caption: "Two phases, two bottlenecks.", columns: ["Phase", "What happens", "Scales with", "Bound by"], rows: [
          { label: "Prefill", cells: ["The whole prompt is processed in parallel", "Input length", "Compute (GPU FLOPs)"] },
          { label: "Decode", cells: ["One token generated at a time, each conditioned on all previous", "Output length", "Memory bandwidth"] },
        ]},
        { type: "list", items: [
          "**TTFT (time to first token)** is dominated by prefill — so a huge prompt makes the user wait before *anything* appears.",
          "**TPOT (time per output token)** governs how fast text then streams. Total ≈ TTFT + (output tokens × TPOT).",
          "**Output length is usually the bigger latency lever than input length.** Asking for a summary in 3 bullets instead of 3 paragraphs is often a 3× speedup.",
          "**Streaming doesn't make it faster — it makes it feel faster**, which is frequently enough.",
        ]},
        { type: "h2", text: "The context window" },
        { type: "p", text: "The **context window** is the maximum number of tokens the model can attend to in one call. Crucially it is shared by *everything*: system prompt, tool definitions, conversation history, retrieved documents, and the response being generated. A 200K window with a 190K prompt leaves you 10K of answer." },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Token** = a subword fragment, the unit models read and write. **Tokenizer** = the component that splits text into tokens (usually BPE — byte-pair encoding). **Context window** = the total token budget for one call, input plus output. **Attention** = the mechanism letting each token look at other tokens to decide what matters. **Autoregressive** = generating one token at a time, each conditioned on everything before it. **Logits** = the raw scores the model assigns to every possible next token, before sampling turns them into a choice. **Knowledge cutoff** = the date after which the model saw no training data." },
        { type: "h3", text: "Long context is not free" },
        { type: "list", items: [
          "**Cost is linear in input tokens** — a 100K-token prompt on every turn is a budget decision, not a convenience.",
          "**Attention cost is quadratic in sequence length** in the naive formulation, which is why very long prompts get slow as well as expensive.",
          "**\"Lost in the middle\"**: retrieval accuracy sags for facts buried in the centre of a very long context. Put the critical material at the start or the end.",
          "**More context can lower quality.** Irrelevant text is a distractor. Ten precise passages beat a hundred vaguely related ones.",
        ]},
        { type: "callout", kind: "tip", text: "The existence of a million-token window is not an instruction to fill it. Treat the context window as a **budget you spend deliberately** — that discipline is exactly what the industry now calls *context engineering*." },
        { type: "h2", text: "Sampling: why the same prompt gives different answers" },
        { type: "p", text: "The model's actual output is a **probability distribution over every token in its vocabulary**. A sampler then picks one. The sampler's settings are why output varies." },
        { type: "compare", caption: "The knobs, and when to move them.", columns: ["Parameter", "What it does", "Practical setting"], rows: [
          { label: "temperature", cells: ["Flattens (high) or sharpens (low) the distribution", "0–0.3 for extraction, classification, code; 0.7–1.0 for brainstorming and copy"] },
          { label: "top_p (nucleus)", cells: ["Samples only from the smallest set of tokens whose probabilities sum to p", "Leave at default; tune this *or* temperature, not both"] },
          { label: "top_k", cells: ["Samples only from the k most likely tokens", "Rarely needed in production APIs"] },
          { label: "max_tokens", cells: ["Hard cap on output length", "Always set it — it is your cost and latency ceiling"] },
          { label: "stop sequences", cells: ["Ends generation when a string appears", "Useful for structured or delimiter-based formats"] },
        ]},
        { type: "callout", kind: "warn", text: "**Temperature 0 is not deterministic in practice.** Floating-point non-associativity across batched GPU kernels, mixture-of-experts routing, and load-dependent batching all mean identical requests can still diverge. Design tests that tolerate variation — asserting on exact strings is a flaky test waiting to happen." },
        { type: "h2", text: "Where hallucination comes from" },
        { type: "p", text: "A language model is optimised to produce **plausible continuations**, not true ones. It has no separate store of facts to check against and no built-in signal for \"I don't know\". Fluent wrongness is therefore the default failure mode, not an anomaly." },
        { type: "diagram", name: "failure-modes", caption: "Four distinct root causes, four distinct fixes — treating them as one problem is why teams get stuck." },
        { type: "compare", caption: "Diagnose before you treat.", columns: ["Symptom", "Root cause", "Fix"], rows: [
          { label: "Confident but outdated facts", cells: ["Knowledge cutoff", "Retrieval over current sources"] },
          { label: "Invented citations, APIs, or IDs", cells: ["Plausible-continuation pressure", "Ground in retrieved text; require quotes; validate identifiers"] },
          { label: "Ignores part of a long prompt", cells: ["Lost in the middle / context dilution", "Shorten, reorder, split the task"] },
          { label: "Fails the same edge case every time", cells: ["Capability or format gap", "Better examples, task decomposition, or fine-tuning"] },
        ]},
        { type: "callout", kind: "key", text: "You cannot prompt a model into knowing something it was never shown. **Missing knowledge is a retrieval problem; unreliable behaviour is a prompting or fine-tuning problem.** Sorting a failure into the right bucket is most of the debugging." },
        { type: "h2", text: "The one-paragraph version of the architecture" },
        { type: "p", text: "Tokens become vectors (**embeddings**). Those vectors pass through dozens of identical **transformer blocks**, each containing an **attention** layer — where every position gathers information from other positions — and a feed-forward layer that transforms it. The final layer produces a score for every token in the vocabulary; sampling picks one; it is appended to the input; repeat. Modern large models often use **mixture-of-experts (MoE)**, where only a fraction of parameters activate per token, which is how a model can have huge total capacity at moderate inference cost." },
        { type: "quote", text: "Attention is all you need.", cite: "Vaswani et al., 2017 — the paper the entire industry is downstream of" },
      ],
      takeaways: [
        "Everything is tokens: pricing, context limits, and latency are all measured in them, never in words.",
        "Prefill (parallel, compute-bound) sets TTFT; decode (sequential, bandwidth-bound) sets streaming speed — output length usually dominates latency.",
        "The context window is shared by system prompt, tools, history, retrieval, and the answer — and filling it costs money, speed, and often accuracy.",
        "Sampling parameters explain output variation; temperature 0 reduces but does not guarantee determinism.",
        "Hallucination has distinct root causes — cutoff, plausible continuation, context dilution, capability gap — and each has a different fix.",
      ],
      flashcards: [
        { front: "Roughly how many tokens is 1,000 English words?", back: "About 1,300 tokens (1 token ≈ ¾ of a word ≈ 4 characters). Code, rare words, and non-English text fragment into far more." },
        { front: "Prefill vs decode", back: "Prefill processes the whole prompt in parallel and is compute-bound — it sets time to first token. Decode generates one token at a time and is memory-bandwidth-bound — it sets time per output token." },
        { front: "Why isn't temperature 0 fully deterministic?", back: "Floating-point non-associativity across batched GPU kernels, MoE expert routing, and variable batching mean identical requests can still produce different tokens. Never assert on exact output strings." },
        { front: "What is 'lost in the middle'?", back: "The observed drop in retrieval accuracy for facts placed in the centre of a very long context. Put critical material near the beginning or the end." },
        { front: "Which failure does retrieval fix, and which does it not?", back: "It fixes missing or stale knowledge. It does not fix bad formatting, wrong tone, or a genuine capability gap — those need prompting, decomposition, or fine-tuning." },
      ],
      quiz: [
        { q: "A user complains your assistant takes 6 seconds before any text appears. Which lever helps most?", options: ["Lower the temperature", "Shorten the prompt / retrieved context", "Increase max_tokens", "Ask for longer answers"], answer: 1, explain: "Time to first token is dominated by prefill, which scales with input length. Trimming context (or caching it) is the direct fix; sampling settings barely matter." },
        { q: "Which statement about the context window is correct?", options: ["It applies only to your input", "Input and output share one budget", "It resets each turn automatically", "It's measured in words"], answer: 1, explain: "System prompt, tool definitions, history, retrieved context, and the generated answer all draw on the same token budget — which is why a near-full prompt truncates the reply." },
        { q: "Your model invents plausible-looking API endpoints that don't exist. Best fix?", options: ["Raise temperature for creativity", "Ground it in retrieved API docs and validate outputs against the real schema", "Increase max_tokens", "Add 'do not hallucinate' to the system prompt"], answer: 1, explain: "Invented identifiers come from plausible-continuation pressure with no ground truth in context. Supply the real reference material and verify the output programmatically — instructions alone don't create knowledge." },
        { q: "You're extracting structured fields from invoices. What temperature?", options: ["1.0 for flexibility", "0–0.2", "0.7 as a balance", "Temperature doesn't affect extraction"], answer: 1, explain: "Extraction has one correct answer, so you want the sharpest distribution. Creativity is a defect here." },
      ],
    },
    {
      slug: "the-model-landscape",
      title: "The model landscape and how to choose",
      summary:
        "Frontier vs open-weight, reasoning models vs fast models, MoE and small language models — and the routing decision that quietly determines your margin.",
      minutes: 11,
      blocks: [
        { type: "p", text: "There is no \"best model\". There is a **best model for this request, at this price, at this latency, given your evals** — and that answer changes every few months. What doesn't change is the shape of the decision, so learn the shape rather than a leaderboard." },
        { type: "diagram", name: "model-landscape", caption: "Capability against cost and latency. Open weights move you along the cost axis, not the capability axis." },
        { type: "h2", text: "The tiers you'll actually choose between" },
        { type: "compare", caption: "Every major provider ships roughly this ladder.", columns: ["Tier", "Good for", "Watch out for"], rows: [
          { label: "Frontier", cells: ["Hard reasoning, long agent runs, ambiguous instructions, code", "Cost per call and rate limits at scale"] },
          { label: "Fast / mid tier", cells: ["The high-volume majority: classification, extraction, routine Q&A, drafting", "Silent quality loss on the hard tail if you don't measure"] },
          { label: "Small (1–8B) / on-device", cells: ["Latency-critical, offline, private, or embedded work", "Narrow competence — needs tight tasks and good prompts"] },
          { label: "Reasoning models", cells: ["Maths, planning, multi-step derivation, hard debugging", "Slow and token-hungry; overkill for most requests"] },
          { label: "Embedding & reranker models", cells: ["Retrieval, clustering, dedup, classification features", "Not generative — a separate model family with its own evals"] },
        ]},
        { type: "h2", text: "Reasoning models and test-time compute" },
        { type: "p", text: "The defining shift of the last two years: instead of only making models bigger at *training* time, providers let models spend more compute at **inference** time — generating an internal chain of reasoning before answering. More thinking tokens buys measurably better answers on hard problems, and buys nothing on easy ones." },
        { type: "callout", kind: "key", text: "**Test-time compute turns latency and cost into a dial you can turn per request.** Treat \"how much should this request think?\" as a routing decision, not a global setting. Reasoning effort on a FAQ lookup is pure waste; reasoning effort on a migration plan is the whole point." },
        { type: "h2", text: "Frontier API vs open-weight self-hosting" },
        { type: "compare", caption: "The decision that shows up in every architecture review.", columns: ["Dimension", "Hosted frontier API", "Open-weight, self-hosted"], rows: [
          { label: "Time to first version", cells: ["Minutes", "Days to weeks (GPUs, serving stack, ops)"] },
          { label: "Peak capability", cells: ["Highest available", "Strong, typically a step behind the frontier"] },
          { label: "Cost curve", cells: ["Pay per token — cheap at low volume, painful at very high volume", "Fixed GPU cost — expensive when idle, excellent at high, steady utilisation"] },
          { label: "Data control", cells: ["Governed by contract and vendor policy", "Data never leaves your boundary"] },
          { label: "Customisation", cells: ["Prompting, tools, sometimes hosted fine-tuning", "Full: LoRA, quantization, custom decoding, logits access"] },
          { label: "Operational burden", cells: ["Rate limits and vendor incidents", "Your GPUs, your OOMs, your 3 a.m. page"] },
        ]},
        { type: "callout", kind: "tip", text: "The honest heuristic: **start on a hosted API, and self-host when one of three things is true** — sustained volume makes per-token pricing more expensive than GPUs, data residency forbids the API, or you need weight-level control (fine-tuning, custom decoding, guaranteed model stability). \"We might want to self-host later\" is not a reason to self-host now." },
        { type: "h2", text: "Reading benchmarks without fooling yourself" },
        { type: "list", items: [
          "**Public benchmarks are contaminated.** Popular test sets leak into training data. A leaderboard jump may be memorisation.",
          "**Benchmarks measure their own task, not yours.** A model can top a coding benchmark and be mediocre at your codebase's idioms.",
          "**Arena / preference scores measure what people *like*** — often verbosity and confident tone — which is not the same as correctness.",
          "**Averages hide the slices you care about.** Ask about your hardest customer segment, your longest documents, your non-English traffic.",
          "**The only benchmark that matters is yours.** 100–300 real examples from your own traffic beats every public leaderboard for deciding what to ship.",
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**MoE** (Mixture of Experts) = an architecture where a router activates only a few of many expert sub-networks per token, giving large total capacity at lower inference cost. **SLM** (Small Language Model) = a compact model (roughly 1–8B parameters) able to run on a single GPU, a laptop, or a phone. **Test-time compute** = spending extra inference tokens on reasoning to improve the answer. **Distillation** = training a small model to imitate a larger one. **Multimodal** = handling more than text — images, audio, video. **Knowledge cutoff** = the last date represented in training data. **Model card** = the vendor document describing a model's intended use, limits, and evaluations." },
        { type: "h2", text: "Routing: the pattern that pays for itself" },
        { type: "p", text: "Mature systems rarely use one model. They **route**: a cheap classifier or heuristic sends each request to the smallest model likely to succeed, with escalation when confidence is low or validation fails." },
        { type: "steps", items: [
          { title: "Start with one strong model", text: "Get quality right first. Optimising cost before you have a working baseline optimises the wrong thing." },
          { title: "Build the eval set", text: "Real requests, correct answers, and the slices you care about. You cannot route safely without it." },
          { title: "Measure the cheap tier on that set", text: "Very often the cheap model matches on 80–90% of traffic. Now you know exactly what downgrading costs." },
          { title: "Route by request class, not by vibe", text: "A small classifier, a rule on request type, or a complexity heuristic — something inspectable and testable." },
          { title: "Escalate on failure signals", text: "Low confidence, failed schema validation, refusal, or a judge score below threshold → retry on the stronger model." },
          { title: "Re-evaluate on every model release", text: "New releases routinely make last quarter's routing table obsolete. Keep the eval suite runnable in one command." },
        ]},
        { type: "callout", kind: "warn", text: "Model versions are moving ground. Pin explicit model IDs in production — never a floating alias — and treat a model upgrade as a release: run the full eval suite, canary it, and keep the previous version one config change away." },
      ],
      takeaways: [
        "Models come in tiers — frontier, fast, small/on-device, reasoning, and embedding/reranker — and each has a job.",
        "Test-time compute makes 'how hard should this think?' a per-request dial, not a global setting.",
        "Self-host when volume economics, data residency, or weight-level control demand it — not on principle.",
        "Public benchmarks are contaminated and off-target; 100–300 examples of your own traffic decide better.",
        "Routing cheap-by-default with escalation on failure signals is the standard way to hold quality while cutting cost.",
      ],
      flashcards: [
        { front: "What is a mixture-of-experts (MoE) model?", back: "An architecture where a router activates only a subset of expert sub-networks per token — large total parameter count, much lower compute per token than a dense model of the same size." },
        { front: "When should you self-host an open-weight model?", back: "When sustained volume makes GPUs cheaper than per-token pricing, when data must not leave your boundary, or when you need weight-level control (fine-tuning, custom decoding, guaranteed stability)." },
        { front: "Why are public benchmark scores unreliable?", back: "Test-set contamination, mismatch with your actual task, preference scores rewarding verbosity, and averages that hide your important slices. Your own eval set is the only decisive one." },
        { front: "What is test-time compute?", back: "Spending additional inference tokens on internal reasoning before answering. It improves hard problems and wastes money on easy ones — so route it per request." },
      ],
      quiz: [
        { q: "Your classification endpoint runs 5M requests/month on a frontier model. Cheapest safe improvement?", options: ["Fine-tune the frontier model", "Evaluate a small model on your eval set and route the easy majority to it", "Reduce max_tokens", "Switch providers"], answer: 1, explain: "Classification is exactly where cheap tiers hold up. Measure on your own eval set, route the bulk to the small model, and escalate only what fails — typically an order-of-magnitude cost cut with measured quality." },
        { q: "A vendor's new model tops every leaderboard. What do you do first?", options: ["Switch production immediately", "Run your own eval suite and canary it", "Ignore it", "Fine-tune it before testing"], answer: 1, explain: "Leaderboards don't measure your task, and behaviour changes can break prompts tuned to the old model. Treat any model change as a release: eval, canary, keep a rollback path." },
        { q: "Which workload is the best fit for a reasoning model?", options: ["Extracting fields from 100k invoices", "Classifying support tickets", "Planning a multi-step database migration", "Rewriting marketing copy"], answer: 2, explain: "Reasoning models earn their extra tokens on multi-step planning and derivation. High-volume extraction and classification want the cheap, fast tier." },
      ],
    },
    {
      slug: "the-genai-stack",
      title: "The GenAI stack and how a request flows",
      summary:
        "The four layers of every AI product, what you build vs what you rent, and a trace of one request from user turn to grounded answer.",
      minutes: 10,
      blocks: [
        { type: "p", text: "Every serious GenAI product — a support copilot, a coding agent, a document pipeline — is assembled from the same four layers. Learning the layers means you can read an unfamiliar architecture in minutes, and it gives you a structure for answering system-design questions." },
        { type: "diagram", name: "ai-engineer-stack", caption: "You rent the model layer. You own orchestration — which is where product quality is actually decided." },
        { type: "h2", text: "Layer by layer" },
        { type: "compare", caption: "What lives where.", columns: ["Layer", "Components", "Who owns it"], rows: [
          { label: "Product surface", cells: ["Chat UI, IDE plugin, batch job, API endpoint, workflow trigger", "Product + frontend"] },
          { label: "Orchestration", cells: ["Prompt templates, retrieval, tool calling, agent loop, memory, guardrails, routing", "You — this is the AI Engineer's layer"] },
          { label: "Model layer", cells: ["Generation models, embedding models, rerankers, safety classifiers, speech/vision models", "Rented (API) or hosted (open weights)"] },
          { label: "Data & infrastructure", cells: ["Vector store, object storage, relational DB, cache, gateway, GPUs, traces and evals", "Platform + you"] },
        ]},
        { type: "callout", kind: "key", text: "Teams consistently over-invest in the layer they rent and under-invest in the layer they own. **Two teams using the identical model ship products of wildly different quality**, and the difference is almost entirely orchestration and evaluation." },
        { type: "h2", text: "One request, end to end" },
        { type: "steps", items: [
          { title: "Request arrives", text: "Authenticated, rate-limited, and tagged with a tenant and a trace ID. Every downstream step carries that ID." },
          { title: "Input guardrail", text: "Cheap checks first: PII detection, prompt-injection heuristics, off-topic classification, size limits. Rejecting here costs a millisecond instead of a model call." },
          { title: "Context assembly", text: "The expensive, interesting step. Retrieve relevant passages, rerank them, load the relevant slice of conversation memory, and attach only the tool definitions this request could plausibly need." },
          { title: "Model call", text: "Route to a tier, apply prompt caching to the stable prefix, set max_tokens, stream the response." },
          { title: "Tool loop, if any", text: "The model requests a tool; you validate arguments, execute with least privilege and a timeout, feed results back, and repeat under a hard step limit." },
          { title: "Output guardrail & validation", text: "Schema validation, citation checking, safety classification, and PII redaction — before the user sees a single token." },
          { title: "Emit and observe", text: "Stream to the user; write a trace with prompt version, model ID, token counts, latency breakdown, tool calls, and cost. Sample it into the eval set." },
        ]},
        { type: "callout", kind: "tip", text: "Say this flow out loud in a system-design interview and you have already structured your answer. Then dig into whichever step the interviewer is actually interested in — usually context assembly or evaluation." },
        { type: "h2", text: "Build, buy, or rent" },
        { type: "compare", caption: "Where the sensible defaults sit in 2026.", columns: ["Concern", "Default", "Build your own when"], rows: [
          { label: "Generation model", cells: ["Rent (hosted API)", "Volume, residency, or weight-level control demands it"] },
          { label: "Vector store", cells: ["pgvector if you already run Postgres; a managed vector DB above ~10M chunks", "You have genuinely extreme scale or latency needs"] },
          { label: "Orchestration", cells: ["Thin code you own, with a framework only where it pays", "Always — this is the differentiating layer"] },
          { label: "Evaluation", cells: ["A hosted eval/tracing tool early, your own harness as you mature", "Your quality bar is domain-specific, which it usually is"] },
          { label: "Gateway / routing", cells: ["A gateway (self-hosted or managed) in front of all providers", "Rarely worth building from scratch"] },
        ]},
        { type: "callout", kind: "warn", text: "Framework caution: agent frameworks are excellent for prototyping and can become the thing you debug at 3 a.m. Adopt one for the parts that are genuinely tedious (streaming, retries, tracing, state) and keep your prompts, tools, and control flow legible in your own code." },
        { type: "h2", text: "The non-negotiables from day one" },
        { type: "list", items: [
          "**A trace for every request** — prompt version, model, tokens, latency, tools, cost, outcome. Retrofitting observability is miserable.",
          "**Prompts in version control**, not in a database row edited by hand and not pasted from a doc.",
          "**An eval set that runs in one command**, even if it starts with 30 examples.",
          "**A cost-per-request number** somebody looks at weekly.",
          "**A kill switch** — a config flag that disables a feature, falls back to a smaller model, or reverts to a non-AI path without a deploy.",
        ]},
        { type: "quote", text: "Two teams, the same model, wildly different products. The difference is everything you build around it.", cite: "Why this course is 14 modules and not one" },
      ],
      takeaways: [
        "Every GenAI product has four layers: product surface, orchestration, model, and data/infrastructure.",
        "Orchestration is the layer you own and the layer that decides quality — the model is a rented dependency.",
        "The canonical request path: guardrail in → context assembly → routed model call → tool loop → validation → stream and trace.",
        "Sensible defaults: rent the model, pgvector before a dedicated vector DB, own your orchestration, buy tracing early.",
        "Day-one non-negotiables: tracing, versioned prompts, a runnable eval set, a cost number, and a kill switch.",
      ],
      flashcards: [
        { front: "Name the four layers of the GenAI stack", back: "Product surface, orchestration (prompts, retrieval, tools, agent loop, guardrails), model layer (generation, embeddings, rerankers, classifiers), and data/infrastructure (vector store, cache, gateway, GPUs, traces)." },
        { front: "Which layer decides product quality?", back: "Orchestration. Everyone can call the same model; what differs is context assembly, tool design, validation, and evaluation." },
        { front: "What belongs in a production LLM trace?", back: "Trace ID, tenant, prompt version, model ID, input/output token counts, latency split by stage, tool calls and their results, guardrail verdicts, cost, and the final outcome." },
        { front: "What is a kill switch in an AI product?", back: "A config flag that disables the feature, downgrades to a smaller model, or falls back to a non-AI path — without a code deploy. The cheapest incident-response tool you can build." },
      ],
      quiz: [
        { q: "Where should an input guardrail run?", options: ["After the model responds", "Before the model call, as a cheap early check", "Only in the UI", "Inside the vector database"], answer: 1, explain: "Cheap checks first: rejecting an injection attempt or an oversized payload before a model call saves cost, latency, and risk. Output guardrails then run after generation — you need both." },
        { q: "Two teams build a support assistant on the same model; one is far better. Most likely reason?", options: ["A secret model version", "Better orchestration — retrieval quality, context assembly, and evaluation", "Higher temperature", "More GPUs"], answer: 1, explain: "The rented layer is identical. Differences come from what you put in the context window, how tools are designed and validated, and whether the team measures quality systematically." },
        { q: "You're starting a RAG product and already run Postgres. Default vector store?", options: ["A dedicated managed vector DB immediately", "pgvector in the Postgres you already operate", "In-memory numpy", "A graph database"], answer: 1, explain: "pgvector keeps documents, metadata, permissions, and vectors in one transactional system you already back up and monitor. Move to a dedicated store when scale or latency actually demands it." },
      ],
    },
  ],
};
