import type { Pattern } from "./types";

export const patterns: Pattern[] = [
  {
    name: "The four-layer GenAI stack",
    tagline: "Product surface → orchestration → model → data & infrastructure.",
    diagram: "ai-engineer-stack",
    when: "The mental model to open any AI system-design answer with — it tells the interviewer where you'll spend your time before you draw a single box.",
    watch: "Teams over-invest in the model layer, which they rent, and under-invest in orchestration and evaluation, which decide the product.",
    accent: "iris",
  },
  {
    name: "Model tiering & routing",
    tagline: "Cheap model for the easy majority, frontier model for the hard tail.",
    diagram: "model-landscape",
    when: "Any high-volume workload where most requests are easy — classification, extraction, routine Q&A — and a minority need real reasoning.",
    watch: "You need a routing signal you trust and an eval per class, or you silently downgrade quality to save money. Log every routing decision; a misroute looks exactly like a quality regression.",
    accent: "teal",
  },
  {
    name: "The RAG pipeline",
    tagline: "Offline ingest fills the index; the online path retrieves, reranks, grounds, and cites.",
    diagram: "rag-pipeline",
    when: "The default architecture whenever answers must come from a corpus you control — large, changing, permissioned, or requiring attribution.",
    watch: "Most teams build the online path first and then discover every real problem is in the offline half: parsing, chunking, freshness, and deletions.",
    accent: "iris",
  },
  {
    name: "Hybrid retrieval with reranking",
    tagline: "Vector + BM25, fused by RRF, narrowed by a cross-encoder.",
    diagram: "hybrid-rerank",
    when: "Essentially every production RAG system. It's the most reliable single quality upgrade available and needs no architectural change.",
    watch: "Retrieve wide (≈50) then narrow hard (5–10). Retrieving only 5 up front permanently loses the answers ranked 6–50, and no reranker can recover them.",
    accent: "teal",
  },
  {
    name: "Small-to-big retrieval",
    tagline: "Search precise small chunks; return the coherent parent section.",
    diagram: "chunking-strategies",
    when: "When the right chunk is found but answers still miss context from the surrounding paragraphs — the most common 'retrieval worked, answer didn't' complaint.",
    watch: "The parent must still fit your context budget. Combine with reranking, or you trade precision for a window full of loosely relevant prose.",
    accent: "teal",
  },
  {
    name: "Contextual retrieval",
    tagline: "Prepend generated situating context to each chunk before embedding it.",
    diagram: "rag-pipeline",
    when: "When chunks are meaningless in isolation — 'the limit was raised to 500 rpm in Q2' with no indication of which product, plan, or year.",
    watch: "It costs one cheap model call per chunk at ingest. Use prompt caching on the document prefix or the ingest bill for a large corpus will surprise you.",
    accent: "iris",
  },
  {
    name: "Corrective RAG (grade, then branch)",
    tagline: "Score the retrieved context before generating, and act on the score.",
    diagram: "rag-triad",
    when: "Any system where a confident answer from irrelevant context is worse than no answer — which is most enterprise deployments.",
    watch: "It needs a real fallback. Grading context as irrelevant and then generating anyway is theatre; the branch must lead to re-retrieval, a different source, or an honest decline.",
    accent: "rose",
  },
  {
    name: "Agentic RAG",
    tagline: "Retrieval becomes a tool the model calls, grades, and retries.",
    diagram: "agentic-rag",
    when: "Research and investigation work where one retrieval genuinely can't answer the question and the next query depends on what the last one found.",
    watch: "Unbounded without hard limits: max retrieval calls, token budget, wall-clock timeout, and deduplication of repeated queries. One ambiguous question can otherwise loop until something times out.",
    accent: "iris",
  },
  {
    name: "Text-to-SQL with a semantic layer",
    tagline: "The model composes defined metrics; it doesn't invent joins over raw tables.",
    diagram: "graph-rag",
    when: "Counting, aggregation, and trend questions — 'how many enterprise accounts churned last quarter' — that similarity search structurally cannot answer.",
    watch: "Read-only credentials, row-level security, single-SELECT validation, statement timeouts, and show the SQL. The dangerous failure isn't an error — it's a query that runs and returns a plausible wrong number.",
    accent: "amber",
  },
  {
    name: "The tool-calling loop",
    tagline: "The model requests; your code validates, authorises, executes, and returns.",
    diagram: "tool-call-loop",
    when: "Any time a model needs to reach beyond its context — look something up, compute something, or change something.",
    watch: "The model never executes anything. Authorise as the end user from the session, never from a model-supplied identifier, and return recoverable errors as tool results rather than raising into the loop.",
    accent: "amber",
  },
  {
    name: "The bounded agent loop",
    tagline: "Reason, act, observe, repeat — with four exits that guarantee termination.",
    diagram: "agent-loop",
    when: "When the sequence of steps genuinely depends on what earlier steps discover. If you can draw the steps in advance, write a workflow instead.",
    watch: "All four exits are required: step limit, token budget, wall-clock timeout, and no-progress detection. And partial results must be labelled incomplete, or downstream systems consume them as finished.",
    accent: "amber",
  },
  {
    name: "Read/write separation with approval",
    tagline: "Reads loop freely; writes and outward actions pause for a human.",
    diagram: "agent-loop",
    when: "Any agent that can affect the real world — payments, emails, deletions, deploys, tickets.",
    watch: "The cheapest high-value safety control there is. Show the human the proposed action *and its reasoning and evidence*, and record who approved what and when.",
    accent: "rose",
  },
  {
    name: "Supervisor with sub-agents",
    tagline: "A coordinator decomposes work and delegates to scoped sub-agents.",
    diagram: "multi-agent-topologies",
    when: "When sub-tasks need their own large context, parallelise cleanly, or require different tools and permissions.",
    watch: "Split for context isolation, not job titles. Expect a 3–15× token multiplier, lossy summarised hand-offs, and compounding error rates — use typed contracts across every boundary.",
    accent: "iris",
  },
  {
    name: "Trust-boundary separation",
    tagline: "The agent that reads untrusted content holds no credentials and has no egress.",
    diagram: "prompt-injection",
    when: "Whenever an agent processes anything an attacker could influence — web pages, uploaded files, incoming email, issue comments, tool results.",
    watch: "This breaks the lethal trifecta by construction. The untrusted-content agent returns a typed, length-capped summary; the privileged agent never sees raw external text.",
    accent: "rose",
  },
  {
    name: "MCP tool catalogue",
    tagline: "Expose each system once as a server; every host and agent composes from it.",
    diagram: "mcp-architecture",
    when: "Once more than one application or agent needs the same system — the point at which N×M integrations become N+M.",
    watch: "The protocol standardises exposure, not authorisation. Per-user identity, per-tool least privilege, rate limits, bounded results, and audit remain the server author's job.",
    accent: "teal",
  },
  {
    name: "The guardrail sandwich",
    tagline: "Cheap deterministic checks outside, expensive model-based checks inside.",
    diagram: "guardrail-layers",
    when: "Every production LLM endpoint. Input checks reject before you pay for a model call; output checks run before a single token reaches the user.",
    watch: "Each check needs an explicit failure mode — closed, open, redact, human, or fallback — and a measured false-positive rate. A 95%-accurate filter blocks 5,000 legitimate requests a day at 100k volume.",
    accent: "rose",
  },
  {
    name: "The AI gateway",
    tagline: "One layer for routing, caching, retries, quotas, and tracing.",
    diagram: "production-architecture",
    when: "As soon as more than one service calls a model, or as soon as you need a shared view of cost.",
    watch: "Adopt rather than build. The failure mode without one is three services with three retry behaviours, three cost stories, and no consistent trace schema.",
    accent: "iris",
  },
  {
    name: "Prompt-prefix caching",
    tagline: "Order the prompt stable-content-first so the provider can reuse the processed prefix.",
    diagram: "prompt-anatomy",
    when: "Any workload where the system prompt, tool definitions, or a long static document repeat across requests — which is nearly all of them.",
    watch: "Caching matches an exact prefix. A timestamp or request ID at the top invalidates the whole thing on every call — the most common self-inflicted cost wound there is.",
    accent: "teal",
  },
  {
    name: "Semantic caching",
    tagline: "Serve a stored answer when a new question is close enough to an old one.",
    diagram: "caching-layers",
    when: "High-volume workloads with a heavy head of repeated questions — FAQ traffic, common support intents.",
    watch: "A quality decision dressed as a cost saving. 'How do I cancel?' and 'How do I cancel without a fee?' are near neighbours with different answers. Scope by tenant, never cache personalised answers, and measure false-hit rate.",
    accent: "amber",
  },
  {
    name: "Distil and route",
    tagline: "Teach a small model the teacher's behaviour; escalate only when it falters.",
    diagram: "distillation",
    when: "High-volume narrow tasks where a frontier model works but its per-call price doesn't survive the traffic.",
    watch: "The student matches the teacher where you measured, not in general. Train on real production inputs, filter teacher outputs hard, and keep an escalation path on low confidence or failed validation.",
    accent: "amber",
  },
  {
    name: "Eval-gated release",
    tagline: "PR with eval delta → CI assertions → judged suite → canary → progressive rollout.",
    diagram: "deploy-lifecycle",
    when: "Every change to a prompt, model, tool schema, retrieval config, or guardrail policy — all of which are deployable artefacts.",
    watch: "Pin explicit model versions and keep the previous prompt version one flag away, so rollback is seconds. A floating model alias upgrades beneath you at the provider's convenience.",
    accent: "iris",
  },
  {
    name: "Trace-and-feedback loop",
    tagline: "Every production failure becomes a permanent eval case.",
    diagram: "eval-loop",
    when: "From day one. Retrofitting observability after an incident is miserable, and an eval suite that doesn't grow goes stale.",
    watch: "The trace must contain the *rendered* prompt and the retrieved chunk IDs, or 'we can't reproduce it' is where the investigation dies.",
    accent: "teal",
  },
];
