import type { Module } from "./types";

export const foundations: Module = {
  id: "foundations",
  title: "ML Foundations",
  blurb:
    "The concepts every AI interview starts with: the kinds of learning, the bias–variance tradeoff, how models are trained with gradient descent, and how you actually measure whether a model is any good.",
  accent: "iris",
  lessons: [
    {
      slug: "types-of-machine-learning",
      title: "The kinds of machine learning",
      summary:
        "Supervised, unsupervised, and reinforcement learning — the map interviewers expect you to place any problem onto, plus the classification-vs-regression split inside supervised learning.",
      minutes: 9,
      blocks: [
        { type: "p", text: "**Machine learning** is getting a program to improve at a task by learning patterns from data, instead of being explicitly programmed with rules. Almost every AI interview opens by checking that you can place a problem into the right *category* of learning — because the category dictates the data you need, the algorithms you'd reach for, and how you'd evaluate success." },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Model** = the mathematical function (with tunable numbers called *parameters* or *weights*) that maps an input to a prediction. **Training / fitting** = the process of adjusting those parameters so predictions match the data. **Inference** = using the trained model to predict on new data. **Feature** = one input variable (a column); **label / target** = the answer you're trying to predict." },
        { type: "diagram", name: "learning-types", caption: "The three paradigms: learn from labeled answers, from unlabeled structure, or from reward." },
        { type: "h2", text: "Supervised learning" },
        { type: "p", text: "You have **labeled** examples — inputs `X` paired with known correct outputs `y` — and the model learns the mapping `X → y`. This is the workhorse of applied ML. It splits into two problem types:" },
        { type: "compare", caption: "The two flavors of supervised learning.", columns: ["Type", "Predicts", "Examples", "Typical metric"], rows: [
          { label: "Classification", cells: ["A discrete class/category", "Spam vs not, disease vs healthy, which of 10 digits", "Accuracy, precision/recall, F1, AUC"] },
          { label: "Regression", cells: ["A continuous number", "House price, tomorrow's temperature, click-through rate", "MSE, RMSE, MAE, R²"] },
        ]},
        { type: "h2", text: "Unsupervised learning" },
        { type: "p", text: "No labels — the model finds structure in the data on its own. The two big sub-tasks are **clustering** (group similar points, e.g. k-means for customer segments) and **dimensionality reduction** (compress many features into a few while keeping information, e.g. PCA). Anomaly detection and topic modeling also live here." },
        { type: "h2", text: "Reinforcement learning" },
        { type: "p", text: "An **agent** takes actions in an **environment** and learns from a **reward** signal, aiming to maximize cumulative reward over time. There's no fixed labeled dataset — the agent generates experience by acting. It powers game-playing (AlphaGo), robotics, and — crucially for modern AI — the **RLHF** step that aligns large language models to human preferences." },
        { type: "callout", kind: "key", text: "Interview reflex: when handed a problem, first ask 'do I have labels?' Labels → supervised (then: is the target a category or a number?). No labels but I want structure → unsupervised. Learning from trial-and-error with a reward → reinforcement." },
        { type: "h2", text: "Two more terms you'll be asked to contrast" },
        { type: "list", items: [
          "**Semi-supervised learning** — a small labeled set plus a large unlabeled set; common because labels are expensive.",
          "**Self-supervised learning** — the data creates its own labels (e.g. 'predict the next word' or 'fill in the masked pixel'). This is how modern LLMs and vision models are *pretrained* at scale, and a favorite interview topic.",
        ]},
        { type: "callout", kind: "tip", text: "If asked 'is a recommendation system supervised or unsupervised?', the honest answer is 'it depends how you frame it' — collaborative filtering can be matrix factorization (unsupervised-ish) or you can frame next-click as supervised. Showing you can reframe a problem is a strong signal." },
      ],
      takeaways: [
        "The three paradigms: supervised (labeled X→y), unsupervised (find structure, no labels), reinforcement (learn from reward).",
        "Supervised splits into classification (discrete class) and regression (continuous number) — each with its own metrics.",
        "Self-supervised learning (predict-the-next-token / masked prediction) is how modern LLMs are pretrained at scale.",
        "The first move on any ML problem is to place it in the right category — it dictates data, algorithms, and evaluation.",
      ],
      flashcards: [
        { front: "Classification vs regression", back: "Both are supervised. Classification predicts a discrete class (spam/not); regression predicts a continuous number (price). Different metrics: accuracy/F1 vs MSE/RMSE." },
        { front: "What is self-supervised learning?", back: "Learning where the data generates its own labels — e.g. predict the next word or reconstruct a masked input. It's how LLMs and modern vision models are pretrained without human labels." },
        { front: "How would you spot a reinforcement learning problem?", back: "There's an agent taking actions in an environment, no fixed labeled dataset, and learning is driven by a reward signal to maximize over time (games, robotics, RLHF)." },
      ],
      quiz: [
        { q: "Predicting tomorrow's exact temperature in °C is which kind of task?", options: ["Classification", "Regression", "Clustering", "Reinforcement learning"], answer: 1, explain: "The target is a continuous number, so it's regression (supervised)." },
        { q: "Grouping customers into segments with no predefined categories is…", options: ["Supervised classification", "Regression", "Unsupervised clustering", "Semi-supervised"], answer: 2, explain: "No labels, and you're grouping similar points — that's unsupervised clustering (e.g. k-means)." },
        { q: "'Predict the next word in a sentence' as a training objective is an example of…", options: ["Reinforcement learning", "Self-supervised learning", "Supervised regression", "Clustering"], answer: 1, explain: "The label (the next word) comes free from the data itself — that's self-supervised, the basis of LLM pretraining." },
      ],
    },
    {
      slug: "bias-variance-tradeoff",
      title: "Overfitting & the bias–variance tradeoff",
      summary:
        "Why a model that aces the training set can fail in the real world — and the single most important framework for reasoning about model error in interviews.",
      minutes: 11,
      blocks: [
        { type: "p", text: "The whole game of supervised learning is **generalization**: performing well on *new, unseen* data, not just the data you trained on. The bias–variance tradeoff is the framework for understanding *why* models fail to generalize, and it comes up in nearly every ML interview." },
        { type: "h2", text: "Two ways to be wrong" },
        { type: "list", items: [
          "**Bias** — error from wrong assumptions; the model is too simple to capture the real pattern. High bias = **underfitting**: it does poorly on both training and test data (e.g. fitting a straight line to a curve).",
          "**Variance** — error from being too sensitive to the training data's noise; the model memorizes quirks that don't generalize. High variance = **overfitting**: great on training data, poor on test data.",
        ]},
        { type: "diagram", name: "overfitting", caption: "Underfit (too simple), good fit (captures the trend), overfit (chases noise)." },
        { type: "callout", kind: "key", text: "Total expected error ≈ bias² + variance + irreducible noise. Lowering one often raises the other — that's the *tradeoff*. You can't drive both to zero, so you aim for the sweet spot that minimizes their sum." },
        { type: "diagram", name: "bias-variance", caption: "As complexity rises, bias falls but variance climbs; total error is a U-curve with a sweet spot." },
        { type: "h2", text: "How to diagnose it" },
        { type: "p", text: "Compare training error to validation error — this is the diagnostic interviewers want to hear:" },
        { type: "compare", caption: "Reading the two error numbers.", columns: ["Training error", "Validation error", "Diagnosis", "Fix"], rows: [
          { label: "High", cells: ["High", "Underfitting (high bias)", "Bigger model, more features, train longer"] },
          { label: "Low", cells: ["High", "Overfitting (high variance)", "More data, regularization, simpler model"] },
          { label: "Low", cells: ["Low", "Good fit ✓", "Ship it (keep monitoring)"] },
        ]},
        { type: "h2", text: "Fighting overfitting: regularization" },
        { type: "p", text: "**Regularization** is any technique that discourages the model from becoming too complex, trading a little training accuracy for better generalization. The classics:" },
        { type: "list", items: [
          "**L2 (Ridge)** — penalizes the sum of *squared* weights; shrinks weights smoothly toward zero, spreading influence across features.",
          "**L1 (Lasso)** — penalizes the sum of *absolute* weights; drives some weights exactly to zero, so it also does **feature selection**.",
          "**Dropout** — randomly switch off neurons during training so the network can't rely on any one path (deep learning).",
          "**Early stopping** — stop training when validation error starts rising, before the model memorizes.",
          "**Data augmentation & more data** — the most reliable cure for variance is simply more (or more varied) training data.",
        ]},
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Generalization** = how well a model does on data it never saw in training. **Regularization** = deliberately constraining a model (e.g. penalizing large weights) to reduce overfitting. **Hyperparameter** = a setting you choose *before* training (learning rate, regularization strength, tree depth) as opposed to a weight the model learns. **λ (lambda)** = the knob controlling how strong the regularization penalty is." },
        { type: "callout", kind: "warn", text: "A classic trap: 'my model has 99% training accuracy, so it's great.' High training accuracy alone tells you nothing — it may just be memorizing. Always report the gap between training and held-out validation/test performance." },
      ],
      takeaways: [
        "Generalization — doing well on unseen data — is the real goal; the bias–variance tradeoff explains why models miss it.",
        "High bias = underfitting (too simple, bad on train and test); high variance = overfitting (memorizes noise, bad on test).",
        "Diagnose by comparing training vs validation error; the gap tells you which problem you have and which fix to apply.",
        "Regularization (L1/L2, dropout, early stopping) and more/varied data are the standard cures for overfitting.",
      ],
      flashcards: [
        { front: "Define bias and variance", back: "Bias = error from overly simple assumptions (underfitting). Variance = error from over-sensitivity to training noise (overfitting). Total error ≈ bias² + variance + irreducible noise." },
        { front: "Low training error but high validation error means…", back: "Overfitting (high variance). Cures: more data, regularization (L1/L2, dropout), simpler model, early stopping." },
        { front: "L1 vs L2 regularization", back: "L2 (Ridge) penalizes squared weights — shrinks smoothly. L1 (Lasso) penalizes absolute weights — drives some to exactly zero, doing feature selection." },
      ],
      quiz: [
        { q: "A model scores 98% on training data and 65% on validation data. This is…", options: ["Underfitting", "Overfitting", "A good fit", "Data leakage guaranteed"], answer: 1, explain: "Large gap with high train / low validation performance is the signature of overfitting (high variance)." },
        { q: "Which regularizer also performs feature selection by zeroing out weights?", options: ["L2 / Ridge", "L1 / Lasso", "Dropout", "Batch norm"], answer: 1, explain: "L1 (Lasso) drives some weights exactly to zero, effectively selecting features." },
        { q: "Your model underfits (high bias). A reasonable fix is to…", options: ["Add more regularization", "Use a simpler model", "Increase model capacity / add features", "Collect less data"], answer: 2, explain: "Underfitting means too little capacity — add features or use a more expressive model; regularizing further would make it worse." },
      ],
    },
    {
      slug: "how-models-train",
      title: "How models learn: loss & gradient descent",
      summary:
        "The engine under almost every model — a loss function to measure wrongness and gradient descent to reduce it. Know this cold; it underlies neural networks and LLMs alike.",
      minutes: 10,
      blocks: [
        { type: "p", text: "Training a model means finding the parameters (weights) that make its predictions least wrong. Two ideas make that concrete: a **loss function** that scores how wrong the model is, and an **optimization algorithm** — almost always **gradient descent** — that adjusts weights to lower that score." },
        { type: "h2", text: "The loss function" },
        { type: "p", text: "A **loss** (or cost) function maps predictions and true answers to a single number: high when the model is wrong, low when it's right. Training = minimizing it. The right loss depends on the task:" },
        { type: "compare", caption: "Common loss functions and when to use them.", columns: ["Loss", "Task", "Intuition"], rows: [
          { label: "MSE (mean squared error)", cells: ["Regression", "Average squared gap; punishes big errors hard"] },
          { label: "MAE (mean absolute error)", cells: ["Regression", "Average absolute gap; robust to outliers"] },
          { label: "Cross-entropy / log loss", cells: ["Classification", "Punishes confident wrong probabilities heavily"] },
        ]},
        { type: "h2", text: "Gradient descent" },
        { type: "p", text: "The **gradient** is the vector of partial derivatives of the loss with respect to each weight — it points in the direction the loss increases fastest. So to *decrease* loss, step in the *opposite* direction. Repeat until you reach a minimum." },
        { type: "diagram", name: "gradient-descent", caption: "Start at random weights and repeatedly step downhill along the negative gradient toward the minimum." },
        { type: "code", lang: "text", caption: "The core update rule — memorize it", code: "θ  :=  θ  −  η · ∇J(θ)\n\nθ      the parameters (weights)\nJ(θ)   the loss as a function of the weights\n∇J(θ)  the gradient (slope) of the loss\nη      the learning rate (step size)" },
        { type: "h2", text: "The learning rate" },
        { type: "p", text: "**η (eta)**, the learning rate, sets the step size and is the single most important hyperparameter to tune. Too **small** → training crawls and can stall in a poor spot. Too **large** → you overshoot the minimum and the loss diverges (bounces or explodes). In practice people use a schedule that starts higher and decays." },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**Gradient** = the multi-dimensional slope of the loss; points uphill, so we move opposite it. **Epoch** = one full pass through the training data. **Batch** = the subset of examples used to compute one gradient step. **Convergence** = when the loss stops meaningfully decreasing. **Local minimum** = a dip that isn't the lowest possible — a risk for non-convex problems." },
        { type: "h2", text: "Batch, stochastic, and mini-batch" },
        { type: "list", items: [
          "**Batch GD** — compute the gradient over the *entire* dataset per step. Accurate but slow and memory-heavy.",
          "**Stochastic GD (SGD)** — one example per step. Fast and noisy; the noise can help escape bad minima.",
          "**Mini-batch GD** — a small batch (e.g. 32–512) per step. The practical default — balances speed, stability, and hardware efficiency. This is what deep learning uses.",
        ]},
        { type: "callout", kind: "tip", text: "Interviewers love 'what if loss isn't going down?' Good answers: learning rate too high (diverging) or too low (crawling); bad feature scaling; a bug in the loss/gradient; data not shuffled; or you need a better optimizer (Adam) — covered in the Deep Learning module." },
      ],
      takeaways: [
        "Training = minimizing a loss function that scores how wrong predictions are; pick the loss to match the task (MSE for regression, cross-entropy for classification).",
        "Gradient descent repeatedly steps weights opposite the gradient: θ := θ − η·∇J(θ).",
        "The learning rate η is the key knob: too small stalls, too large diverges.",
        "Mini-batch gradient descent (small batches per step) is the practical default that powers deep learning.",
      ],
      flashcards: [
        { front: "Write the gradient descent update rule", back: "θ := θ − η·∇J(θ) — move the parameters θ opposite the gradient of the loss, scaled by learning rate η." },
        { front: "Which loss for classification vs regression?", back: "Classification → cross-entropy (log loss). Regression → MSE (punishes big errors) or MAE (robust to outliers)." },
        { front: "Batch vs stochastic vs mini-batch GD", back: "Batch = whole dataset per step (accurate, slow). SGD = one example (fast, noisy). Mini-batch = small batches, the practical default balancing both." },
      ],
      quiz: [
        { q: "In θ := θ − η·∇J(θ), what does η control?", options: ["The number of features", "The step size (learning rate)", "The batch size", "The loss function choice"], answer: 1, explain: "η is the learning rate — the size of each step down the gradient." },
        { q: "Loss is oscillating wildly and increasing. The most likely cause is…", options: ["Learning rate too high", "Too much data", "Learning rate too low", "Using mini-batches"], answer: 0, explain: "A too-large learning rate overshoots the minimum, causing the loss to bounce or diverge." },
        { q: "Cross-entropy loss is the standard choice for…", options: ["Regression", "Classification", "Clustering", "Dimensionality reduction"], answer: 1, explain: "Cross-entropy (log loss) scores predicted class probabilities against true labels — the classification default." },
      ],
    },
    {
      slug: "evaluating-models",
      title: "Evaluating models the right way",
      summary:
        "Accuracy lies on imbalanced data. Master precision, recall, F1, ROC/AUC, the metrics for regression, and honest validation — the most interview-tested topic in all of ML.",
      minutes: 12,
      blocks: [
        { type: "p", text: "Choosing and defending the right **evaluation metric** is one of the most common ML interview themes, because a model is only as good as the number you judge it by — and the obvious number (accuracy) is often the wrong one." },
        { type: "h2", text: "The confusion matrix" },
        { type: "p", text: "For classification, everything starts here: a 2×2 table of predictions vs reality. All the important metrics are ratios of its four cells." },
        { type: "diagram", name: "confusion-matrix", caption: "True/false × positive/negative — the four outcomes every classification metric is built from." },
        { type: "compare", caption: "The core classification metrics.", columns: ["Metric", "Formula", "Answers the question"], rows: [
          { label: "Accuracy", cells: ["(TP+TN) / all", "What fraction did I get right? (misleading if imbalanced)"] },
          { label: "Precision", cells: ["TP / (TP+FP)", "Of those I flagged positive, how many really were?"] },
          { label: "Recall (sensitivity)", cells: ["TP / (TP+FN)", "Of all real positives, how many did I catch?"] },
          { label: "F1 score", cells: ["2·P·R / (P+R)", "Harmonic mean of precision & recall — one balanced number"] },
        ]},
        { type: "callout", kind: "key", text: "The precision–recall tradeoff is the heart of it. Raising the decision threshold catches fewer false positives (↑ precision) but misses more real positives (↓ recall). Which you favor depends on the cost of each error — there's no universally 'best' number." },
        { type: "h2", text: "Why accuracy lies: the imbalanced-data trap" },
        { type: "p", text: "Suppose 99% of transactions are legitimate and 1% are fraud. A model that predicts 'legit' for *everything* scores **99% accuracy** — and catches zero fraud. Its recall on fraud is 0%. This is the canonical interview example for why accuracy is dangerous on imbalanced data, and why you'd report precision/recall (or AUC) instead." },
        { type: "callout", kind: "tip", text: "Match the metric to the cost of errors. Cancer screening: favor **recall** — missing a real case (false negative) is far worse than a false alarm. Spam filter: favor **precision** — flagging a real email as spam (false positive) is worse than letting one spam through." },
        { type: "h2", text: "ROC curve and AUC" },
        { type: "p", text: "The **ROC curve** plots true-positive rate against false-positive rate as you sweep the decision threshold. **AUC** (area under it) summarizes performance across *all* thresholds into one number: 1.0 is perfect, 0.5 is random guessing. AUC is threshold-independent and popular for comparing classifiers — though on heavily imbalanced data, the **precision–recall curve** (PR-AUC) is often more informative." },
        { type: "diagram", name: "roc-curve", caption: "AUC is the area under the ROC curve — a threshold-independent score from 0.5 (random) to 1.0 (perfect)." },
        { type: "h2", text: "Regression metrics" },
        { type: "list", items: [
          "**MSE / RMSE** — (root) mean squared error; RMSE is in the target's units. Punishes large errors heavily.",
          "**MAE** — mean absolute error; more robust to outliers, easier to interpret.",
          "**R² (coefficient of determination)** — fraction of variance explained; 1.0 is perfect, 0 is no better than predicting the mean, and it can go negative.",
        ]},
        { type: "h2", text: "Honest validation" },
        { type: "p", text: "A metric only means something if it's measured on data the model never trained on. That requires disciplined data splitting and awareness of leakage." },
        { type: "diagram", name: "data-splits", caption: "Hold out a test set you touch only once; use cross-validation to make the estimate stable." },
        { type: "list", items: [
          "**Train / validation / test.** Train on one split, tune hyperparameters on validation, and report final numbers on a test set touched exactly once.",
          "**k-fold cross-validation.** Rotate which fold is the validation set k times and average — a more stable estimate that uses all data, great when data is limited.",
          "**Data leakage.** When information from the test set (or the future) sneaks into training — e.g. scaling using the whole dataset's mean, or a feature that encodes the label. It inflates scores and is a top real-world failure. Interviewers probe for it.",
        ]},
        { type: "callout", kind: "warn", text: "Never tune on the test set. Every time you look at the test set to make a decision, it leaks into your process and stops being an honest estimate of real-world performance. Tune on validation; touch test once, at the end." },
        { type: "callout", kind: "note", title: "Jargon, decoded", text: "**TP/FP/FN/TN** = true/false positives/negatives — the confusion-matrix cells. **Threshold** = the probability cutoff for calling a prediction 'positive.' **AUC** = area under the ROC curve, a single threshold-independent score. **Data leakage** = test/future info contaminating training, giving falsely high scores. **Stratified split** = a split that preserves the class ratio in each part — important for imbalanced data." },
      ],
      takeaways: [
        "Accuracy is misleading on imbalanced data; report precision, recall, F1, or AUC instead.",
        "Precision (of flagged, how many right) vs recall (of real positives, how many caught) trade off via the threshold — choose based on error costs.",
        "AUC summarizes a classifier across all thresholds; PR-AUC is better for heavy imbalance. Regression uses RMSE/MAE/R².",
        "Measure metrics only on held-out data; use train/val/test and k-fold CV, and watch relentlessly for data leakage.",
      ],
      flashcards: [
        { front: "Precision vs recall", back: "Precision = TP/(TP+FP): of predicted positives, how many are right. Recall = TP/(TP+FN): of actual positives, how many you caught. They trade off via the threshold." },
        { front: "Why is accuracy a bad metric on imbalanced data?", back: "A trivial model predicting the majority class scores high accuracy while catching none of the rare class. Use precision/recall/F1 or AUC/PR-AUC instead." },
        { front: "What is data leakage?", back: "When information from the test set or the future contaminates training (e.g. scaling on the full dataset, or a feature that encodes the label), inflating scores that collapse in production." },
        { front: "What does AUC measure?", back: "Area under the ROC curve — a threshold-independent score of how well the model ranks positives above negatives. 1.0 perfect, 0.5 random." },
      ],
      quiz: [
        { q: "On a dataset that is 99% negative, a model predicting 'negative' always gets…", options: ["99% accuracy but 0% recall on positives", "50% accuracy", "High F1", "High recall"], answer: 0, explain: "Accuracy is inflated by the majority class while the model catches zero positives — the classic imbalance trap." },
        { q: "For cancer screening, you'd typically optimize for high…", options: ["Precision", "Recall", "Accuracy", "Specificity"], answer: 1, explain: "Missing a real case (false negative) is very costly, so you favor recall even at the price of more false alarms." },
        { q: "Scaling your features using the mean of the entire dataset before splitting causes…", options: ["Better generalization", "Data leakage", "Underfitting", "Higher bias"], answer: 1, explain: "The test set's statistics leak into training, giving an over-optimistic estimate — always fit scalers on training data only." },
      ],
    },
  ],
};
